/**
 * Calcul mental — les fractions, les mesures, les durées, les petits problèmes.
 *
 * Cinq rituels, quinze minutes, à l'oral ou à l'ardoise. Une fiche donne **les dix questions et les dix réponses**. Ce sont les rituels où le calcul rencontre le concret : combien de grammes dans deux kilos et demi, de huit heures quarante-cinq à midi trente.
 *
 * Deux exceptions à la règle des dix. « Les problèmes en une phrase » en
 * compte cinq, parce qu'un problème se dit, se redit et se réfléchit. « Les
 * durées » en compte dix alors que sa consigne en annonce cinq : les cinq
 * premières font la séance, les cinq suivantes attendent le jour où il en
 * redemande, et l'adulte n'a rien à inventer dans un cas comme dans l'autre.
 *
 * Ce qu'une fiche donne, et pourquoi : voir `lib/fiches/types.ts`. En deux
 * mots — le matériel exact, le corrigé quand il y en a un, et ce qu'on
 * regarde. Un adulte qui l'ouvre ne doit plus rien avoir à chercher.
 *
 * L'ordre des séries est l'ordre de l'année : la première fiche tombe en
 * novembre ou en décembre, la treizième en juin. En période 2 — les
 * premières fiches de chaque série — les nombres entiers restent à quatre chiffres, comme le
 * demande le programme du cycle 3 (BO spécial n° 16 du 17 avril 2025). Les
 * grands nombres, la virgule et les fractions plus grandes que 1 arrivent
 * ensuite, dans l'ordre où le manuel les installe.
 *
 * **Réservé aux adultes** : ces fiches portent les corrigés.
 *
 * Rien de tout ceci n'a été relu par un enseignant. Ça doit l'être.
 */

import { f, type Fiche } from "./types";

export const calculGrandeurs: Fiche[] = [
  /* ── Les fractions d’une quantité ──────────────────────────────────────
     Une part, puis plusieurs parts. On divise par le nombre du bas, on
     multiplie par le nombre du haut : la méthode tient en une phrase, et
     c'est elle qu'on répète toute l'année plutôt qu'une liste de résultats. */

  f(
    "cg-fractions-01",
    "Les fractions d’une quantité",
    "La moitié · partager en deux parts égales",
    [
      "Vous dites le nombre, il annonce la moitié. À l’oral, ou sur l’ardoise s’il préfère écrire.",
      "S’il bloque, proposez-lui de partager en deux paquets : « dix bonbons pour deux, combien chacun ? ». C’est la même question.",
      "Pas de chronomètre. On laisse le temps qu’il faut, puis on donne la réponse et on passe à la suivante.",
    ],
    [
      "La moitié de 10",
      "La moitié de 8",
      "La moitié de 14",
      "La moitié de 20",
      "La moitié de 16",
      "La moitié de 30",
      "La moitié de 24",
      "La moitié de 50",
      "La moitié de 18",
      "La moitié de 100",
    ],
    ["5", "4", "7", "10", "8", "15", "12", "25", "9", "50"],
    "Les moitiés de 10, 20, 50 et 100 viennent souvent sans effort ; celles de 14, 18 et 24 demandent un détour. Si le détour passe par les doubles (« 7 et 7 font 14, donc c’est 7 »), c’est un bon chemin, gardez-le.",
  ),

  f(
    "cg-fractions-02",
    "Les fractions d’une quantité",
    "La moitié et le quart · couper, puis recouper",
    [
      "On installe une idée : le quart, c’est la moitié de la moitié. Dites-le une fois au début, puis laissez-le s’en servir.",
      "Les questions vont par paires : la moitié d’un nombre, puis son quart. La deuxième s’appuie sur la première.",
      "Quinze minutes suffisent largement pour dix questions. S’il reste du temps, il en invente une pour vous.",
    ],
    [
      "La moitié de 12",
      "Le quart de 12",
      "La moitié de 20",
      "Le quart de 20",
      "Le quart de 8",
      "Le quart de 16",
      "La moitié de 40",
      "Le quart de 40",
      "Le quart de 100",
      "Le quart de 24",
    ],
    ["6", "3", "10", "5", "2", "4", "20", "10", "25", "6"],
    "On regarde s’il passe par la moitié pour trouver le quart, ou s’il cherche directement à diviser par quatre. Les deux marchent ; celui qu’il choisit dit ce qu’il a compris du mot « quart ».",
  ),

  f(
    "cg-fractions-03",
    "Les fractions d’une quantité",
    "Le tiers · partager en trois",
    [
      "Le tiers s’appuie sur la table de 3 : « le tiers de 12, c’est le nombre qui fait 12 quand on le prend trois fois ».",
      "Si une table manque, donnez-la sans façon et reposez la question : ce n’est pas le jour de la réviser.",
      "La huitième question reprend le nombre de la septième. C’est voulu : il verra que la moitié et le tiers d’un même nombre ne donnent pas la même chose.",
    ],
    [
      "Le tiers de 6",
      "Le tiers de 9",
      "Le tiers de 12",
      "Le tiers de 15",
      "Le tiers de 24",
      "Le tiers de 30",
      "La moitié de 18",
      "Le tiers de 18",
      "Le tiers de 21",
      "Le tiers de 60",
    ],
    ["2", "3", "4", "5", "8", "10", "9", "6", "7", "20"],
    "Le passage de la moitié de 18 au tiers de 18 est le moment intéressant : s’il répond 9 deux fois, c’est le mot « tiers » qu’il faut reprendre, pas le calcul.",
  ),

  f(
    "cg-fractions-04",
    "Les fractions d’une quantité",
    "Moitié, tiers, quart mêlés",
    [
      "Trois nombres reviennent avec les trois fractions : 36 puis 48. C’est fait exprès, pour qu’il compare les résultats.",
      "Annoncez la fraction avant le nombre : « le tiers… de 36 ». Il a ainsi le temps de préparer l’opération.",
      "Si une réponse tarde, dites-la simplement et enchaînez. On reviendra sur celle-là une autre fois.",
    ],
    [
      "La moitié de 36",
      "Le tiers de 36",
      "Le quart de 36",
      "La moitié de 48",
      "Le quart de 48",
      "Le tiers de 48",
      "La moitié de 70",
      "Le quart de 80",
      "Le tiers de 90",
      "La moitié de 96",
    ],
    ["18", "12", "9", "24", "12", "16", "35", "20", "30", "48"],
    "Voyez s’il remarque que plus on partage en petites parts, plus la part est petite. Cette remarque-là vaut plus que les dix réponses réunies ; si elle vient de lui, dites-lui qu’elle est juste.",
  ),

  f(
    "cg-fractions-05",
    "Les fractions d’une quantité",
    "Le cinquième et le dixième",
    [
      "Le dixième se lit dans le nombre : le dixième de 70, c’est 7. Laissez-le trouver cette régularité plutôt que de la donner.",
      "Le cinquième demande la table de 5, qu’il connaît bien ; c’est un rituel confortable, autant en profiter.",
      "Dix questions, un aller simple : on ne revient pas en arrière, on ne recompte pas ce qui est juste.",
    ],
    [
      "Le cinquième de 10",
      "Le cinquième de 25",
      "Le cinquième de 40",
      "Le dixième de 50",
      "Le dixième de 100",
      "Le dixième de 70",
      "Le cinquième de 100",
      "Le dixième de 120",
      "Le cinquième de 60",
      "Le dixième de 300",
    ],
    ["2", "5", "8", "5", "10", "7", "20", "12", "12", "30"],
    "S’il trouve le dixième en enlevant un zéro, il a vu quelque chose de solide. Demandez-lui si ça marcherait aussi pour 35 : la question ouvre la porte aux décimaux, sans qu’on ait à y répondre aujourd’hui.",
  ),

  f(
    "cg-fractions-06",
    "Les fractions d’une quantité",
    "Plusieurs parts · les deux tiers, les trois quarts",
    [
      "La méthode en une phrase, à dire une fois avant de commencer : on divise par le nombre du bas, puis on multiplie par le nombre du haut.",
      "Pour la première question, faites-la à voix haute avec lui : « 12 divisé par 3 font 4, et 4 fois 2 font 8 ». Ensuite il conduit.",
      "Deux opérations dans la tête, c’est une charge : s’il perd le fil au milieu, redonnez-lui le résultat de la première étape.",
    ],
    [
      "Les deux tiers de 12",
      "Les trois quarts de 20",
      "Les deux tiers de 15",
      "Les trois quarts de 8",
      "Les deux tiers de 30",
      "Les trois quarts de 40",
      "Les deux tiers de 24",
      "Les trois quarts de 100",
      "Les deux tiers de 60",
      "Les trois quarts de 60",
    ],
    ["8", "15", "10", "6", "20", "30", "16", "75", "40", "45"],
    "Le point à surveiller est l’ordre des deux étapes. Diviser d’abord garde des nombres petits ; multiplier d’abord marche aussi mais fatigue plus vite. S’il multiplie d’abord, montrez-lui l’autre chemin sans lui retirer le sien.",
  ),

  f(
    "cg-fractions-07",
    "Les fractions d’une quantité",
    "Cinquièmes et dixièmes, plusieurs parts",
    [
      "Même méthode que la fois précédente, avec des parts plus petites et plus nombreuses.",
      "Les nombres choisis tombent juste : la division est toujours exacte, il n’y a jamais de reste à gérer.",
      "S’il veut écrire l’étape intermédiaire sur l’ardoise, laissez-le. Ce n’est pas de la triche, c’est de la méthode.",
    ],
    [
      "Les deux cinquièmes de 20",
      "Les trois cinquièmes de 25",
      "Les quatre cinquièmes de 50",
      "Les trois dixièmes de 100",
      "Les sept dixièmes de 200",
      "Les deux cinquièmes de 45",
      "Les neuf dixièmes de 50",
      "Les trois cinquièmes de 100",
      "Les quatre cinquièmes de 30",
      "Les cinq dixièmes de 80",
    ],
    ["8", "15", "40", "30", "140", "18", "45", "60", "24", "40"],
    "La dernière question cache une égalité : cinq dixièmes, c’est la moitié. S’il le dit, c’est que les fractions commencent à se parler entre elles ; sinon, gardez la remarque pour une prochaine fois.",
  ),

  f(
    "cg-fractions-08",
    "Les fractions d’une quantité",
    "Des fractions de mesures",
    [
      "Mêmes fractions, mais sur des grandeurs : une heure, un kilogramme, un mètre, un litre. La réponse porte une unité.",
      "Rappelez au besoin les équivalences de départ : une heure fait 60 minutes, un kilogramme 1 000 grammes, un mètre 100 centimètres, un litre 100 centilitres.",
      "Demandez l’unité dans la réponse. « 30 » et « 30 minutes » ne disent pas la même chose, et c’est le moment de le faire sentir.",
    ],
    [
      "La moitié d’une heure, en minutes",
      "Le quart d’une heure, en minutes",
      "Les trois quarts d’une heure, en minutes",
      "La moitié d’un kilogramme, en grammes",
      "Le quart d’un kilogramme, en grammes",
      "La moitié d’un mètre, en centimètres",
      "Le tiers d’une heure, en minutes",
      "Le quart d’un litre, en centilitres",
      "La moitié d’un kilomètre, en mètres",
      "Les trois quarts d’un litre, en centilitres",
    ],
    [
      "30 min",
      "15 min",
      "45 min",
      "500 g",
      "250 g",
      "50 cm",
      "20 min",
      "25 cL",
      "500 m",
      "75 cL",
    ],
    "L’heure est la grandeur qui résiste, parce qu’elle se partage en 60 et non en 100. S’il répond 50 pour la moitié d’une heure, c’est le 60 qu’il faut réinstaller, pas la fraction.",
  ),

  f(
    "cg-fractions-09",
    "Les fractions d’une quantité",
    "Sixièmes, huitièmes, neuvièmes",
    [
      "Des parts plus fines, et des tables moins fréquentées : 6, 8 et 9. Donnez la table dès qu’elle manque.",
      "Le huitième peut se trouver en coupant trois fois en deux : la moitié, la moitié, la moitié. Proposez ce chemin s’il cherche.",
      "Trois questions demandent plusieurs parts ; elles arrivent à la fin, quand la mécanique est lancée.",
    ],
    [
      "Le sixième de 12",
      "Le sixième de 30",
      "Le huitième de 16",
      "Le huitième de 40",
      "Le neuvième de 27",
      "Le neuvième de 45",
      "Les cinq sixièmes de 12",
      "Les trois huitièmes de 16",
      "Le sixième de 60",
      "Les sept huitièmes de 80",
    ],
    ["2", "5", "2", "5", "3", "5", "10", "6", "10", "70"],
    "Le sixième et le huitième se confondent volontiers quand on va vite. Si ça arrive, ralentissez le débit plutôt que de reprendre la notion : c’est l’écoute qui décroche, pas la compréhension.",
  ),

  f(
    "cg-fractions-10",
    "Les fractions d’une quantité",
    "Les grandes quantités",
    [
      "Mêmes fractions, nombres plus gros. L’idée : ce qui marche sur 12 marche sur 1 200, il suffit de garder les zéros.",
      "Dites-le une fois : « la moitié de 12 fait 6, donc la moitié de 1 200 fait 600 ». Puis laissez-le appliquer.",
      "S’il s’embrouille dans les zéros, faites-lui écrire le nombre sur l’ardoise avant de répondre. Voir le nombre suffit souvent.",
    ],
    [
      "La moitié de 1 200",
      "Le quart de 1 200",
      "Le tiers de 900",
      "Les trois quarts de 400",
      "La moitié de 2 500",
      "Le dixième de 4 500",
      "Les deux tiers de 3 000",
      "Le cinquième de 2 000",
      "Les trois quarts de 800",
      "La moitié de 7 000",
    ],
    ["600", "300", "300", "300", "1 250", "450", "2 000", "400", "600", "3 500"],
    "La moitié de 2 500 et celle de 7 000 sont les deux qui demandent de couper un nombre impair de centaines ou de milliers. S’il s’y arrête, c’est là qu’il faut revenir, avec des nombres du même genre : la moitié de 300, de 500, de 900.",
  ),

  f(
    "cg-fractions-11",
    "Les fractions d’une quantité",
    "Plus d’un tout · les fractions plus grandes que 1",
    [
      "Nouveauté du jour : le nombre du haut peut dépasser celui du bas. Les trois demis de 10, c’est un tout et demi, donc 15.",
      "Dites cette phrase avant de commencer, et refaites la première question avec lui : 10 divisé par 2 font 5, et 5 pris trois fois font 15.",
      "La méthode ne change pas d’un iota. C’est seulement le résultat qui devient plus grand que le nombre de départ, et ça surprend : prévenez-le.",
    ],
    [
      "Les trois demis de 10",
      "Les cinq quarts de 8",
      "Les quatre tiers de 9",
      "Les trois demis de 20",
      "Les cinq quarts de 20",
      "Les sept demis de 6",
      "Les cinq tiers de 12",
      "Les six cinquièmes de 10",
      "Les neuf quarts de 4",
      "Les quatre tiers de 30",
    ],
    ["15", "10", "12", "30", "25", "21", "20", "12", "9", "40"],
    "Le moment à guetter est celui où il accepte qu’une fraction puisse agrandir. S’il rature parce que « ça ne peut pas être plus grand », ce n’est pas une confusion de calcul : reprenez le partage du gâteau, en coupant deux gâteaux au lieu d’un.",
  ),

  f(
    "cg-fractions-12",
    "Les fractions d’une quantité",
    "Le chemin inverse · retrouver le tout",
    [
      "On renverse la question : on donne la part, il cherche le nombre de départ. « La moitié d’un nombre fait 7 ; quel est ce nombre ? »",
      "Le chemin est celui de la fraction, à l’envers : là où on divisait, on multiplie. Laissez-lui le découvrir sur les deux premières.",
      "Les trois dernières partent de plusieurs parts : on revient d’abord à une seule part, puis au tout. Deux étapes, comme d’habitude.",
    ],
    [
      "La moitié d’un nombre fait 7. Quel est ce nombre ?",
      "Le quart d’un nombre fait 5. Quel est ce nombre ?",
      "Le tiers d’un nombre fait 9. Quel est ce nombre ?",
      "La moitié d’un nombre fait 25. Quel est ce nombre ?",
      "Le cinquième d’un nombre fait 4. Quel est ce nombre ?",
      "Le dixième d’un nombre fait 8. Quel est ce nombre ?",
      "Les deux tiers d’un nombre font 10. Quel est ce nombre ?",
      "Les trois quarts d’un nombre font 15. Quel est ce nombre ?",
      "Le quart d’un nombre fait 12. Quel est ce nombre ?",
      "Les trois quarts d’un nombre font 90. Quel est ce nombre ?",
    ],
    [
      "14",
      "20",
      "27",
      "50",
      "20",
      "80",
      "15 (un tiers fait 5, donc le tout fait 15)",
      "20 (un quart fait 5, donc le tout fait 20)",
      "48",
      "120 (un quart fait 30, donc le tout fait 120)",
    ],
    "Les trois questions à plusieurs parts sont d’un autre calibre que les six premières. S’il les laisse passer, ce n’est pas la fraction qui manque : c’est le retour à une seule part, et c’est cette étape-là qu’on refera seule la prochaine fois.",
  ),

  f(
    "cg-fractions-13",
    "Les fractions d’une quantité",
    "Tout mêlé, en situation",
    [
      "Dernier tour de l’année : les fractions, les grandeurs, et deux questions posées à l’envers.",
      "Certaines réponses sont une fraction et non un nombre — la quatrième et la huitième. Il peut répondre « le quart » ou « un quart sur quatre », les deux disent la chose.",
      "Prenez les questions dans l’ordre : elles montent doucement, et la dernière demande deux étapes.",
    ],
    [
      "Un sac de 2 kg : la moitié, en grammes ?",
      "120 billes : le tiers ?",
      "Une heure et demie, en minutes ?",
      "250 g, quelle fraction d’un kilogramme ?",
      "Les deux tiers de 45",
      "Le cinquième de 350",
      "Les trois quarts de 2 000",
      "40 minutes, quelle fraction d’une heure ?",
      "Les cinq sixièmes de 36",
      "Un trajet de 60 km dont il a fait les trois cinquièmes : combien de kilomètres ?",
    ],
    [
      "1 000 g",
      "40",
      "90 min",
      "le quart",
      "30",
      "70",
      "1 500",
      "les deux tiers",
      "30",
      "36 km",
    ],
    "Après treize séances, ce qu’on regarde n’est plus le nombre de réponses justes mais la façon dont il s’y prend : s’il annonce la méthode avant de calculer (« je divise par 5, puis je multiplie par 3 »), la série a fait son travail.",
  ),
  /* ── Les problèmes en une phrase ───────────────────────────────────────
     Cinq énoncés dictés, très courts, la réponse seule sur l'ardoise. On ne
     demande pas le calcul écrit : on demande de comprendre ce qu'on cherche.
     Une addition en novembre, deux étapes en juin. */

  f(
    "cg-problemes-01",
    "Les problèmes en une phrase",
    "Ajouter, retrancher · de petits nombres",
    [
      "Lisez l’énoncé deux fois, lentement, puis laissez le silence. Il écrit la réponse seule, sans le calcul.",
      "S’il demande une troisième lecture, donnez-la : relire n’est pas une aide, c’est la façon normale de lire un problème.",
      "On corrige à la fin des cinq, pas au fur et à mesure. Chacun dit sa réponse et on regarde ensemble.",
    ],
    [
      "Il y a 24 crayons dans la boîte, on en ajoute 13. Combien y en a-t-il ?",
      "Elle a 40 images, elle en donne 15. Combien lui en reste-t-il ?",
      "Dans un sac : 18 billes rouges et 27 billes bleues. Combien de billes en tout ?",
      "Un livre de 60 pages, il en a lu 35. Combien lui reste-t-il à lire ?",
      "Le matin il ramasse 12 noix, l’après-midi 19. Combien en tout ?",
    ],
    ["37 crayons", "25 images", "45 billes", "25 pages", "31 noix"],
    "On regarde s’il peut redire l’histoire sans les nombres : « il y avait des crayons dans la boîte, on en a mis d’autres ». S’il raconte ce qui se passe, l’opération suit d’elle-même. Ce n’est pas le mot qui décide — « en tout » ou « il reste » tromperont plus tard dans l’année —, c’est l’histoire, comme le dit la leçon.",
  ),

  f(
    "cg-problemes-02",
    "Les problèmes en une phrase",
    "Les mêmes questions, des nombres jusqu’au millier",
    [
      "Rien de nouveau sinon la taille des nombres. Il peut poser l’opération sur l’ardoise s’il en a besoin.",
      "Dictez en détachant les centaines : « trois cent vingt… clous ». Les grands nombres se perdent vite à l’oreille.",
      "Cinq énoncés en quinze minutes, ce n’est pas serré : laissez-lui le temps de relire sa réponse avant de la montrer.",
    ],
    [
      "Une boîte contient 320 clous, on en ajoute 150. Combien y en a-t-il ?",
      "Il reste 800 m à parcourir, il en a fait 450. Combien lui reste-t-il ?",
      "Elle a 175 € et 225 € dans deux enveloppes. Combien en tout ?",
      "Un carnet de 500 tickets, 160 sont vendus. Combien en reste-t-il ?",
      "Sur 640 graines semées, 90 n’ont pas poussé. Combien ont poussé ?",
    ],
    ["470 clous", "350 m", "400 €", "340 tickets", "550 graines"],
    "La dernière demande de comprendre que « n’ont pas poussé » se retranche. Si elle passe à côté, reprenez-la en changeant un mot : « 90 sont restées en terre », parfois ça suffit.",
  ),

  f(
    "cg-problemes-03",
    "Les problèmes en une phrase",
    "Des paquets tous pareils · la multiplication",
    [
      "Cinq situations où une même quantité se répète. C’est le terrain naturel de la multiplication.",
      "S’il additionne au lieu de multiplier, laissez-le : 8 + 8 + 8 + 8 + 8 + 8 donne la bonne réponse. Vous lui montrerez le raccourci à la correction.",
      "Demandez-lui à la fin ce que les cinq énoncés avaient en commun. La réponse « c’est toujours des paquets » vaut la séance.",
    ],
    [
      "6 boîtes de 8 œufs. Combien d’œufs ?",
      "7 rangées de 9 chaises. Combien de chaises ?",
      "4 paquets de 25 cartes. Combien de cartes ?",
      "5 sachets de 12 bonbons. Combien de bonbons ?",
      "3 étagères de 40 livres. Combien de livres ?",
    ],
    ["48 œufs", "63 chaises", "100 cartes", "60 bonbons", "120 livres"],
    "Les deux dernières sortent des tables apprises : 5 fois 12 et 3 fois 40. S’il les trouve en découpant (« 5 fois 10, plus 5 fois 2 »), notez-le : ce chemin-là servira longtemps.",
  ),

  f(
    "cg-problemes-04",
    "Les problèmes en une phrase",
    "Partager en parts égales",
    [
      "La division arrive par le partage : on connaît le tout et le nombre de parts, on cherche la valeur d’une part.",
      "Les deux dernières changent de question : on connaît la valeur d’une part et on cherche combien il y en a. C’est la même opération, vue d’ailleurs.",
      "Toutes les divisions tombent juste. S’il propose de vérifier en multipliant, c’est exactement ce qu’il faut faire.",
    ],
    [
      "24 gâteaux répartis dans 4 assiettes, la même quantité dans chacune. Combien par assiette ?",
      "35 billes en 5 tas égaux. Combien par tas ?",
      "48 cartes distribuées à 6 joueurs. Combien chacun ?",
      "60 € partagés entre 4 personnes. Combien chacune ?",
      "72 fleurs à mettre en bouquets de 8. Combien de bouquets ?",
    ],
    ["6 gâteaux", "7 billes", "8 cartes", "15 €", "9 bouquets"],
    "Le cinquième énoncé est d’un autre type que les quatre premiers, même si l’opération est identique. S’il bute dessus seulement, ce n’est pas la division qui manque : c’est de voir qu’ici on cherche le nombre de parts.",
  ),

  f(
    "cg-problemes-05",
    "Les problèmes en une phrase",
    "Ce qui manque pour arriver au compte",
    [
      "On cherche un complément : ce qu’il faut ajouter pour atteindre un total. Le mot « manque » revient dans presque tous.",
      "Deux chemins marchent : soustraire, ou avancer par bonds depuis le petit nombre. Acceptez les deux, et demandez-lui lequel il a pris.",
      "Le dernier énoncé parle d’horaires. Il peut compter sur ses doigts de cinq en cinq, c’est une bonne façon de faire.",
    ],
    [
      "Il a 35 €, il lui en faut 50. Combien lui manque-t-il ?",
      "Un album de 120 images, il en a collé 85. Combien lui en manque-t-il ?",
      "L’étagère porte 200 livres au maximum, il y en a 145. Combien peut-on encore en poser ?",
      "La recette demande 500 g de farine, il y en a 320 dans le bol. Combien en ajouter ?",
      "Le bus part à 9 h, il est 8 h 25. Dans combien de temps part-il ?",
    ],
    ["15 €", "35 images", "55 livres", "180 g", "35 minutes"],
    "Regardez de quel côté il part. Compter en avant depuis 85 jusqu’à 120 et soustraire 85 de 120 donnent le même résultat ; celui qui avance par bonds se trompe moins souvent, et c’est bon à savoir.",
  ),

  f(
    "cg-problemes-06",
    "Les problèmes en une phrase",
    "L’argent · payer, rendre, additionner",
    [
      "Des euros entiers, des situations de tous les jours. S’il a de la vraie monnaie sous la main, sortez-la : c’est plus parlant qu’une ardoise.",
      "Les deux derniers demandent deux étapes : on calcule le total, puis ce qui reste. Prévenez-le avant de dicter.",
      "N’oubliez pas l’unité dans la réponse : on répond « 8 € », pas « 8 ».",
    ],
    [
      "Un cahier 3 €, un stylo 2 €, une gomme 1 €. Combien en tout ?",
      "Il paie 12 € avec un billet de 20 €. Combien lui rend-on ?",
      "4 places de cinéma à 7 € l’une. Combien en tout ?",
      "Elle avait économisé 45 €, elle dépense 18 €. Combien lui reste-t-il ?",
      "Trois livres à 9 € l’un, il donne 30 €. Combien lui rend-on ?",
    ],
    ["6 €", "8 €", "28 €", "27 €", "3 € (27 € de livres)"],
    "Le dernier énoncé est le premier à deux étapes de l’année. S’il donne 27 au lieu de 3, il a fait la première étape et oublié la question : relisez-lui seulement la dernière phrase, il corrigera tout seul.",
  ),

  f(
    "cg-problemes-07",
    "Les problèmes en une phrase",
    "Combien de plus, combien de moins",
    [
      "Cinq comparaisons. On ne cherche pas un total mais un écart, et c’est une idée qui demande à être dite.",
      "Faites-lui reformuler la question avant de calculer : « on cherche de combien le sapin dépasse le pommier ». La reformulation fait la moitié du travail.",
      "Un dessin au trait sur l’ardoise, deux barres l’une sous l’autre, aide beaucoup ici. Proposez-le sans l’imposer.",
    ],
    [
      "Le sapin mesure 12 m, le pommier 7 m. Combien de mètres de plus pour le sapin ?",
      "Une salle de 340 places, 275 sont occupées. Combien de places libres ?",
      "Hier il a marché 18 km, aujourd’hui 25 km. Combien de plus aujourd’hui ?",
      "Un carton pèse 15 kg, un autre 9 kg. Quelle différence ?",
      "Un paquet de 250 g, un autre de 400 g. Combien manque-t-il au premier pour égaler le second ?",
    ],
    ["5 m", "65 places", "7 km", "6 kg", "150 g"],
    "« Combien de plus » et « combien il manque » sont la même soustraction dite dans deux sens. S’il en réussit un type et pas l’autre, c’est la formulation qu’on travaillera, pas le calcul.",
  ),

  f(
    "cg-problemes-08",
    "Les problèmes en une phrase",
    "Deux fois plus, trois fois moins",
    [
      "« Fois plus » multiplie, « fois moins » divise. C’est la seule chose à tenir aujourd’hui, et elle se dit en une phrase.",
      "Attention au piège de l’habitude : « moins » ne veut pas dire soustraire ici. Si la confusion vient, elle est logique, ne la traitez pas comme une étourderie.",
      "Dictez les énoncés en marquant un temps après « fois plus » ou « fois moins » : c’est là que se joue la compréhension.",
    ],
    [
      "Il a 14 billes, son cousin en a deux fois plus. Combien en a le cousin ?",
      "Le premier vélo coûte 45 €, le second trois fois moins. Combien coûte le second ?",
      "Une corde mesure 6 m, une autre est quatre fois plus longue. Combien mesure-t-elle ?",
      "Un paquet pèse 100 g, un autre cinq fois moins. Combien pèse-t-il ?",
      "Un sac de 3 kg, un autre dix fois plus lourd. Combien pèse-t-il ?",
    ],
    ["28 billes", "15 €", "24 m", "20 g", "30 kg"],
    "S’il soustrait sur les « fois moins », ne reprenez pas la division : reprenez la phrase. Faites-lui dire ce que serait « trois fois plus », puis demandez ce que fait le contraire. L’idée revient d’elle-même.",
  ),

  f(
    "cg-problemes-09",
    "Les problèmes en une phrase",
    "Quand il reste quelque chose",
    [
      "Les divisions ne tombent plus juste. Il y a un reste, et il fait partie de la réponse : on attend deux nombres.",
      "Le troisième énoncé est d’un genre à part : le reste oblige à prendre une voiture de plus. Personne ne reste sur le trottoir.",
      "S’il annonce seulement le quotient, redemandez : « et les autres, ils vont où ? ». La question fait apparaître le reste.",
    ],
    [
      "26 œufs à ranger dans des boîtes de 6. Combien de boîtes pleines, et combien d’œufs restent ?",
      "50 billes à mettre dans des sachets de 8. Combien de sachets pleins, et combien reste-t-il ?",
      "30 enfants partent en voiture, 4 places par voiture. Combien de voitures faut-il pour que tous partent ?",
      "100 cartes en paquets de 12. Combien de paquets pleins, et combien reste-t-il ?",
      "45 fleurs en bouquets de 7. Combien de bouquets, et combien reste-t-il ?",
    ],
    [
      "4 boîtes pleines, il reste 2 œufs",
      "6 sachets pleins, il reste 2 billes",
      "8 voitures (7 pleines et une avec 2 enfants)",
      "8 paquets pleins, il reste 4 cartes",
      "6 bouquets, il reste 3 fleurs",
    ],
    "Le troisième énoncé est celui qui compte. Répondre « 7 voitures et il reste 2 enfants » montre que la division est comprise ; c’est la situation qui demande d’arrondir vers le haut, et c’est un pas de plus, pas une confusion.",
  ),

  f(
    "cg-problemes-10",
    "Les problèmes en une phrase",
    "Deux étapes, deux questions",
    [
      "Chaque énoncé demande deux opérations. Dites-le avant de commencer : on cherche d’abord un nombre intermédiaire, puis la réponse.",
      "Autorisez-le à écrire le nombre intermédiaire sur l’ardoise. Tenir deux résultats en tête est ce qu’il y a de plus coûteux ici.",
      "À la correction, demandez-lui de dire les deux étapes à voix haute avant de donner la réponse. C’est l’entraînement du jour.",
    ],
    [
      "3 paquets de 12 gâteaux, il en mange 5. Combien reste-t-il de gâteaux ?",
      "Il a 25 € et achète deux livres à 9 € l’un. Combien lui reste-t-il ?",
      "4 boîtes de 6 œufs, 3 œufs sont cassés. Combien d’œufs intacts ?",
      "Une course de 10 km : il a couru 2 km, puis 3 km. Combien reste-t-il ?",
      "5 rangées de 8 chaises, 6 chaises sont prises. Combien de chaises libres ?",
    ],
    [
      "31 gâteaux (36 − 5)",
      "7 € (25 − 18)",
      "21 œufs (24 − 3)",
      "5 km (10 − 5)",
      "34 chaises (40 − 6)",
    ],
    "Ce qui se joue, c’est de ne pas s’arrêter à la première étape. S’il répond 36 au premier, il a bien calculé et mal terminé : faites-lui relire la question, sans rien reprendre d’autre.",
  ),

  f(
    "cg-problemes-11",
    "Les problèmes en une phrase",
    "Quand tout est proportionnel",
    [
      "La phrase qui résout presque tout : on cherche d’abord ce que vaut une unité, puis on multiplie.",
      "Deux énoncés demandent le passage par un ; deux autres donnent déjà la valeur d’une unité. Le dernier demande de multiplier par trois.",
      "Dites-lui de commencer par se demander : « combien pour un ? ». C’est la question à garder toute l’année.",
    ],
    [
      "Un stylo coûte 3 €. Combien coûtent 7 stylos ?",
      "4 croissants coûtent 8 €. Combien coûte un croissant ?",
      "3 m de tissu coûtent 15 €. Combien coûtent 6 m ?",
      "Une voiture parcourt 90 km en une heure. Combien en 3 heures ?",
      "5 kg de pommes coûtent 10 €. Combien coûtent 15 kg ?",
    ],
    [
      "21 €",
      "2 €",
      "30 € (le double de 3 m, donc le double du prix)",
      "270 km",
      "30 € (trois fois plus de pommes, trois fois le prix)",
    ],
    "Le troisième et le cinquième peuvent se faire sans passer par un, en voyant que c’est le double ou le triple. Si c’est ce chemin qu’il prend, c’est le plus rapide et il l’a trouvé seul : dites-le-lui.",
  ),

  f(
    "cg-problemes-12",
    "Les problèmes en une phrase",
    "Des parts dans un problème",
    [
      "Les fractions reviennent, cette fois dans une histoire. Le travail est de repérer de quelle quantité on prend la part.",
      "Faites-lui dire « le tiers de quoi ? » avant de calculer. C’est la question qui évite presque toutes les impasses.",
      "Le dernier énoncé demande en plus une conversion. S’il donne la réponse en litres, elle est juste aussi : acceptez-la et convertissez ensemble.",
    ],
    [
      "Un gâteau coupé en 8 parts, il en mange 3. Combien de parts reste-t-il ?",
      "Elle a 36 billes et en donne le tiers. Combien en donne-t-elle ?",
      "Un paquet de 200 g, on en verse la moitié dans le bol. Combien de grammes ?",
      "Un trajet de 40 km dont les trois quarts sont faits. Combien de kilomètres faits ?",
      "Une bouteille de 1 L, il en boit le quart. Combien de centilitres ?",
    ],
    ["5 parts", "12 billes", "100 g", "30 km", "25 cL"],
    "Le deuxième énoncé peut se lire de deux façons : ce qu’elle donne, ou ce qui lui reste. Les deux calculs sont utiles ; si c’est le reste qu’il a calculé, la fraction est comprise et c’est la question qu’il faut relire.",
  ),

  f(
    "cg-problemes-13",
    "Les problèmes en une phrase",
    "Euros et centimes",
    [
      "Des prix à virgule, comme sur un ticket de caisse. La virgule sépare les euros des centimes, rien de plus.",
      "S’il préfère travailler en centimes puis reconvertir, c’est une méthode sûre : 1,20 € vaut 120 centimes, et l’addition redevient celle de novembre.",
      "Dernière séance de la série : laissez-le dicter le cinquième énoncé à votre place, si l’envie lui prend d’en inventer un.",
    ],
    [
      "Un pain 1,20 €, un croissant 1,10 €. Combien en tout ?",
      "Il paie 4,50 € avec un billet de 5 €. Combien lui rend-on ?",
      "3 bouteilles à 1,50 € l’une. Combien en tout ?",
      "Deux articles : 2,75 € et 3,25 €. Combien en tout ?",
      "Il a 10 € et achète un article à 2,50 € et un autre à 4 €. Combien lui reste-t-il ?",
    ],
    ["2,30 €", "0,50 €", "4,50 €", "6 €", "3,50 € (6,50 € dépensés)"],
    "La quatrième tombe sur un compte rond, 6 € pile : s’il écrit 6,00 ou 6, les deux se valent. Ce qu’on regarde surtout, c’est s’il aligne les centimes avec les centimes quand il pose l’opération.",
  ),
  /* ── Encadrer et arrondir ──────────────────────────────────────────────
     Encadrer, c'est dire entre quels deux nombres ronds on se trouve ;
     arrondir, c'est choisir le plus proche des deux. On installe l'ordre de
     grandeur, qui servira à se relire tout le reste de l'année. */

  f(
    "cg-encadrer-01",
    "Encadrer et arrondir",
    "Entre deux dizaines",
    [
      "La question est toujours la même : « entre quelles dizaines se trouve ce nombre ? ». Il répond par deux nombres.",
      "Montrez-lui une fois la règle graduée ou une ligne tracée sur l’ardoise : le nombre se pose entre deux repères, et on lit les repères.",
      "La réponse se dit « entre 40 et 50 ». Acceptez aussi qu’il écrive « 40 < 47 < 50 » s’il aime les signes.",
    ],
    [
      "47",
      "83",
      "25",
      "61",
      "99",
      "108",
      "134",
      "276",
      "305",
      "199",
    ],
    [
      "entre 40 et 50",
      "entre 80 et 90",
      "entre 20 et 30",
      "entre 60 et 70",
      "entre 90 et 100",
      "entre 100 et 110",
      "entre 130 et 140",
      "entre 270 et 280",
      "entre 300 et 310",
      "entre 190 et 200",
    ],
    "Les nombres en 9 (99, 199) sont ceux qui font hésiter, parce que la dizaine suivante change aussi de centaine. S’il s’y arrête, c’est là qu’il faut revenir, avec 89, 109, 209.",
  ),

  f(
    "cg-encadrer-02",
    "Encadrer et arrondir",
    "Entre deux centaines",
    [
      "Même question, un cran plus haut : on cherche les centaines qui entourent le nombre.",
      "Le chiffre des centaines donne la réponse de gauche ; celle de droite est la centaine juste après. Laissez-le trouver ce raccourci.",
      "Les quatre dernières questions ont quatre chiffres. Faites-les écrire sur l’ardoise avant de répondre si l’oreille s’y perd.",
    ],
    [
      "340",
      "512",
      "890",
      "105",
      "999",
      "1 250",
      "2 070",
      "3 405",
      "7 890",
      "4 099",
    ],
    [
      "entre 300 et 400",
      "entre 500 et 600",
      "entre 800 et 900",
      "entre 100 et 200",
      "entre 900 et 1 000",
      "entre 1 200 et 1 300",
      "entre 2 000 et 2 100",
      "entre 3 400 et 3 500",
      "entre 7 800 et 7 900",
      "entre 4 000 et 4 100",
    ],
    "Le piège discret est 2 070 : la centaine d’en dessous s’écrit 2 000, sans rien entre les deux. Si ce zéro le gêne, c’est la valeur des positions qu’on reprendra, pas l’encadrement.",
  ),

  f(
    "cg-encadrer-03",
    "Encadrer et arrondir",
    "Entre deux milliers",
    [
      "Troisième cran : les milliers. Le chiffre de gauche donne le repère du bas, le suivant celui du haut.",
      "Dictez en groupant : « six mille quatre cent quatre-vingts ». La façon de dire le nombre porte déjà la réponse.",
      "Dix questions du même type, c’est voulu : on cherche l’automatisme, pas la variété.",
    ],
    [
      "6 480",
      "1 200",
      "3 999",
      "8 050",
      "2 500",
      "9 001",
      "4 760",
      "7 300",
      "5 555",
      "9 990",
    ],
    [
      "entre 6 000 et 7 000",
      "entre 1 000 et 2 000",
      "entre 3 000 et 4 000",
      "entre 8 000 et 9 000",
      "entre 2 000 et 3 000",
      "entre 9 000 et 10 000",
      "entre 4 000 et 5 000",
      "entre 7 000 et 8 000",
      "entre 5 000 et 6 000",
      "entre 9 000 et 10 000",
    ],
    "Les deux questions à 9 000 mènent à 10 000, un nombre à cinq chiffres qu’il n’a peut-être pas encore écrit. S’il hésite à l’écrire, dictez-le-lui : ce n’est pas l’objet du jour.",
  ),

  f(
    "cg-encadrer-04",
    "Encadrer et arrondir",
    "Arrondir · choisir le plus proche",
    [
      "Nouveau mot : arrondir, c’est encadrer puis garder celui des deux repères dont on est le plus près.",
      "La règle du milieu se dit une fois : quand on est pile au milieu, on prend celui du haut. C’est une convention, pas une vérité ; dites-le comme ça.",
      "Précisez à chaque fois le cran demandé : « à la dizaine », « à la centaine ». C’est la moitié de la question.",
    ],
    [
      "Arrondir 47 à la dizaine",
      "Arrondir 43 à la dizaine",
      "Arrondir 65 à la dizaine",
      "Arrondir 128 à la dizaine",
      "Arrondir 342 à la centaine",
      "Arrondir 380 à la centaine",
      "Arrondir 250 à la centaine",
      "Arrondir 1 460 à la centaine",
      "Arrondir 2 049 à la centaine",
      "Arrondir 7 951 à la centaine",
    ],
    ["50", "40", "70", "130", "300", "400", "300", "1 500", "2 000", "8 000"],
    "Le 65 et le 250 tombent pile au milieu : c’est la convention qui décide, pas le raisonnement. S’il les laisse passer tous les deux, c’est que la convention n’est pas encore retenue, et elle se redit en une phrase.",
  ),

  f(
    "cg-encadrer-05",
    "Encadrer et arrondir",
    "Arrondir au millier",
    [
      "Un seul cran aujourd’hui, le millier. La question ne change pas d’une fois sur l’autre.",
      "Le chiffre à regarder est celui des centaines : en dessous de 5 on descend, à partir de 5 on monte. Faites-le dire avant chaque réponse.",
      "Les deux dernières font monter jusqu’au millier supérieur d’un coup : 9 640 devient 10 000. Prévenez que ça arrive.",
    ],
    [
      "Arrondir 6 480 au millier",
      "Arrondir 3 500 au millier",
      "Arrondir 2 199 au millier",
      "Arrondir 8 900 au millier",
      "Arrondir 4 499 au millier",
      "Arrondir 7 500 au millier",
      "Arrondir 1 050 au millier",
      "Arrondir 9 640 au millier",
      "Arrondir 5 400 au millier",
      "Arrondir 2 750 au millier",
    ],
    [
      "6 000",
      "4 000",
      "2 000",
      "9 000",
      "4 000",
      "8 000",
      "1 000",
      "10 000",
      "5 000",
      "3 000",
    ],
    "Le 4 499 est le seul qui puisse tromper : les deux 9 qui suivent donnent envie de monter. Si c’est arrivé, faites-lui souligner le chiffre des centaines ; il verra que c’est un 4, et que le reste ne compte pas.",
  ),

  f(
    "cg-encadrer-06",
    "Encadrer et arrondir",
    "Encadrer les grands nombres",
    [
      "Les nombres passent à six chiffres. Écrivez-les sur l’ardoise avant de demander l’encadrement : on les lit par paquets de trois.",
      "Un même nombre revient à deux crans différents — au millier, puis à la dizaine de mille. Faire les deux de suite éclaire ce que « cran » veut dire.",
      "Si les grands nombres l’intimident, commencez par lui faire lire le nombre à voix haute. Le lire, c’est déjà le dominer.",
    ],
    [
      "Entre quels milliers se trouve 45 380 ?",
      "Entre quelles dizaines de mille se trouve 45 380 ?",
      "Entre quels milliers se trouve 128 700 ?",
      "Entre quelles centaines de mille se trouve 128 700 ?",
      "Entre quels milliers se trouve 9 850 ?",
      "Entre quelles dizaines de mille se trouve 87 200 ?",
      "Entre quels milliers se trouve 300 050 ?",
      "Entre quelles centaines de mille se trouve 750 000 ?",
      "Entre quels milliers se trouve 56 001 ?",
      "Entre quelles dizaines de mille se trouve 234 500 ?",
    ],
    [
      "entre 45 000 et 46 000",
      "entre 40 000 et 50 000",
      "entre 128 000 et 129 000",
      "entre 100 000 et 200 000",
      "entre 9 000 et 10 000",
      "entre 80 000 et 90 000",
      "entre 300 000 et 301 000",
      "entre 700 000 et 800 000",
      "entre 56 000 et 57 000",
      "entre 230 000 et 240 000",
    ],
    "Ce qu’on regarde, c’est s’il repère la position à couper plutôt qu’il ne devine. Un doigt posé sous le chiffre des milliers, et la réponse tombe : ce geste-là vaut d’être encouragé.",
  ),

  f(
    "cg-encadrer-07",
    "Encadrer et arrondir",
    "Arrondir les grands nombres",
    [
      "Même terrain que la fois précédente, mais on choisit maintenant le plus proche des deux repères.",
      "Deux nombres reviennent à deux crans différents : 45 380 et 128 700. Le même nombre donne deux arrondis, et c’est normal.",
      "S’il demande lequel est « le bon », la réponse est : celui qu’on a demandé. L’arrondi dépend du cran, il n’y en a pas un plus vrai que l’autre.",
    ],
    [
      "Arrondir 45 380 au millier",
      "Arrondir 45 380 à la dizaine de mille",
      "Arrondir 128 700 au millier",
      "Arrondir 128 700 à la centaine de mille",
      "Arrondir 87 500 au millier",
      "Arrondir 9 850 au millier",
      "Arrondir 234 900 à la dizaine de mille",
      "Arrondir 76 200 à la dizaine de mille",
      "Arrondir 505 000 à la centaine de mille",
      "Arrondir 649 000 à la centaine de mille",
    ],
    [
      "45 000",
      "50 000",
      "129 000",
      "100 000",
      "88 000",
      "10 000",
      "230 000",
      "80 000",
      "500 000",
      "600 000",
    ],
    "L’idée à guetter est qu’un même nombre ait deux arrondis justes. Si elle passe, les ordres de grandeur sont en place ; sinon, refaites seulement les deux premières questions la prochaine fois, et rien d’autre.",
  ),

  f(
    "cg-encadrer-08",
    "Encadrer et arrondir",
    "Les nombres à virgule, entre deux entiers",
    [
      "La virgule entre en scène. La question reste : entre quels deux entiers se trouve ce nombre ?",
      "La réponse est la partie entière, et l’entier juste après. Faites-le dire ainsi une fois, puis laissez-le faire.",
      "Dictez la virgule à voix haute : « trois virgule sept ». Ne dites jamais « trois sept », c’est un autre nombre.",
    ],
    [
      "3,7",
      "12,94",
      "0,8",
      "25,05",
      "9,99",
      "7,5",
      "100,4",
      "6,02",
      "14,6",
      "2,25",
    ],
    [
      "entre 3 et 4",
      "entre 12 et 13",
      "entre 0 et 1",
      "entre 25 et 26",
      "entre 9 et 10",
      "entre 7 et 8",
      "entre 100 et 101",
      "entre 6 et 7",
      "entre 14 et 15",
      "entre 2 et 3",
    ],
    "Le 9,99 est celui qui trouble : deux 9 après la virgule donnent l’impression d’avoir dépassé 10. S’il répond « entre 10 et 11 », c’est une bonne intuition mal placée, et la droite graduée la remet d’aplomb.",
  ),

  f(
    "cg-encadrer-09",
    "Encadrer et arrondir",
    "Arrondir un nombre à virgule à l’unité",
    [
      "Après l’encadrement vient le choix : on garde l’entier le plus proche. C’est exactement ce qu’il faisait avec les dizaines.",
      "Le chiffre à regarder est celui juste après la virgule : moins de 5 on descend, 5 ou plus on monte. Le reste ne compte pas.",
      "Reprenez les mêmes nombres qu’à la séance précédente autant que possible : la comparaison entre les deux séances fait le travail.",
    ],
    [
      "Arrondir 3,7 à l’unité",
      "Arrondir 12,94 à l’unité",
      "Arrondir 8,2 à l’unité",
      "Arrondir 0,6 à l’unité",
      "Arrondir 25,05 à l’unité",
      "Arrondir 7,5 à l’unité",
      "Arrondir 14,49 à l’unité",
      "Arrondir 99,8 à l’unité",
      "Arrondir 2,25 à l’unité",
      "Arrondir 10,5 à l’unité",
    ],
    ["4", "13", "8", "1", "25", "8", "14", "100", "2", "11"],
    "Le 14,49 est le nœud : le 9 attire l’œil alors que c’est le 4 qui décide. Si la réponse est 15, faites-lui cacher tout ce qui suit le premier chiffre après la virgule ; la difficulté disparaît d’un coup.",
  ),

  f(
    "cg-encadrer-10",
    "Encadrer et arrondir",
    "Au dixième près",
    [
      "On descend d’un cran sous l’unité : les dixièmes. On encadre puis on arrondit, comme d’habitude.",
      "Dites une fois que 13 s’écrit aussi 13,0 : c’est ce qui permet d’encadrer 12,94 entre 12,9 et 13.",
      "Les questions alternent encadrement et arrondi. Annoncez laquelle des deux vous posez, à chaque fois.",
    ],
    [
      "Entre quels dixièmes se trouve 3,74 ?",
      "Entre quels dixièmes se trouve 12,94 ?",
      "Arrondir 3,74 au dixième",
      "Arrondir 12,94 au dixième",
      "Arrondir 0,58 au dixième",
      "Entre quels dixièmes se trouve 9,95 ?",
      "Arrondir 7,25 au dixième",
      "Arrondir 14,02 au dixième",
      "Entre quels dixièmes se trouve 0,07 ?",
      "Arrondir 5,96 au dixième",
    ],
    [
      "entre 3,7 et 3,8",
      "entre 12,9 et 13",
      "3,7",
      "12,9",
      "0,6",
      "entre 9,9 et 10",
      "7,3",
      "14",
      "entre 0 et 0,1",
      "6",
    ],
    "Les réponses qui perdent la virgule (14 pour 14,02, 6 pour 5,96) surprennent souvent : on s’attend à un nombre à virgule quand on arrondit au dixième. C’est une bonne occasion de dire que 14 et 14,0 sont le même nombre.",
  ),

  f(
    "cg-encadrer-11",
    "Encadrer et arrondir",
    "Encadrer une fraction",
    [
      "Les fractions se posent sur la même droite que les nombres à virgule. La question ne change pas : entre quels entiers ?",
      "Dictez à voix haute et écrivez sur l’ardoise : « sept demis », et vous écrivez 7/2. L’oreille et l’œil ensemble.",
      "Le chemin : combien de fois le nombre du bas tient-il dans celui du haut ? Deux fois dans 7 pour les demis, et il reste quelque chose, donc entre 3 et 4.",
    ],
    [
      "7/2 (sept demis)",
      "5/4 (cinq quarts)",
      "10/3 (dix tiers)",
      "11/4 (onze quarts)",
      "7/5 (sept cinquièmes)",
      "13/2 (treize demis)",
      "8/3 (huit tiers)",
      "17/5 (dix-sept cinquièmes)",
      "9/4 (neuf quarts)",
      "23/10 (vingt-trois dixièmes)",
    ],
    [
      "entre 3 et 4",
      "entre 1 et 2",
      "entre 3 et 4",
      "entre 2 et 3",
      "entre 1 et 2",
      "entre 6 et 7",
      "entre 2 et 3",
      "entre 3 et 4",
      "entre 2 et 3",
      "entre 2 et 3",
    ],
    "Ce qu’on regarde, c’est s’il passe par la division plutôt que par un souvenir. Dire « 4 tient deux fois dans 9, il reste 1 » puis conclure « entre 2 et 3 », c’est la méthode entière ; si elle est là, les fractions cessent d’être un objet à part.",
  ),

  f(
    "cg-encadrer-12",
    "Encadrer et arrondir",
    "L’ordre de grandeur d’un calcul",
    [
      "On ne cherche plus le résultat exact mais l’à-peu-près : on arrondit chaque nombre, puis on calcule de tête.",
      "Interdisez-vous de poser l’opération, tous les deux. C’est le jeu du jour, et il tient en dix secondes par question.",
      "Le corrigé donne l’estimation attendue et, entre parenthèses, le résultat exact. Montrez-lui l’écart : c’est ce qui rend l’estimation utile.",
    ],
    [
      "2 980 + 4 100, environ combien ?",
      "5 120 − 1 890, environ combien ?",
      "19 × 21, environ combien ?",
      "98 + 203, environ combien ?",
      "4,9 + 3,1, environ combien ?",
      "312 × 3, environ combien ?",
      "1 010 + 2 990, environ combien ?",
      "49 × 11, environ combien ?",
      "7 850 − 3 900, environ combien ?",
      "612 + 397, environ combien ?",
    ],
    [
      "environ 7 000 (exactement 7 080)",
      "environ 3 000 (exactement 3 230)",
      "environ 400 (exactement 399)",
      "environ 300 (exactement 301)",
      "environ 8 (exactement 8)",
      "environ 900 (exactement 936)",
      "environ 4 000 (exactement 4 000)",
      "environ 500 (exactement 539)",
      "environ 4 000 (exactement 3 950)",
      "environ 1 000 (exactement 1 009)",
    ],
    "L’enjeu n’est pas la précision mais l’audace : accepter de répondre « environ ». S’il refuse d’estimer et veut le résultat juste, c’est un signe d’exigence envers lui-même ; répétez-lui que la bonne réponse, aujourd’hui, est une réponse approchée.",
  ),

  f(
    "cg-encadrer-13",
    "Encadrer et arrondir",
    "Arrondir pour de vrai",
    [
      "Dernière séance de la série : des arrondis comme on en fait dans une journée, sur des prix, des masses, des distances.",
      "Chaque question dit le cran demandé. Laissez-le répondre avec l’unité : « 13 € », « 2 kg ».",
      "À la fin, demandez-lui à quoi ça sert d’arrondir. Toute réponse qui parle de « voir vite » ou de « vérifier » est la bonne.",
    ],
    [
      "Un prix de 12,94 €, arrondi à l’euro",
      "Une masse de 2 480 g, arrondie au kilogramme",
      "Une distance de 6 480 m, arrondie au kilomètre",
      "Un prix de 3,49 €, arrondi à l’euro",
      "Une durée de 1 h 52, arrondie à l’heure",
      "Une masse de 750 g, arrondie au kilogramme",
      "Une taille de 1,47 m, arrondie au dixième de mètre",
      "Un trajet de 348 km, arrondi à la centaine de kilomètres",
      "Une contenance de 1,8 L, arrondie au litre",
      "Une température de 27,5 °C, arrondie au degré",
    ],
    [
      "13 €",
      "2 kg",
      "6 km",
      "3 €",
      "2 h",
      "1 kg",
      "1,5 m",
      "300 km",
      "2 L",
      "28 °C",
    ],
    "La durée est la seule qui ne se compte pas en dix : 1 h 52 est près de 2 h parce que l’heure fait 60 minutes. S’il répond 1 h, c’est la règle des décimaux qu’il a appliquée là où elle ne vaut pas, et ça se comprend ; la séance sur les durées fera le reste.",
  ),
  /* ── Les unités de mesure ──────────────────────────────────────────────
     Longueurs, masses, contenances. Une seule chose à retenir toute l'année :
     d'une unité à sa voisine, on multiplie ou on divise par 10, par 100, par
     1 000. Le reste se déduit, et on le déduit à voix haute. */

  f(
    "cg-unites-01",
    "Les unités de mesure",
    "Des mètres et des centimètres",
    [
      "Une seule équivalence à poser au départ : 1 mètre vaut 100 centimètres, 1 centimètre vaut 10 millimètres. Écrivez-la sur l’ardoise et laissez-la visible.",
      "Les quatrième, cinquième et dixième questions mélangent deux unités — 1 m 50 veut dire un mètre et 50 centimètres. Dites-le avant.",
      "Le nombre seul suffit, comme à l’écran : « 150 » est une réponse juste. La phrase complète, avec l’unité, se dit à l’oral — « dans 1 m 50, il y a 150 centimètres ».",
    ],
    [
      "Combien de centimètres dans 1 m ?",
      "Dans 2 m ?",
      "Dans 3 m ?",
      "Dans 1 m 50 ?",
      "Dans 2 m 20 ?",
      "Combien de millimètres dans 1 cm ?",
      "Dans 5 cm ?",
      "Dans 12 cm ?",
      "Combien de centimètres dans 4 m ?",
      "Dans 3 m 50 ?",
    ],
    [
      "100 cm",
      "200 cm",
      "300 cm",
      "150 cm",
      "220 cm",
      "10 mm",
      "50 mm",
      "120 mm",
      "400 cm",
      "350 cm",
    ],
    "Ce qu’on regarde, c’est s’il ajoute les centimètres au bon endroit dans 1 m 50. Répondre 105 au lieu de 150 n’est pas une faute de calcul : c’est l’écriture mixte qui n’est pas encore lue. La règle graduée la montre en dix secondes.",
  ),

  f(
    "cg-unites-02",
    "Les unités de mesure",
    "Les kilomètres",
    [
      "Une équivalence de plus : 1 kilomètre vaut 1 000 mètres. C’est la seule nouveauté de la séance.",
      "Deux questions parlent de demi-kilomètre et de quart de kilomètre : les fractions rencontrent les mesures, et c’est voulu.",
      "S’il cherche, ramenez-le à ce qu’il connaît : « un demi-kilomètre, c’est la moitié de 1 000 m ».",
    ],
    [
      "Combien de mètres dans 1 km ?",
      "Dans 2 km ?",
      "Dans 1 km 500 ?",
      "Dans 3 km ?",
      "Dans 2 km 250 ?",
      "Dans un demi-kilomètre ?",
      "Dans 1 km 750 ?",
      "Dans 4 km ?",
      "Dans un quart de kilomètre ?",
      "Dans 5 km ?",
    ],
    [
      "1 000 m",
      "2 000 m",
      "1 500 m",
      "3 000 m",
      "2 250 m",
      "500 m",
      "1 750 m",
      "4 000 m",
      "250 m",
      "5 000 m",
    ],
    "Le quart de kilomètre est le plus exigeant des dix : il demande de couper 1 000 en quatre. S’il y arrive, les fractions et les mesures se sont rejointes, et ça ne va plus se défaire.",
  ),

  f(
    "cg-unites-03",
    "Les unités de mesure",
    "Les masses",
    [
      "Même structure que les kilomètres, autre grandeur : 1 kilogramme vaut 1 000 grammes. Le 1 000 revient, faites-le remarquer.",
      "Si vous avez une balance de cuisine, posez-y un paquet et faites lire l’affichage. Une mesure vue vaut une conversion apprise.",
      "Les demis et les quarts reviennent : 500 g et 250 g sont des repères qu’il croisera toute sa vie.",
    ],
    [
      "Combien de grammes dans 1 kg ?",
      "Dans 2 kg ?",
      "Dans 2 kg 500 ?",
      "Dans un demi-kilogramme ?",
      "Dans 1 kg 250 ?",
      "Dans un quart de kilogramme ?",
      "Dans 3 kg ?",
      "Dans 1 kg 800 ?",
      "Dans 4 kg ?",
      "Dans 2 kg 750 ?",
    ],
    [
      "1 000 g",
      "2 000 g",
      "2 500 g",
      "500 g",
      "1 250 g",
      "250 g",
      "3 000 g",
      "1 800 g",
      "4 000 g",
      "2 750 g",
    ],
    "Si les mètres de la fois précédente et les kilogrammes d’aujourd’hui se mélangent (100 d’un côté, 1 000 de l’autre), séparez-les nettement : faites deux colonnes sur l’ardoise et laissez-les l’une à côté de l’autre pendant la séance.",
  ),

  f(
    "cg-unites-04",
    "Les unités de mesure",
    "Les contenances",
    [
      "Trois équivalences : 1 litre vaut 100 centilitres et 1 000 millilitres, et 1 centilitre vaut 10 millilitres.",
      "Une brique de jus, une bouteille d’eau, un verre doseur : si quelque chose traîne dans la cuisine, lisez les étiquettes ensemble avant de commencer.",
      "Le litre se comporte comme le mètre pour les centilitres, et comme le kilogramme pour les millilitres. Dites-le, ça range les choses.",
    ],
    [
      "Combien de centilitres dans 1 L ?",
      "Dans 2 L ?",
      "Dans un demi-litre ?",
      "Dans un quart de litre ?",
      "Combien de millilitres dans 1 L ?",
      "Combien de millilitres dans un litre et demi ?",
      "Combien de millilitres dans 1 cL ?",
      "Combien de millilitres dans 25 cL ?",
      "Combien de centilitres dans 3 L ?",
      "Combien de centilitres dans 1 L et 75 cL ?",
    ],
    [
      "100 cL",
      "200 cL",
      "50 cL",
      "25 cL",
      "1 000 mL",
      "1 500 mL",
      "10 mL",
      "250 mL",
      "300 cL",
      "175 cL",
    ],
    "La huitième question demande deux pas d’un coup : des centilitres vers les millilitres. S’il la laisse passer alors que les autres sont venues, c’est le chaînage qui manque, pas les équivalences ; on le reprendra à la séance sur les contenances complètes.",
  ),

  f(
    "cg-unites-05",
    "Les unités de mesure",
    "Toutes les longueurs, dans les deux sens",
    [
      "On monte et on descend l’échelle des longueurs : mm, cm, m, km. Certaines questions convertissent vers le petit, d’autres vers le grand.",
      "La question à se poser avant de calculer : est-ce que la réponse sera un nombre plus grand ou plus petit ? Faites-la dire à chaque fois.",
      "Une réponse en écriture mixte (2 m 50, 4 cm 5 mm) est une bonne réponse. Elle se dit comme on parle.",
    ],
    [
      "5 m en millimètres",
      "250 cm en mètres",
      "1 500 m en kilomètres",
      "3 200 m en kilomètres",
      "45 mm en centimètres",
      "7 m 5 cm en centimètres",
      "2 km 50 m en mètres",
      "80 cm en millimètres",
      "3 500 m en kilomètres",
      "120 mm en centimètres",
    ],
    [
      "5 000 mm",
      "2 m 50",
      "1 km 500",
      "3 km 200",
      "4 cm 5 mm",
      "705 cm",
      "2 050 m",
      "800 mm",
      "3 km 500",
      "12 cm",
    ],
    "Les deux questions à zéro intercalé — 7 m 5 cm et 2 km 50 m — sont celles qui demandent le plus d’attention. Répondre 75 cm au lieu de 705 est très fréquent ; écrire le nombre dans un tableau de conversion règle la question mieux qu’une explication.",
  ),

  f(
    "cg-unites-06",
    "Les unités de mesure",
    "Les grandes masses · la tonne",
    [
      "Une unité de plus : la tonne, qui vaut 1 000 kilogrammes. C’est la masse d’une petite voiture, dites-le pour ancrer l’ordre de grandeur.",
      "Cinq questions vont du grand vers le petit, cinq du petit vers le grand. Le va-et-vient est l’objet de la séance.",
      "La septième n’est pas une conversion mais un complément : combien manque-t-il à 750 g pour faire 1 kg. Prévenez qu’elle est d’un autre genre.",
    ],
    [
      "Combien de kilogrammes dans 1 t ?",
      "Dans 2 t ?",
      "Dans une demi-tonne ?",
      "3 500 g en kilogrammes",
      "1 200 g en kilogrammes",
      "4 t 500 en kilogrammes",
      "Il y a 750 g dans le sac : combien pour atteindre 1 kg ?",
      "2 500 kg en tonnes",
      "5 kg 50 g en grammes",
      "10 t en kilogrammes",
    ],
    [
      "1 000 kg",
      "2 000 kg",
      "500 kg",
      "3 kg 500",
      "1 kg 200",
      "4 500 kg",
      "250 g",
      "2 t 500",
      "5 050 g",
      "10 000 kg",
    ],
    "Le 5 kg 50 g est le plus retors : la réponse est 5 050 et non 5 500. S’il se trompe, ne corrigez pas le nombre : faites-lui poser 5 kg d’un côté, 50 g de l’autre, et additionner. Il trouvera l’erreur lui-même.",
  ),

  f(
    "cg-unites-07",
    "Les unités de mesure",
    "Toutes les contenances",
    [
      "L’échelle complète : litre, décilitre, centilitre, millilitre. Chaque marche vaut dix fois la suivante.",
      "Le décilitre est le moins familier. Posez-le une fois : un décilitre, c’est un dixième de litre, donc 10 centilitres.",
      "Deux questions attendent une écriture mixte ou une fraction : « un demi-litre » et « 1 L 25 cL » sont des réponses parfaitement dites.",
    ],
    [
      "1 L en décilitres",
      "1 dL en centilitres",
      "2 L 5 dL en centilitres",
      "750 mL en centilitres",
      "3 000 mL en litres",
      "1 L 250 mL en millilitres",
      "50 cL en litres",
      "20 dL en litres",
      "125 cL en litres",
      "6 dL en millilitres",
    ],
    [
      "10 dL",
      "10 cL",
      "250 cL",
      "75 cL",
      "3 L",
      "1 250 mL",
      "un demi-litre (0,5 L)",
      "2 L",
      "1 L 25 cL",
      "600 mL",
    ],
    "La troisième demande deux marches d’un coup, des décilitres aux centilitres en passant par le litre. S’il la construit à voix haute (« 2 L font 200 cL, 5 dL font 50 cL, donc 250 »), le chaînage est acquis et le reste suivra.",
  ),

  f(
    "cg-unites-08",
    "Les unités de mesure",
    "Du petit vers le grand",
    [
      "Aujourd’hui on ne fait qu’un sens : on part de la petite unité et on remonte. C’est celui qui demande de diviser, et le plus coûteux des deux.",
      "Le repère utile : si on remonte, le nombre devient plus petit. Une réponse plus grande que la question est un signal, et il peut le voir seul.",
      "L’écriture mixte est la réponse attendue presque partout : 3 500 g font 3 kg 500, et pas autre chose.",
    ],
    [
      "3 500 g en kilogrammes",
      "250 cm en mètres",
      "4 500 m en kilomètres",
      "175 cL en litres",
      "2 400 mL en litres",
      "90 mm en centimètres",
      "8 000 kg en tonnes",
      "1 050 g en kilogrammes",
      "6 200 m en kilomètres",
      "500 mL en litres",
    ],
    [
      "3 kg 500",
      "2 m 50",
      "4 km 500",
      "1 L 75 cL",
      "2 L 400 mL",
      "9 cm",
      "8 t",
      "1 kg 50 g",
      "6 km 200",
      "un demi-litre (0,5 L)",
    ],
    "Le 1 050 g est le point sensible : il donne 1 kg 50 g, avec un zéro qui compte. Si la réponse est 1 kg 500, c’est le rang du 5 qui a été mal lu ; faites-lui écrire 1 050 et souligner les trois derniers chiffres.",
  ),

  f(
    "cg-unites-09",
    "Les unités de mesure",
    "L’écriture à virgule",
    [
      "Les mesures s’écrivent aussi avec une virgule : 2 kg 500 s’écrit 2,5 kg, et c’est le même nombre.",
      "Le pont à poser une fois : la virgule sépare les unités entières de ce qui reste. 2,5 kg, c’est 2 kilos entiers et un demi.",
      "Les cinq premières questions traduisent dans un sens, les cinq suivantes dans l’autre. Annoncez le passage à mi-parcours.",
    ],
    [
      "2 kg 500 en écriture à virgule",
      "1 m 50 en écriture à virgule",
      "3 km 200 en écriture à virgule",
      "0,5 L en centilitres",
      "2,5 kg en grammes",
      "1,75 m en centimètres",
      "4,2 km en mètres",
      "750 g en kilogrammes, avec une virgule",
      "1,25 L en millilitres",
      "6 cm 5 mm en centimètres, avec une virgule",
    ],
    [
      "2,5 kg",
      "1,5 m",
      "3,2 km",
      "50 cL",
      "2 500 g",
      "175 cm",
      "4 200 m",
      "0,75 kg",
      "1 250 mL",
      "6,5 cm",
    ],
    "Le 750 g qui devient 0,75 kg est la question la plus riche de la séance : elle demande d’accepter un zéro devant la virgule. S’il l’écrit sans hésiter, les décimaux et les mesures se sont rejoints.",
  ),

  f(
    "cg-unites-10",
    "Les unités de mesure",
    "Choisir l’unité, et estimer",
    [
      "Aujourd’hui on ne convertit pas : on choisit l’unité qui convient, et on donne un ordre de grandeur.",
      "Il n’y a pas de réponse unique au chiffre près. Le corrigé donne une estimation raisonnable ; toute réponse du même ordre est bonne.",
      "Si une estimation part très loin, ne la corrigez pas d’emblée : cherchez un objet à mesurer dans la pièce et comparez. L’objet tranche mieux que vous.",
    ],
    [
      "La longueur d’un crayon : quelle unité, et combien environ ?",
      "La distance entre deux villes : quelle unité ?",
      "La masse d’une pomme : quelle unité, et combien environ ?",
      "La masse d’une voiture : quelle unité, et combien environ ?",
      "L’épaisseur d’une pièce de monnaie : quelle unité, et combien environ ?",
      "La contenance d’une cuillère : quelle unité, et combien environ ?",
      "La contenance d’une baignoire : quelle unité, et combien environ ?",
      "La hauteur d’une porte : quelle unité, et combien environ ?",
      "La masse d’un camion : quelle unité, et combien environ ?",
      "La contenance d’une canette : quelle unité, et combien ?",
    ],
    [
      "en centimètres, environ 17 cm",
      "en kilomètres",
      "en grammes, environ 150 g",
      "en kilogrammes, environ 1 200 kg",
      "en millimètres, environ 2 mm",
      "en millilitres, environ 5 mL",
      "en litres, environ 150 L",
      "en mètres, environ 2 m",
      "en tonnes, environ 10 t",
      "en centilitres, 33 cL",
    ],
    "Cette séance ne se corrige pas comme les autres : il n’y a rien à rater. Ce qu’on regarde, c’est s’il a des repères dans le corps — un mètre, c’est à peu près la hauteur de sa poignée de porte — ou s’il devine au hasard. Dans le second cas, mesurez trois objets ensemble cette semaine.",
  ),

  f(
    "cg-unites-11",
    "Les unités de mesure",
    "Additionner et retrancher des mesures",
    [
      "On calcule avec des mesures. La règle unique : on n’additionne que ce qui porte la même unité, donc on convertit d’abord.",
      "Deux questions parlent de périmètre : on additionne les côtés. Le carré en a quatre égaux, le rectangle deux fois deux.",
      "Les deux dernières demandent de retrancher en franchissant une unité : 2 L moins 350 mL, 5 m moins 1 m 25. Ce sont les plus exigeantes, elles arrivent à la fin.",
    ],
    [
      "1 m 50 + 2 m 30",
      "750 g + 250 g",
      "1 L 500 mL + 750 mL",
      "2 km 400 + 1 km 800",
      "Le périmètre d’un carré de 12 cm de côté",
      "Le périmètre d’un rectangle de 15 cm sur 8 cm",
      "3 kg 200 + 1 kg 950",
      "45 cm + 65 cm",
      "2 L − 350 mL",
      "5 m − 1 m 25",
    ],
    [
      "3 m 80",
      "1 kg",
      "2 L 250 mL",
      "4 km 200",
      "48 cm",
      "46 cm",
      "5 kg 150",
      "1 m 10",
      "1 L 650 mL",
      "3 m 75",
    ],
    "La septième est celle où la retenue change d’unité : 200 + 950 font 1 150, donc un kilo de plus et 150 g. S’il répond 4 kg 1150, le calcul est juste et l’écriture ne l’est pas ; c’est une correction d’écriture, pas de raisonnement, et ça vaut la peine de le lui dire.",
  ),

  f(
    "cg-unites-12",
    "Les unités de mesure",
    "Tout mêlé, virgule comprise",
    [
      "Les trois grandeurs, les deux sens, l’écriture à virgule et l’écriture mixte. Rien de nouveau, tout ensemble.",
      "Laissez-le choisir sa forme de réponse quand les deux existent : 1,25 km ou 1 km 250 disent la même chose.",
      "S’il veut un tableau de conversion sous les yeux, donnez-le-lui. Un outil qu’on sait utiliser n’est pas une béquille.",
    ],
    [
      "0,75 kg en grammes",
      "1 250 m en kilomètres, avec une virgule",
      "3,5 L en centilitres",
      "2 t 250 kg en kilogrammes",
      "8 cm 4 mm en millimètres",
      "12 000 m en kilomètres",
      "0,4 m en centimètres",
      "60 cL en litres, avec une virgule",
      "1 500 kg en tonnes, avec une virgule",
      "2,05 m en centimètres",
    ],
    [
      "750 g",
      "1,25 km",
      "350 cL",
      "2 250 kg",
      "84 mm",
      "12 km",
      "40 cm",
      "0,6 L",
      "1,5 t",
      "205 cm",
    ],
    "Le 2,05 m est le dernier piège de la série : deux chiffres après la virgule, donc des centimètres, donc 205 et non 250. S’il le franchit, l’écriture décimale des mesures est en place ; s’il trébuche, c’est le seul point à reprendre.",
  ),

  f(
    "cg-unites-13",
    "Les unités de mesure",
    "Des mesures dans la vie",
    [
      "Dernière séance : chaque question est une petite situation, et la conversion y est cachée quelque part.",
      "Deux étapes presque partout : on calcule, puis on convertit. Ou l’inverse, et ça marche aussi.",
      "Si une question se joue dans la cuisine ou la salle de bains, allez-y. Une réponse vérifiée sur l’objet vaut dix corrections.",
    ],
    [
      "Une bouteille de 1,5 L, on sert trois verres de 20 cL. Combien reste-t-il, en centilitres ?",
      "Un sac de 5 kg, on en prend 750 g. Combien reste-t-il ?",
      "Il parcourt quatre fois 400 m. Combien en kilomètres ?",
      "Une planche de 2 m, on coupe 45 cm. Combien reste-t-il ?",
      "Six briques de 25 cL. Combien en litres ?",
      "Trois paquets de 250 g. Combien en tout ?",
      "Une piscine de 25 m, il fait dix longueurs. Combien en kilomètres ?",
      "Un pot de 500 g, quatre pots. Combien en kilogrammes ?",
      "Un ruban de 1 m 20 coupé en 4 morceaux égaux. Combien mesure chaque morceau ?",
      "2 L de jus servis dans des verres de 25 cL. Combien de verres ?",
    ],
    [
      "90 cL (150 − 60)",
      "4 kg 250",
      "1,6 km (1 600 m)",
      "1 m 55",
      "1,5 L (150 cL)",
      "750 g",
      "0,25 km (250 m)",
      "2 kg",
      "30 cm",
      "8 verres",
    ],
    "Après treize séances, le signe que la série a porté est celui-ci : il convertit avant de calculer, sans qu’on le lui demande. Si les conversions arrivent encore après coup, le résultat est le même et tout va bien ; c’est seulement le geste qu’on installera l’an prochain.",
  ),
  /* ── Les durées ────────────────────────────────────────────────────────
     La consigne de la trame annonce cinq calculs ; chaque fiche en porte dix.
     Les cinq premières font la séance, les cinq suivantes attendent le jour
     où il en redemande — ainsi l'adulte n'a jamais à en inventer une.

     L'heure ne se compte pas en dix mais en soixante : c'est la seule
     difficulté de la série, et elle revient à chaque séance. */

  f(
    "cg-durees-01",
    "Les durées",
    "D’heure en heure",
    [
      "Cinq questions font la séance ; les cinq suivantes sont là pour le jour où il en redemande, ou pour la semaine prochaine.",
      "Des heures entières seulement, aujourd’hui. On compte de l’une à l’autre, sur les doigts si besoin.",
      "Une horloge à aiguilles, même dessinée à la main sur l’ardoise, rend la chose visible : on part d’un chiffre, on arrive à un autre, on compte les bonds.",
    ],
    [
      "De 8 h à 11 h, combien de temps ?",
      "De 9 h à 12 h ?",
      "De 14 h à 17 h ?",
      "De 10 h à 16 h ?",
      "De 7 h à 12 h ?",
      "De 13 h à 18 h ?",
      "De 8 h à 12 h ?",
      "De 15 h à 20 h ?",
      "De 6 h à 9 h ?",
      "De 11 h à 19 h ?",
    ],
    ["3 h", "3 h", "3 h", "6 h", "5 h", "5 h", "4 h", "5 h", "3 h", "8 h"],
    "On regarde s’il soustrait ou s’il avance par bonds. Les deux donnent la bonne réponse ; celui qui avance par bonds tiendra mieux quand les minutes arriveront, alors ne l’en détournez pas.",
  ),

  f(
    "cg-durees-02",
    "Les durées",
    "Les demies et les quarts d’heure",
    [
      "Trois repères à poser : une demi-heure fait 30 minutes, un quart d’heure 15, trois quarts d’heure 45.",
      "Les deux horaires d’une même question tombent sur la même demie ou le même quart : la durée reste ronde, et c’est fait exprès.",
      "Cinq questions suffisent pour aujourd’hui. Gardez les cinq autres, elles serviront.",
    ],
    [
      "De 8 h à 8 h 30 ?",
      "De 9 h à 9 h 15 ?",
      "De 10 h à 10 h 45 ?",
      "De 8 h 30 à 9 h 30 ?",
      "De 14 h 15 à 15 h 15 ?",
      "De 9 h 30 à 11 h 30 ?",
      "De 16 h 45 à 17 h 45 ?",
      "De 8 h à 9 h 30 ?",
      "De 13 h à 14 h 45 ?",
      "De 10 h 15 à 12 h 15 ?",
    ],
    [
      "30 min",
      "15 min",
      "45 min",
      "1 h",
      "1 h",
      "2 h",
      "1 h",
      "1 h 30",
      "1 h 45",
      "2 h",
    ],
    "Quand les minutes sont les mêmes des deux côtés (8 h 30 à 9 h 30), la durée est un nombre entier d’heures. S’il le repère seul, il a trouvé une règle vraie, et elle lui fera gagner du temps toute l’année.",
  ),

  f(
    "cg-durees-03",
    "Les durées",
    "À la minute, dans la même heure",
    [
      "Toutes les questions restent à l’intérieur d’une même heure : on ne franchit pas encore le cap.",
      "La soustraction des minutes suffit : de 9 h 10 à 9 h 35, on fait 35 moins 10.",
      "Dictez lentement les horaires. « Quatorze heures zéro cinq » se confond vite avec « quatorze heures cinquante ».",
    ],
    [
      "De 9 h 10 à 9 h 35 ?",
      "De 14 h 05 à 14 h 50 ?",
      "De 8 h 20 à 8 h 55 ?",
      "De 10 h 12 à 10 h 40 ?",
      "De 16 h 25 à 16 h 55 ?",
      "De 11 h 08 à 11 h 38 ?",
      "De 15 h 30 à 15 h 47 ?",
      "De 7 h 15 à 7 h 50 ?",
      "De 13 h 40 à 13 h 59 ?",
      "De 9 h 03 à 9 h 33 ?",
    ],
    [
      "25 min",
      "45 min",
      "35 min",
      "28 min",
      "30 min",
      "30 min",
      "17 min",
      "35 min",
      "19 min",
      "30 min",
    ],
    "Tant qu’on reste dans la même heure, la durée est une soustraction ordinaire. C’est le moment de le lui dire clairement : ce confort-là va s’arrêter la prochaine fois, et il vaut mieux qu’il sache pourquoi.",
  ),

  f(
    "cg-durees-04",
    "Les durées",
    "Franchir l’heure",
    [
      "Le cap du jour : l’heure change au milieu de la durée. De 8 h 45 à 9 h 20, on ne peut plus soustraire les minutes directement.",
      "Le chemin en deux morceaux, à dire une fois puis à laisser : de 8 h 45 à 9 h, il y a 15 minutes ; de 9 h à 9 h 20, il y en a 20 ; en tout, 35.",
      "Laissez-le écrire l’étape intermédiaire. Deux nombres à retenir en même temps, c’est ce qui coûte le plus ici.",
    ],
    [
      "De 8 h 45 à 9 h 20 ?",
      "De 10 h 50 à 11 h 10 ?",
      "De 9 h 40 à 10 h 15 ?",
      "De 14 h 55 à 15 h 30 ?",
      "De 7 h 30 à 8 h 10 ?",
      "De 11 h 35 à 12 h 05 ?",
      "De 16 h 20 à 17 h 05 ?",
      "De 8 h 45 à 10 h 15 ?",
      "De 13 h 50 à 15 h 20 ?",
      "De 9 h 25 à 11 h 10 ?",
    ],
    [
      "35 min",
      "20 min",
      "35 min",
      "35 min",
      "40 min",
      "30 min",
      "45 min",
      "1 h 30",
      "1 h 30",
      "1 h 45",
    ],
    "Si la réponse à la première est 25 au lieu de 35, c’est qu’il a soustrait 45 de 20 comme s’il s’agissait de dizaines. Ce n’est pas une étourderie : c’est le 60 de l’heure qui n’est pas encore installé, et la méthode du chemin le contourne mieux qu’aucune explication.",
  ),

  f(
    "cg-durees-05",
    "Les durées",
    "Toute une journée",
    [
      "Des durées longues : plusieurs heures et des minutes, midi franchi presque à chaque fois.",
      "Toujours le chemin : on va d’abord à l’heure ronde suivante, puis d’heure en heure, puis on ajoute les dernières minutes.",
      "Écrivez les étapes sous ses yeux pendant qu’il les dit. Voir le chemin se construire vaut mieux que de le reconstruire de tête.",
    ],
    [
      "De 8 h 45 à 12 h 30 ?",
      "De 9 h 15 à 16 h 30 ?",
      "De 8 h 30 à 11 h 45 ?",
      "De 13 h 30 à 17 h 15 ?",
      "De 10 h 20 à 14 h 50 ?",
      "De 7 h 45 à 12 h 15 ?",
      "De 9 h 50 à 15 h 20 ?",
      "De 14 h 10 à 18 h 40 ?",
      "De 8 h 25 à 12 h 05 ?",
      "De 11 h 40 à 17 h 10 ?",
    ],
    [
      "3 h 45",
      "7 h 15",
      "3 h 15",
      "3 h 45",
      "4 h 30",
      "4 h 30",
      "5 h 30",
      "4 h 30",
      "3 h 40",
      "5 h 30",
    ],
    "Quand les minutes d’arrivée sont plus petites que celles de départ (8 h 25 à 12 h 05), il faut emprunter une heure. C’est le point le plus coûteux de toute la série ; s’il y arrive une fois, refaites-en une du même genre dès la séance suivante, tant que c’est frais.",
  ),

  f(
    "cg-durees-06",
    "Les durées",
    "Heures et minutes, dans les deux sens",
    [
      "On convertit : des heures vers les minutes, et des minutes vers les heures. Le nombre 60 est la clé de tout.",
      "Une question demande une fraction d’heure. Elle relie cette série à celle des fractions, et la réponse se dit en mots.",
      "La dernière demande 200 minutes en heures. Le chemin : combien de fois 60 tient dans 200, et que reste-t-il.",
    ],
    [
      "1 h en minutes",
      "2 h en minutes",
      "1 h 30 en minutes",
      "1 h 15 en minutes",
      "90 minutes en heures",
      "120 minutes en heures",
      "45 minutes, quelle fraction d’une heure ?",
      "150 minutes en heures",
      "2 h 45 en minutes",
      "200 minutes en heures",
    ],
    [
      "60 min",
      "120 min",
      "90 min",
      "75 min",
      "1 h 30",
      "2 h",
      "les trois quarts",
      "2 h 30",
      "165 min",
      "3 h 20",
    ],
    "L’erreur naturelle est de traiter 1 h 30 comme 1,30 et de répondre 130 minutes. Elle est logique et vient de tout ce qu’il a appris sur les nombres : dites-lui que l’heure est la seule grandeur qui se compte en soixante, et que ce n’est pas lui qui a mal compris.",
  ),

  f(
    "cg-durees-07",
    "Les durées",
    "Ajouter une durée à un horaire",
    [
      "Autre question : on connaît l’heure de départ et la durée, on cherche l’heure d’arrivée.",
      "Même méthode qu’avant, en avançant : on ajoute les heures, puis les minutes, et on passe à l’heure suivante quand on dépasse 60.",
      "Les réponses sont des horaires, pas des durées : on répond « 9 h 45 » et non « 9 h 45 de temps ».",
    ],
    [
      "Il est 9 h. Quelle heure sera-t-il 45 minutes plus tard ?",
      "Il est 10 h 30. Et 1 h plus tard ?",
      "Il est 8 h 50. Et 20 minutes plus tard ?",
      "Il est 14 h 15. Et 2 h 30 plus tard ?",
      "Il est 11 h 40. Et 35 minutes plus tard ?",
      "Il est 7 h 25. Et 1 h 45 plus tard ?",
      "Il est 16 h 20. Et 50 minutes plus tard ?",
      "Il est 13 h 55. Et 3 h plus tard ?",
      "Il est 9 h 35. Et 2 h 40 plus tard ?",
      "Il est 15 h 50. Et 1 h 25 plus tard ?",
    ],
    [
      "9 h 45",
      "11 h 30",
      "9 h 10",
      "16 h 45",
      "12 h 15",
      "9 h 10",
      "17 h 10",
      "16 h 55",
      "12 h 15",
      "17 h 15",
    ],
    "Le moment délicat est le dépassement : 40 + 35 font 75, donc une heure de plus et 15 minutes. S’il écrit 11 h 75, le calcul est juste et l’écriture ne l’est pas ; c’est une correction d’écriture seulement, et ça vaut la peine de le dire ainsi.",
  ),

  f(
    "cg-durees-08",
    "Les durées",
    "Retrouver l’heure de départ",
    [
      "On renverse encore : on connaît l’arrivée et la durée, on cherche le départ. Il faut donc reculer.",
      "Le chemin fonctionne à l’envers : on retire d’abord les heures, puis les minutes, en empruntant une heure si besoin.",
      "S’il a un doute, proposez-lui de vérifier en avançant depuis sa réponse. La vérification ne coûte rien et elle rassure.",
    ],
    [
      "Il arrive à 10 h après 2 h de route. À quelle heure est-il parti ?",
      "Arrivée à 12 h 30, trajet de 45 minutes. Départ ?",
      "Arrivée à 17 h, trajet de 1 h 30. Départ ?",
      "Arrivée à 9 h 15, trajet de 25 minutes. Départ ?",
      "Arrivée à 14 h 05, trajet de 1 h 20. Départ ?",
      "Arrivée à 18 h 40, trajet de 3 h. Départ ?",
      "Arrivée à 11 h 10, trajet de 40 minutes. Départ ?",
      "Arrivée à 16 h 25, trajet de 2 h 45. Départ ?",
      "Arrivée à 8 h 05, trajet de 50 minutes. Départ ?",
      "Arrivée à 20 h, trajet de 4 h 30. Départ ?",
    ],
    [
      "8 h",
      "11 h 45",
      "15 h 30",
      "8 h 50",
      "12 h 45",
      "15 h 40",
      "10 h 30",
      "13 h 40",
      "7 h 15",
      "15 h 30",
    ],
    "Reculer coûte plus que d’avancer, c’est vrai pour tout le monde. Si les questions où l’on emprunte une heure (la cinquième, la huitième, la neuvième) sont celles qui s’arrêtent, la vérification par l’avant est le meilleur appui : elle transforme un calcul difficile en un calcul qu’il sait déjà faire.",
  ),

  f(
    "cg-durees-09",
    "Les durées",
    "Jours, semaines et mois",
    [
      "On quitte l’horloge pour le calendrier. Un calendrier de l’année sous la main rend la séance bien plus vivante.",
      "Les questions 4 à 6 demandent la longueur des mois : la comptine des jointures, ou la chanson, tout est bon.",
      "Les deux questions d’intervalle (du 3 au 17 mars, du 25 mars au 5 avril) se comptent sur le calendrier avec le doigt. C’est la bonne façon de faire.",
    ],
    [
      "Combien de jours dans une semaine ?",
      "Combien de jours dans 3 semaines ?",
      "Combien de mois dans une année ?",
      "Combien de jours en janvier ?",
      "Combien de jours en février, une année ordinaire ?",
      "Combien de jours en avril ?",
      "Du 3 au 17 mars, combien de jours ?",
      "Du 25 mars au 5 avril, combien de jours ?",
      "Combien de semaines dans 28 jours ?",
      "Combien de jours dans une année ordinaire ?",
    ],
    [
      "7 jours",
      "21 jours",
      "12 mois",
      "31 jours",
      "28 jours",
      "30 jours",
      "14 jours",
      "11 jours (6 en mars, 5 en avril)",
      "4 semaines",
      "365 jours",
    ],
    "Le passage d’un mois à l’autre est la seule vraie difficulté : il oblige à savoir que mars a 31 jours. S’il compte 10 au lieu de 11, c’est presque toujours le dernier jour du mois qui a été oublié, et le calendrier le montre mieux qu’un raisonnement.",
  ),

  f(
    "cg-durees-10",
    "Les durées",
    "Les secondes",
    [
      "Une unité plus petite : la seconde. Une minute en compte 60, comme une heure compte 60 minutes.",
      "Un chronomètre, celui d’un téléphone par exemple, permet de sentir combien dure une minute. Faites l’expérience une fois, elle vaut la séance.",
      "La sixième question demande combien de secondes dans une heure. Le chemin : 60 minutes, chacune de 60 secondes.",
    ],
    [
      "1 minute en secondes",
      "2 minutes en secondes",
      "1 min 30 en secondes",
      "90 secondes en minutes",
      "300 secondes en minutes",
      "1 h en secondes",
      "45 secondes + 30 secondes",
      "180 secondes en minutes",
      "2 min 20 en secondes",
      "250 secondes en minutes",
    ],
    [
      "60 s",
      "120 s",
      "90 s",
      "1 min 30",
      "5 min",
      "3 600 s",
      "1 min 15 s",
      "3 min",
      "140 s",
      "4 min 10 s",
    ],
    "Le 3 600 impressionne, et c’est bon signe qu’il impressionne : cela veut dire qu’il se représente ce que ça fait. S’il hésite sur le calcul, donnez-lui 60 × 60 à poser ; la multiplication n’est pas le sujet du jour.",
  ),

  f(
    "cg-durees-11",
    "Les durées",
    "L’après-midi, le soir, la nuit",
    [
      "Deux façons de dire la même heure : 14 h ou 2 h de l’après-midi. On passe de l’une à l’autre en enlevant 12.",
      "Six questions franchissent le soir ou la nuit. Minuit s’écrit 24 h quand on compte, et 0 h quand on repart : dites-le une fois.",
      "Pour les durées de nuit, le chemin passe par minuit : de 21 h à minuit, puis de minuit à l’heure du matin.",
    ],
    [
      "14 h, c’est quelle heure de l’après-midi ?",
      "18 h 30, c’est quelle heure du soir ?",
      "Il est 20 h 15. Combien de temps jusqu’à minuit ?",
      "De 19 h 45 à 22 h 30 ?",
      "De 21 h à 6 h du matin ?",
      "De 22 h 30 à 7 h ?",
      "16 h 45, en heures de l’après-midi ?",
      "De 23 h 20 à minuit ?",
      "De 17 h 50 à 21 h 05 ?",
      "De 20 h à 5 h 30 ?",
    ],
    [
      "2 h de l’après-midi",
      "6 h et demie du soir",
      "3 h 45",
      "2 h 45",
      "9 h",
      "8 h 30",
      "4 h 45",
      "40 min",
      "3 h 15",
      "9 h 30",
    ],
    "Les durées qui traversent minuit sont les plus étranges : le nombre d’arrivée est plus petit que celui de départ, et pourtant le temps a avancé. Si ça le déroute, coupez la durée en deux à minuit et faites deux calculs ; l’étrangeté disparaît.",
  ),

  f(
    "cg-durees-12",
    "Les durées",
    "Comparer deux durées",
    [
      "On ne calcule plus une durée, on en compare deux. Le travail est de les ramener à la même unité avant de décider.",
      "Trois questions ont pour réponse « c’est pareil ». Prévenez-le : sinon, il cherchera une différence là où il n’y en a pas.",
      "Demandez-lui de justifier en une phrase : « 1 h 20, c’est 80 minutes, donc c’est plus long ». La justification est la séance.",
    ],
    [
      "Qu’est-ce qui dure le plus : 90 minutes ou 1 h 45 ?",
      "2 h ou 100 minutes ?",
      "3 600 secondes ou 1 h ?",
      "45 minutes ou trois quarts d’heure ?",
      "Une journée ou 1 000 minutes ?",
      "2 semaines ou 15 jours ?",
      "1 h 20 ou 75 minutes ?",
      "Un mois de 30 jours ou 4 semaines ?",
      "150 secondes ou 3 minutes ?",
      "1 h 05 ou 65 minutes ?",
    ],
    [
      "1 h 45 (105 min contre 90)",
      "2 h (120 min contre 100)",
      "c’est pareil",
      "c’est pareil",
      "une journée (1 440 min contre 1 000)",
      "15 jours (contre 14)",
      "1 h 20 (80 min contre 75)",
      "le mois (30 jours contre 28)",
      "3 minutes (180 s contre 150)",
      "c’est pareil",
    ],
    "Ce qu’on regarde ici n’est pas la réponse mais la conversion qui la précède. S’il compare 1 h 20 et 75 sans convertir, il a une chance sur deux d’avoir raison ; s’il convertit d’abord, il a la méthode, et c’est elle qu’on cherchait depuis septembre.",
  ),

  f(
    "cg-durees-13",
    "Les durées",
    "Des durées dans la vie",
    [
      "Dernière séance de la série : chaque question est une situation, et il faut d’abord décider ce qu’on cherche — une durée, ou un horaire.",
      "Deux questions demandent deux étapes, la quatrième et la neuvième. Prévenez avant de les dicter.",
      "Si vous n’en faites que cinq, prenez les cinq premières : les suivantes attendront sans s’abîmer.",
    ],
    [
      "Un film commence à 20 h 30 et dure 1 h 50. À quelle heure se termine-t-il ?",
      "Le train part à 9 h 12 et arrive à 11 h 47. Combien dure le trajet ?",
      "Un gâteau cuit 40 minutes, enfourné à 15 h 25. À quelle heure le sortir ?",
      "Il travaille de 8 h 45 à 12 h 30, puis de 13 h 30 à 16 h 15. Combien de temps en tout ?",
      "Une partie dure 25 minutes, ils en font quatre. Combien de temps ?",
      "Le car part à 7 h 50, le trajet dure 1 h 25. À quelle heure arrive-t-il ?",
      "Il dort de 21 h 15 à 7 h. Combien de temps ?",
      "Trois épisodes de 22 minutes. Combien de temps ?",
      "Un match de deux mi-temps de 45 minutes, avec 15 minutes de pause. Combien de temps en tout ?",
      "La recette demande 1 h 30 et il commence à 11 h 15. À quelle heure aura-t-il fini ?",
    ],
    [
      "22 h 20",
      "2 h 35",
      "16 h 05",
      "6 h 30 (3 h 45 le matin, 2 h 45 l’après-midi)",
      "1 h 40 (100 minutes)",
      "9 h 15",
      "9 h 45",
      "1 h 06 (66 minutes)",
      "1 h 45 (105 minutes)",
      "12 h 45",
    ],
    "Le signe que la série a fait son travail n’est pas le nombre de réponses justes : c’est qu’il distingue tout seul « combien de temps ? » de « à quelle heure ? ». S’il confond encore les deux questions, reprenez-les côte à côte sur une même situation, et rien d’autre.",
  ),
];
