/**
 * La copie, les mots invariables, la transformation de phrases.
 *
 * Trois rituels, vingt minutes. Une fiche donne **le texte à copier ou les phrases à transformer**, avec ce qu'il faut regarder dans ce qu'il a écrit.
 *
 * Ce qu'une fiche donne, et pourquoi : voir `lib/fiches/types.ts`. En deux
 * mots — le matériel exact, le corrigé quand il y en a un, et ce qu'on
 * regarde. Un adulte qui l'ouvre ne doit plus rien avoir à chercher.
 *
 * **Réservé aux adultes** : ces fiches portent les corrigés.
 *
 * Trois séries, écrites dans l'ordre où elles se donnent, de décembre à
 * juillet : seize copies, dix-huit listes de mots invariables, quinze séries
 * de phrases à transformer. Une série n'est pas datée ; son rang la situe.
 * Les premières fiches tombent en décembre — les nombres y restent à
 * quatre chiffres, comme le demande le programme du cycle 3 —, le gros de
 * chaque série de janvier à avril, la fin de mai à juillet.
 *
 * Les textes à copier sont soit écrits pour ce cahier, soit du domaine public
 * ancien : trois fables de Jean de La Fontaine, nommées comme telles.
 *
 * Rien de tout ceci n'a été relu par un enseignant. Ça doit l'être.
 */

import { f, type Fiche } from "./types";

/* ------------------------------------------------------------------ */
/* Copie soignée — seize textes de huit lignes                         */
/* ------------------------------------------------------------------ */

const COPIE: Fiche[] = [
  f(
    "ec-copie-01",
    "Copie soignée",
    "Copie 1 · Le chat de la remise",
    [
      "Le texte est là : il n’y a rien à choisir, rien à inventer. On pose cette page à côté du cahier, bien à plat, à sa gauche s’il est droitier.",
      "La méthode, dès aujourd’hui : lire une ligne entière, la redire à voix basse, cacher le modèle avec la main, puis écrire. On ne recopie pas lettre par lettre.",
      "Huit lignes, c’est beaucoup pour un premier jour. S’il en reste deux quand les vingt minutes sont passées, on s’arrête là : six lignes tenues valent mieux que huit expédiées.",
    ],
    [
      "Le chat gris dort dans la remise.",
      "Il a choisi le vieux panier de bois.",
      "Dehors, la pluie tombe sur les tuiles.",
      "Personne ne viendra le déranger.",
      "Il ouvre un œil, puis il le referme.",
      "Sa queue bat lentement contre la paille.",
      "Le jardin sent la terre mouillée.",
      "Le chat gris dort dans la remise.",
    ],
    undefined,
    "Pour cette première fois, regarde le geste plus que le résultat : la feuille tenue de l’autre main, les pieds posés, la ligne qui ne descend pas vers la droite. Regarde surtout combien de mots il garde en tête d’un seul coup. S’il revient au modèle à chaque syllabe, c’est cette mémoire-là qu’on fera grandir, pas son écriture.",
  ),
  f(
    "ec-copie-02",
    "Copie soignée",
    "Copie 2 · La boulangerie",
    [
      "Même méthode qu’au premier jour : lire la ligne, la redire sans regarder, l’écrire, vérifier.",
      "Ce texte-ci a des virgules. Une virgule se lit comme un petit temps d’arrêt, et elle se recopie comme une lettre : elle fait partie du texte.",
      "À la fin, la relecture se fait le doigt sous chaque mot, en partant de la dernière ligne et en remontant. À l’endroit, on lit l’histoire ; à l’envers, on voit les mots.",
    ],
    [
      "Il est six heures et la ville dort encore.",
      "Dans la boulangerie, la lumière est allumée.",
      "Le boulanger sort une plaque du four.",
      "Une odeur de pain chaud remplit la rue.",
      "Un chien s’arrête devant la vitrine.",
      "Il lève le museau et il attend.",
      "La porte s’ouvre, la cloche sonne.",
      "La journée peut commencer.",
    ],
    undefined,
    "Les virgules, d’abord : sont-elles toutes là, et à la bonne place ? Ensuite les majuscules de début de ligne, qui sont aussi des débuts de phrase ici. Si les majuscules tombent et que le reste tient, c’est qu’il lit trop vite le premier mot de la ligne : on lui fera montrer du doigt la majuscule avant d’écrire.",
  ),
  f(
    "ec-copie-03",
    "Copie soignée",
    "Copie 3 · Ce qu’il y a dans le cartable",
    [
      "Une phrase de ce texte court sur trois lignes. On la lit en entier d’abord, à voix haute, pour entendre où elle va.",
      "Quand une phrase ne tient pas sur une ligne, on continue à la ligne suivante sans majuscule : c’est la même phrase. Dis-le-lui avant qu’il commence, ça évite une reprise.",
      "L’énumération se recopie virgule par virgule. On peut lui demander de compter les objets à voix haute avant d’écrire : il y en a cinq.",
    ],
    [
      "Sur la table, Léon vide son cartable.",
      "Il en sort un cahier, deux crayons, une règle,",
      "une gomme grise et un taille-crayon cassé.",
      "Au fond, il trouve un marron de l’automne dernier.",
      "Il le pose près de la fenêtre, à la lumière.",
      "Le marron est lisse, brun, un peu terne.",
      "Il le gardera jusqu’au printemps, dans une boîte.",
      "Ensuite, il rangera tout le reste.",
    ],
    undefined,
    "Le passage d’une ligne à l’autre au milieu d’une phrase : garde-t-il la minuscule, ou remet-il une majuscule par habitude ? C’est le point du jour. Regarde aussi le trait d’union de « taille-crayon » : c’est souvent le premier signe qu’on oublie, parce qu’on ne l’entend pas.",
  ),
  f(
    "ec-copie-04",
    "Copie soignée",
    "Copie 4 · Le vieux pommier",
    [
      "Ce texte est à l’imparfait, et il en est plein : donnait, ramassait, faisait, disait. On les lit ensemble avant de copier, pour que l’oreille les reconnaisse.",
      "La consigne du jour porte sur les terminaisons : quand il arrive à un verbe, il ralentit et il l’épelle tout bas avant de l’écrire.",
      "Deux lignes changent de temps à la fin. Elles sont là exprès : on ne les explique pas, on les copie, et on en reparle une autre fois.",
    ],
    [
      "Au fond du jardin se tenait un vieux pommier.",
      "Son tronc était creux et ses branches partaient bas.",
      "Chaque été, il donnait des pommes petites et dures.",
      "On les ramassait dans un seau de métal bleu.",
      "Ma grand-mère en faisait de la compote.",
      "Elle disait que les meilleures pommes sont les plus laides.",
      "Le pommier est tombé pendant l’hiver.",
      "À sa place, on a planté un cerisier.",
    ],
    undefined,
    "Les terminaisons en -ait : tiennent-elles toutes les six, ou est-ce que le t final s’en va quand la main se fatigue ? Si les trois premières sont justes et les trois dernières non, ce n’est pas l’orthographe qui manque, c’est l’attention en fin de séance : on raccourcira à six lignes la prochaine fois.",
  ),
  f(
    "ec-copie-05",
    "Copie soignée",
    "Copie 5 · La panne d’électricité",
    [
      "Nouveauté du jour : les deux-points et les guillemets. On les regarde ensemble avant de commencer. Les deux-points annoncent, les guillemets encadrent des paroles.",
      "En français, on laisse une espace avant les deux-points et à l’intérieur des guillemets. Sur le cahier, ça se voit : le signe ne se colle pas au mot.",
      "Il copie, puis il souligne au crayon les paroles de son père. Une seule fois, à la règle.",
    ],
    [
      "La panne est arrivée juste après le dîner.",
      "D’un coup, toute la maison est devenue noire.",
      "Mon père a dit une seule chose : « Ne bougez pas. »",
      "Il a cherché la lampe de poche dans le tiroir.",
      "Le faisceau a traversé la cuisine, puis le couloir.",
      "Nous avons allumé trois bougies sur la table.",
      "La lumière est revenue à dix heures du soir.",
      "Nous avons été un peu déçus.",
    ],
    undefined,
    "Les guillemets sont-ils fermés ? C’est le signe qu’on ouvre et qu’on oublie. Regarde aussi l’espace avant les deux-points : s’il colle le signe au mot, montre-lui la différence sur la page plutôt que de l’expliquer, l’œil comprend plus vite que l’oreille.",
  ),
  f(
    "ec-copie-06",
    "Copie soignée",
    "Copie 6 · « La Cigale et la Fourmi », Jean de La Fontaine",
    [
      "Premier texte en vers de l’année. Un vers commence par une majuscule même quand la phrase continue : c’est la règle, et elle surprend toujours.",
      "On ne va pas à la ligne n’importe où : on va à la ligne là où le poète l’a mis. Le retour à la ligne fait partie du texte.",
      "Ce sont les huit premiers vers de la fable : elle continue. Lis-lui la suite à voix haute quand il a fini de copier, ça vaut la peine.",
    ],
    [
      "La Cigale, ayant chanté",
      "Tout l’été,",
      "Se trouva fort dépourvue",
      "Quand la bise fut venue :",
      "Pas un seul petit morceau",
      "De mouche ou de vermisseau.",
      "Elle alla crier famine",
      "Chez la Fourmi sa voisine,",
    ],
    undefined,
    "Les majuscules de début de vers, et les deux majuscules du milieu — la Cigale et la Fourmi portent la leur parce que ce sont des personnages. S’il les met partout, ou s’il n’en met aucune, on relit ensemble les huit vers en pointant chaque grande lettre : c’est plus parlant qu’une règle.",
  ),
  f(
    "ec-copie-07",
    "Copie soignée",
    "Copie 7 · La pâte à crêpes",
    [
      "Ce texte n’est pas un récit, c’est une recette : la mise en page compte autant que les mots. Les ingrédients sont l’un sous l’autre, et ça se recopie tel quel.",
      "Les abréviations d’unités ne prennent pas de point et ne prennent pas de s : on écrit 250 g, jamais 250 grs. Une espace sépare le nombre de l’unité.",
      "S’il veut faire les crêpes après, il faudra qu’il relise sa copie pour savoir quoi verser. C’est la meilleure raison de copier juste qu’on puisse lui donner.",
    ],
    [
      "Pour une vingtaine de crêpes, il faut :",
      "250 g de farine,",
      "3 œufs entiers,",
      "un demi-litre de lait,",
      "une pincée de sel.",
      "Verser la farine dans un saladier, puis creuser un puits.",
      "Casser les œufs au milieu et ajouter le lait peu à peu.",
      "Laisser reposer la pâte une heure avant de cuire.",
    ],
    undefined,
    "La mise en page : les quatre ingrédients restent-ils l’un sous l’autre, ou se recollent-ils en un paragraphe ? Regarde aussi le œ de « œufs ». S’il écrit « oeufs », montre-lui la lettre collée sans en faire une affaire — c’est un détail de typographie, pas une règle d’orthographe.",
  ),
  f(
    "ec-copie-08",
    "Copie soignée",
    "Copie 8 · La lettre de Lucien",
    [
      "Une lettre a une forme : le lieu et la date en haut à droite, la formule d’appel seule sur sa ligne, la signature en bas. On lui montre la page avant d’écrire.",
      "On lui laisse reproduire les retraits comme il les voit. Pour une fois, on regarde autant les blancs que les lettres.",
      "S’il a envie d’écrire une vraie lettre après cette copie, c’est le bon moment : il aura le modèle sous les yeux.",
    ],
    [
      "Nantes, le 14 mars",
      "Cher oncle Marcel,",
      "Je t’écris de la table de la cuisine, il pleut depuis deux jours.",
      "Le poulailler est terminé et les trois poules sont installées.",
      "Celle qui a des plumes rousses se laisse porter sans protester.",
      "Maman dit que tu viendras peut-être à Pâques.",
      "J’espère que oui, j’ai beaucoup de choses à te montrer.",
      "Ton neveu, Lucien",
    ],
    undefined,
    "La virgule après « Cher oncle Marcel » et la place de la date : ce sont les deux marques de la lettre, et ce sont celles qui sautent. Regarde aussi s’il pense à laisser une ligne blanche avant la signature. Rien de tout cela ne s’invente : ça se montre, et ça se refait.",
  ),
  f(
    "ec-copie-09",
    "Copie soignée",
    "Copie 9 · Au marché",
    [
      "Un dialogue. Chaque prise de parole commence par un tiret cadratin et une majuscule, et va à la ligne. Le tiret n’est pas un trait d’union : il est plus long.",
      "On lit le dialogue à deux voix avant de copier — toi la marchande, lui le garçon. Ça met la ponctuation dans l’oreille.",
      "Il copie ensuite en respectant les retours à la ligne. Les deux lignes sans tiret ne sont pas des paroles : ce sont les phrases du narrateur.",
    ],
    [
      "La marchande essuyait ses mains sur son tablier.",
      "— Bonjour, madame. Combien coûtent les poireaux ?",
      "— Deux euros la botte, mon garçon.",
      "— J’en voudrais une, s’il vous plaît.",
      "Elle a choisi la plus belle et l’a posée sur la balance.",
      "— Tu diras bonjour à ta mère de ma part.",
      "— Je n’oublierai pas. Merci, madame.",
      "Il est reparti en serrant la botte contre lui.",
    ],
    undefined,
    "Les cinq tirets, et seulement eux : ne met-il pas de tiret devant les deux lignes du narrateur ? S’il en met partout, c’est qu’il n’a pas encore vu que le dialogue et le récit s’alternent — on relira la page en surlignant d’une couleur ce qui se dit à voix haute.",
  ),
  f(
    "ec-copie-10",
    "Copie soignée",
    "Copie 10 · « Le Lièvre et la Tortue », Jean de La Fontaine",
    [
      "Des vers et un dialogue en même temps : c’est le texte le plus chargé depuis septembre. On le lit deux fois à voix haute avant que le crayon bouge.",
      "Il y a un point-virgule à la première ligne. C’est un point qui n’arrête pas tout à fait : on le lui montre, on ne l’explique pas plus.",
      "Certains mots sont anciens — gageons, commère, ellébore. On les dit ensemble, on en donne le sens en une phrase, et on copie.",
    ],
    [
      "Rien ne sert de courir ; il faut partir à point.",
      "Le Lièvre et la Tortue en sont un témoignage.",
      "Gageons, dit celle-ci, que vous n’atteindrez point",
      "Sitôt que moi ce but. — Sitôt ? Êtes-vous sage ?",
      "Repartit l’animal léger.",
      "Ma commère, il vous faut purger",
      "Avec quatre grains d’ellébore.",
      "— Sage ou non, je parie encore.",
    ],
    undefined,
    "Les accents des majuscules : le Ê de « Êtes-vous ». Beaucoup d’adultes ne le mettent pas non plus ; s’il l’oublie, c’est une occasion de lui apprendre quelque chose que peu de gens savent, ce qui vaut mieux qu’une correction. Regarde aussi si le point-virgule survit à la copie.",
  ),
  f(
    "ec-copie-11",
    "Copie soignée",
    "Copie 11 · Le hérisson",
    [
      "Un texte documentaire : les phrases sont plus longues et les informations sont précises. Une virgule de travers change le sens, donc on va lentement.",
      "Il y a des parenthèses. Ce qu’elles contiennent est une précision qu’on pourrait enlever sans casser la phrase — on essaie à voix haute, on entend que ça marche.",
      "Une ligne porte un nombre en chiffres. Les nombres à quatre chiffres s’écrivent avec une espace entre les milliers et les centaines : 5 000, pas 5000.",
    ],
    [
      "Le hérisson est un petit mammifère couvert de piquants (environ 5 000 chez l’adulte).",
      "Il vit dans les haies, les jardins et les lisières de forêt.",
      "La nuit, il parcourt parfois deux kilomètres pour chercher sa nourriture.",
      "Il mange des vers, des limaces, des insectes et, plus rarement, des fruits tombés.",
      "Quand il a peur, il se met en boule : ses piquants forment alors une armure.",
      "De novembre à mars, il hiberne dans un nid de feuilles sèches.",
      "Sa température descend, son cœur ralentit, il ne se réveille presque pas.",
      "Un tas de bois laissé au fond du jardin peut lui servir d’abri.",
    ],
    undefined,
    "L’espace du nombre : écrit-il 5 000 ou 5000 ? Et les parenthèses sont-elles fermées ? Regarde aussi la quatrième ligne, celle qui a une virgule avant « et » — elle est rare et elle est juste : si elle disparaît sous sa plume, ce n’est pas grave, mais montre-la-lui, c’est une virgule qui fait respirer.",
  ),
  f(
    "ec-copie-12",
    "Copie soignée",
    "Copie 12 · La tempête",
    [
      "Ce récit est au passé simple, le temps des livres. On ne le parle pas, on l’écrit : leva, battirent, fut, mangeâmes.",
      "Deux formes vont l’étonner : « mangeâmes » et son accent circonflexe, « il fallut » sans t muet. On les lit avant, on ne les corrige pas après.",
      "Après la copie, il relit à voix haute et il entoure les verbes qu’il ne dirait jamais en parlant. Il y en a huit.",
    ],
    [
      "Le vent se leva vers minuit et ne retomba plus.",
      "Les volets battirent contre le mur pendant des heures.",
      "Au matin, deux tuiles gisaient en morceaux devant la porte.",
      "Le grand peuplier du voisin s’était couché en travers du chemin.",
      "Personne ne fut blessé, mais l’électricité manqua jusqu’au soir.",
      "Nous mangeâmes du pain et des conserves, à la lueur des bougies.",
      "Le lendemain, tout le hameau sortit avec des scies.",
      "Il fallut trois jours pour dégager la route.",
    ],
    undefined,
    "L’accent circonflexe de « mangeâmes » et le â qu’il faut aller chercher : s’il le pose, c’est qu’il copie vraiment ce qu’il voit et non ce qu’il croit lire. C’est l’indice le plus fiable de tout le rituel. Regarde ensuite le mot « gisaient », qui ne ressemble à rien de connu — les mots inconnus sont ceux qu’on copie le mieux, parce qu’on les regarde.",
  ),
  f(
    "ec-copie-13",
    "Copie soignée",
    "Copie 13 · Un article de dictionnaire",
    [
      "Une page de dictionnaire a ses codes : le mot en capitales, l’abréviation de sa nature, l’origine entre parenthèses, les sens numérotés.",
      "« n. m. » veut dire nom masculin, et les points d’abréviation se recopient. Les points-virgules séparent des exemples qui vont ensemble.",
      "Après la copie, il cherche le même mot dans un vrai dictionnaire de la maison et il compare les deux mises en page. Cinq minutes, pas plus.",
    ],
    [
      "ORAGE n. m. (du latin aura, souffle d’air).",
      "1. Perturbation violente de l’atmosphère, avec des éclairs et du tonnerre ;",
      "elle s’accompagne souvent de pluie, parfois de grêle.",
      "Un orage éclate ; un orage gronde au loin ; le ciel est à l’orage.",
      "2. Au sens figuré : trouble, moment de colère dans une famille.",
      "Il y a de l’orage dans l’air.",
      "Synonymes : bourrasque, tempête, tourmente.",
      "Famille du mot : orageux, orageuse, orageusement.",
    ],
    undefined,
    "Les points d’abréviation de « n. m. » et les deux chiffres qui ouvrent les sens : ce sont les marques du genre de texte, et elles sautent facilement parce qu’elles ne se disent pas. Regarde aussi les points-virgules de la quatrième ligne : trois exemples séparés, trois signes identiques. S’il les remplace par des virgules, la phrase tient encore — dis-le-lui, ça le rassurera sur ce qui est grave et ce qui ne l’est pas.",
  ),
  f(
    "ec-copie-14",
    "Copie soignée",
    "Copie 14 · Le phare",
    [
      "Un poème écrit pour ce cahier, en deux strophes de quatre vers. Entre les deux, on laisse une ligne blanche : elle compte, elle se copie elle aussi.",
      "On le lit d’abord en entier, lentement, sans commenter. Puis il en dit ce qu’il veut, ou rien.",
      "Il copie, et s’il en a envie, il apprend les quatre premiers vers par cœur pour un autre jour. Ce n’est pas demandé.",
    ],
    [
      "Toute la nuit, le phare a veillé sur la mer.",
      "Il n’a rien dit à personne, il n’a pas fait de bruit.",
      "Il tournait lentement, il ouvrait sa lumière,",
      "Et sa lumière partait chercher les gens dans la nuit.",
      "Au matin, le dernier bateau est revenu au port.",
      "Le patron a levé la main vers la haute maison.",
      "Le phare s’est éteint sans un mot, sans effort,",
      "Et il a laissé le jour s’occuper de l’horizon.",
    ],
    undefined,
    "La ligne blanche entre les deux strophes, et la majuscule de chaque vers : c’est tout ce qu’on regarde en premier. Ensuite, si le cœur y est, demande-lui quel vers il préfère et pourquoi. Une copie qu’on a aimée se tient mieux droite que les autres, et ça se voit sur la page.",
  ),
  f(
    "ec-copie-15",
    "Copie soignée",
    "Copie 15 · Monter la tente",
    [
      "Un mode d’emploi. Les verbes sont à l’impératif — étale, glisse, plante — et ils n’ont pas de sujet. On le remarque ensemble avant de copier.",
      "Les cinq étapes sont numérotées et alignées. Le chiffre, le point, une espace, puis la phrase : cette régularité est la moitié du texte.",
      "La première et la dernière ligne ne sont pas numérotées : ce sont des conseils, pas des étapes. Il faut qu’il les distingue à l’œil avant d’écrire.",
    ],
    [
      "Avant de commencer, choisis un terrain plat, sans cailloux ni racines.",
      "1. Étale la tente au sol, la porte tournée à l’opposé du vent.",
      "2. Glisse les deux arceaux dans les fourreaux, sans jamais forcer.",
      "3. Plante un piquet à chaque coin, en biais, à quarante-cinq degrés.",
      "4. Tends le double toit : il ne doit toucher la tente à aucun endroit.",
      "5. Vérifie les haubans et retends-les le soir, l’humidité les détend.",
      "Range la housse et les piquets restants dans la poche intérieure.",
      "Une tente bien tendue résiste à la pluie ; une tente molle prend l’eau.",
    ],
    undefined,
    "L’alignement des cinq étapes : les chiffres se suivent-ils dans la même colonne, ou la marge part-elle en biais ? C’est le seul texte de l’année où la géométrie de la page dit quelque chose. Regarde aussi le É majuscule accentué d’« Étale » : deuxième rencontre après la fable du Lièvre, et bonne occasion de voir si ça a tenu.",
  ),
  f(
    "ec-copie-16",
    "Copie soignée",
    "Copie 16 · Madame Ferrand",
    [
      "La dernière copie de l’année, et la plus dense : lignes longues, deux-points, point-virgule, guillemets, tirets. Tout ce qui a été vu depuis septembre est là.",
      "On ne prévient pas qu’elle est plus difficile. On donne le texte, on donne le temps, et s’il ne fait que cinq lignes, ce sont cinq lignes de fin d’année.",
      "Quand c’est fini, sors la toute première copie, celle de décembre, et pose-la à côté, sans rien dire. La comparaison se fait toute seule, et elle est de lui à lui.",
    ],
    [
      "Madame Ferrand tenait la mercerie du bout de la rue, celle qui sentait la poussière et le tissu neuf.",
      "Elle était petite, sèche, avec des lunettes qu’elle remontait toutes les trois minutes.",
      "Sur le comptoir, des boîtes plates contenaient des boutons triés par couleur : les blancs, les noirs, puis tous les autres.",
      "Quand on entrait, elle disait « bonjour » sans lever les yeux ; quand on sortait, elle disait « à bientôt » de la même voix.",
      "Elle connaissait le prénom de tous les enfants du quartier et l’âge exact de leurs manteaux.",
      "On la croyait sévère. Elle ne l’était pas : elle était occupée.",
      "Le jour où la mercerie a fermé, il y avait quinze personnes devant la porte.",
      "Elle a tiré le rideau, elle a tourné la clé, et elle est partie sans se retourner.",
    ],
    undefined,
    "Ce qui tient tout seul, maintenant, et ce qui demande encore de l’attention : la ponctuation double, les guillemets, le point-virgule. Note pour toi, pas pour lui, les deux ou trois signes qui résistent encore — ce sont ceux par lesquels on recommencera l’an prochain. Et si la dernière ligne est aussi soignée que la première, c’est le vrai résultat de l’année.",
  ),
];

/* ------------------------------------------------------------------ */
/* Les mots invariables — dix-huit listes de dix mots                  */
/* ------------------------------------------------------------------ */

const INVARIABLES: Fiche[] = [
  f(
    "ec-invar-01",
    "Les mots invariables",
    "Liste 1 · les petits mots de tous les jours",
    [
      "Deux temps de dix minutes. D’abord apprendre : tu montres le mot, il le lit, il l’épelle à voix haute, il l’écrit une fois. On passe au suivant.",
      "Ensuite dicter : tu lis la phrase entière, il l’écrit, tu relis une fois. Les phrases sont là, à la suite de chaque mot.",
      "On corrige tout de suite, ensemble. Dans un mot qui a hésité, il entoure la lettre qui a hésité, on redit ensemble une fois le repère du mot, et deux de ces mots reviennent à la prochaine dictée, glissés au milieu des autres.",
    ],
    [
      "dans — jamais de t à la fin, mais un s qu’on n’entend pas. Dictée : Les clés sont dans la poche de gauche.",
      "pour — un r final qu’on entend bien, et qu’on écrit. Dictée : Ce paquet est pour toi.",
      "avec — un c final, et lui, on l’entend. Dictée : Il part avec son frère.",
      "sans — un s à la fin, comme dans « dans ». Dictée : Il est sorti sans manteau.",
      "chez — se termine par un z, toujours. Dictée : On mange chez ma grand-mère.",
      "sous — un s final, comme dans « dessous ». Dictée : Le chat dort sous la table.",
      "sur — un seul r, et pas d’accent. Dictée : Le livre est sur l’étagère.",
      "vers — un s final muet. Dictée : Il marche vers la rivière.",
      "contre — se termine par un e. Dictée : Le vélo est appuyé contre le mur.",
      "entre — se termine par un e, comme « contre ». Dictée : Le chemin passe entre deux haies.",
    ],
    undefined,
    "Ces dix mots reviendront tous les jours de l’année dans tout ce qu’il écrira : ce sont eux qui rapportent le plus. Regarde surtout les lettres finales muettes — le s de « dans », de « sans », de « sous », de « vers ». Si l’une d’elles tombe, les autres tomberont aussi : c’est une seule chose à apprendre, pas quatre.",
  ),
  f(
    "ec-invar-02",
    "Les mots invariables",
    "Liste 2 · les mots du temps",
    [
      "Même déroulé : apprendre les dix, puis les écrire sous la dictée dans leur phrase.",
      "Ceux-ci disent quand. Avant d’écrire, demande-lui de les ranger à l’oral sur une ligne du temps : avant, maintenant, après. Un mot qui a une place se retient mieux.",
      "Si trois mots seulement tiennent aujourd’hui, ce sont ces trois-là qu’on garde. Les sept autres reviendront, ils ne sont pas perdus.",
    ],
    [
      "hier — pas de e à la fin. Dictée : Hier, il a plu toute la journée.",
      "demain — se termine par -ain, comme « pain ». Dictée : Demain, nous partons tôt.",
      "aujourd’hui — un seul mot, avec une apostrophe au milieu. Dictée : Aujourd’hui, le ciel est gris.",
      "toujours — un s final : il y a toujours plusieurs jours. Dictée : Il arrive toujours en avance.",
      "jamais — un s final muet. Dictée : Elle ne se plaint jamais.",
      "souvent — se termine par -ent, comme « vent ». Dictée : On se voit souvent le samedi.",
      "bientôt — un accent circonflexe sur le o. Dictée : Les vacances arrivent bientôt.",
      "tard — un d à la fin, qu’on retrouve dans « retarder ». Dictée : Il s’est couché tard.",
      "tôt — un accent circonflexe et un t final. Dictée : Le soleil se lève tôt en juin.",
      "maintenant — deux fois la syllabe -ant à l’oreille, une seule à l’écrit. Dictée : Maintenant, on range.",
    ],
    undefined,
    "L’apostrophe d’« aujourd’hui » : au bon endroit, ou après le d ? Et le circonflexe de « bientôt » et « tôt », qui va souvent par paires — s’il le met à l’un, il le met à l’autre. Le d muet de « tard » se retient par « retarder » : si le truc marche pour lui, on le réutilisera pour les autres lettres muettes.",
  ),
  f(
    "ec-invar-03",
    "Les mots invariables",
    "Liste 3 · les mots qui relient deux idées",
    [
      "Apprendre, puis dicter. Pour cette liste, ajoute un temps : il relit chaque phrase et il entoure le petit mot au crayon.",
      "Ces dix mots ne disent rien tout seuls — ils relient. On peut lui faire dire ce que chacun fait : ajouter, opposer, expliquer, mettre en ordre.",
      "Les phrases sont courtes exprès : c’est le mot de liaison qui compte, pas le reste.",
    ],
    [
      "mais — un s final muet. Dictée : Il a couru, mais il est arrivé en retard.",
      "ou — deux lettres, sans accent : il veut dire « ou bien ». Dictée : Tu prends du thé ou du lait ?",
      "et — jamais d’accent, et il ne remplace pas « ou ». Dictée : Le chien et le chat dorment.",
      "donc — un c final, souvent muet. Dictée : Il pleut, donc on reste ici.",
      "or — deux lettres, pas d’accent. Dictée : Il devait venir ; or il n’est pas là.",
      "ni — deux lettres, pas d’accent non plus. Dictée : Il n’a ni crayon ni gomme.",
      "car — un r final qu’on entend. Dictée : Rentre, car la nuit tombe.",
      "puis — un s final muet, qu’on retrouve dans « depuis ». Dictée : Il a mangé, puis il est sorti.",
      "ensuite — se termine par un e. Dictée : On range, ensuite on joue.",
      "enfin — se termine par -in. Dictée : Enfin, le bus est arrivé.",
    ],
    undefined,
    "Le piège de la liste, c’est « ou » sans accent contre « où » du lieu : il n’est pas encore demandé de les distinguer, mais note s’il met un accent par réflexe. Regarde aussi « puis » : le s tombe presque toujours la première fois, et il tient dès qu’on a fait le lien avec « depuis ».",
  ),
  f(
    "ec-invar-04",
    "Les mots invariables",
    "Liste 4 · les mots du lieu",
    [
      "Apprendre, puis dicter comme d’habitude. On peut faire la première partie debout, en désignant vraiment les endroits de la pièce.",
      "Dix mots qui disent où. Deux d’entre eux se ressemblent beaucoup : dedans et dehors, dessus et dessous. On les apprend par paires.",
      "S’il connaît déjà la moitié de la liste, on ne fait dicter que l’autre moitié et on garde dix minutes pour autre chose.",
    ],
    [
      "ici — pas d’accent, deux i. Dictée : Pose ton sac ici.",
      "là — un accent grave, qui le sépare de « la » du déterminant. Dictée : Le chat est là, sur la marche.",
      "ailleurs — deux l et un s final. Dictée : Cherchons ailleurs.",
      "partout — se termine par -out, comme « tout ». Dictée : Il y a des feuilles partout.",
      "dehors — un s final, qu’on retrouve dans « hors ». Dictée : Le chien dort dehors.",
      "dedans — un s final, comme dans « dans ». Dictée : La clé est dedans.",
      "devant — se termine par -ant. Dictée : Il attend devant la porte.",
      "derrière — un accent grave et deux r. Dictée : Le jardin est derrière la maison.",
      "loin — se termine par -oin, comme « point ». Dictée : L’école n’est pas loin.",
      "autour — un r final. Dictée : Une haie court autour du pré.",
    ],
    undefined,
    "L’accent de « là » : c’est le premier accent de l’année qui change le sens d’un mot. S’il l’oublie, on écrit les deux au tableau côte à côte, « la porte » et « il est là », et on lui demande lequel montre un endroit. Regarde aussi les deux r de « derrière », qui partent facilement.",
  ),
  f(
    "ec-invar-05",
    "Les mots invariables",
    "Liste 5 · les mots de la quantité",
    [
      "Apprendre, puis dicter. Cette liste-ci se prête à un jeu : tu dis une quantité avec les mains, il donne le mot.",
      "Attention à un point : ces mots ne changent jamais, même devant un pluriel. On écrit « beaucoup de livres », pas « beaucoups ».",
      "La correction se fait mot par mot. Dans un mot qui a hésité, il entoure la lettre qui a hésité, on redit ensemble une fois le repère du mot, et deux de ces mots reviennent à la prochaine dictée, glissés au milieu des autres.",
    ],
    [
      "beaucoup — un p final, comme dans « coup ». Dictée : Il y a beaucoup de monde sur la place.",
      "trop — un p final muet lui aussi. Dictée : Le café est trop chaud.",
      "assez — se termine par un z, comme « chez ». Dictée : Il y en a assez pour tout le monde.",
      "peu — trois lettres, jamais de x. Dictée : Il reste peu de pain.",
      "très — un accent grave et un s. Dictée : La rivière est très froide.",
      "plus — un s final, qu’on entend ou non selon la phrase. Dictée : Il n’y a plus de place.",
      "moins — un s final, toujours. Dictée : Il fait moins froid qu’hier.",
      "autant — se termine par -ant. Dictée : Prends-en autant que tu veux.",
      "tant — se termine par -ant aussi, comme « autant ». Dictée : Il a tant marché qu’il s’est endormi.",
      "presque — se termine par -que. Dictée : Le puzzle est presque fini.",
    ],
    undefined,
    "Le p muet de « beaucoup » et de « trop » : ils s’apprennent ensemble ou pas du tout. Si « beaucoup » prend un s parce qu’il y a beaucoup de choses, c’est une très bonne raison de se tromper — dis-le-lui, puis montre-lui que le mot ne bouge jamais, c’est justement pour ça qu’on l’appelle invariable.",
  ),
  f(
    "ec-invar-06",
    "Les mots invariables",
    "Liste 6 · les manières de faire",
    [
      "Apprendre, puis dicter. Quatre de ces mots s’écrivent en plusieurs morceaux : on les compte à voix haute avant de les écrire.",
      "Pour « à peine », « tout à fait », « de nouveau » et « par cœur », le piège n’est pas l’orthographe des mots, c’est de penser à laisser les espaces.",
      "S’il colle les morceaux, on ne raye pas : on lui demande combien de mots il entend, et il découpe lui-même.",
    ],
    [
      "bien — se termine par -ien, comme « rien ». Dictée : Il a bien travaillé ce matin.",
      "mal — trois lettres, pas de e. Dictée : Ce tiroir ferme mal.",
      "vite — se termine par un e. Dictée : Le temps passe vite en été.",
      "ensemble — un seul mot, avec un m devant le b. Dictée : Nous rangerons la cuisine ensemble.",
      "debout — se termine par -out, comme « partout ». Dictée : Il a mangé debout, près de l’évier.",
      "à peine — deux mots, et un accent grave sur le à. Dictée : Il a à peine touché son assiette.",
      "tout à fait — trois mots séparés. Dictée : Ce n’est pas tout à fait la même chose.",
      "de nouveau — deux mots, et « nouveau » avec -eau. Dictée : Il pleut de nouveau.",
      "par cœur — deux mots, et le œ collé. Dictée : Il connaît la chanson par cœur.",
      "à l’envers — trois morceaux, avec une apostrophe. Dictée : Ton pull est à l’envers.",
    ],
    undefined,
    "Les espaces : ce sont elles qu’on regarde aujourd’hui, plus que les lettres. « Toutàfait » d’un seul bloc veut dire qu’il écrit ce qu’il entend, ce qui est exactement ce qu’on lui demande de faire le reste du temps — donc on explique, on ne reprend pas. Le œ de « cœur » revient de la copie des crêpes : bon moment pour le lui rappeler.",
  ),
  f(
    "ec-invar-07",
    "Les mots invariables",
    "Liste 7 · les mots en -ment (première série)",
    [
      "Apprendre, puis dicter. Aujourd’hui il y a une règle à voir, et elle vaut pour les dix mots.",
      "Un mot en -ment se fabrique à partir d’un adjectif au féminin : douce donne doucement, lente donne lentement. Fais-lui dire le féminin avant d’écrire le mot.",
      "Deux mots échappent à la règle : joliment et poliment, où le e du féminin tombe. On les met de côté et on les apprend à part.",
    ],
    [
      "vraiment — de « vraie », mais le e disparaît. Dictée : Il fait vraiment froid ce matin.",
      "seulement — de « seule » : le e reste. Dictée : Il reste seulement deux parts.",
      "doucement — de « douce ». Dictée : Ferme la porte doucement.",
      "rapidement — de « rapide ». Dictée : Il a répondu rapidement.",
      "lentement — de « lente ». Dictée : Le fleuve coule lentement.",
      "tristement — de « triste ». Dictée : Le chien regardait tristement la porte.",
      "joliment — de « jolie », et là le e tombe. Dictée : La table est joliment mise.",
      "poliment — de « polie », le e tombe aussi. Dictée : Il a refusé poliment.",
      "franchement — de « franche ». Dictée : Dis-moi franchement ce que tu en penses.",
      "simplement — de « simple ». Dictée : Range-les simplement par couleur.",
    ],
    undefined,
    "La règle passe-t-elle avant le mot ? S’il écrit « joliement », c’est excellent : il applique ce qu’on vient de lui apprendre, et c’est l’exception qui cloche, pas lui. Dis-le-lui dans ces termes. Regarde ensuite si le e de « seulement » et de « doucement » tient — c’est le même e, entendu ou non.",
  ),
  f(
    "ec-invar-08",
    "Les mots invariables",
    "Liste 8 · la lettre finale qu’on n’entend pas",
    [
      "Apprendre, puis dicter. Cette liste n’a qu’un sujet : la dernière lettre, qui ne se prononce jamais.",
      "Pour chaque mot, cherchez ensemble un mot de la même famille où la lettre s’entend — dessous et dessouder ne marchent pas, mais longtemps et longue, si. Quand on n’en trouve pas, on apprend par l’œil.",
      "À la dictée, demande-lui de dire tout bas la dernière lettre avant de poser le point. Ça prend une seconde et ça change tout.",
    ],
    [
      "alors — un s final. Dictée : Alors, il a fermé son livre.",
      "volontiers — un s final, et un i qu’on n’attend pas. Dictée : Il viendrait volontiers dimanche.",
      "longtemps — un s final, et le mot « temps » caché dedans. Dictée : Il a attendu longtemps sous la pluie.",
      "exprès — un accent grave et un s. Dictée : Il a laissé la fenêtre ouverte exprès.",
      "après — un accent grave et un s, comme « exprès ». Dictée : On verra ça après le repas.",
      "autrefois — un s final, et « fois » caché dedans. Dictée : Autrefois, le moulin tournait encore.",
      "dessus — deux s au milieu, un s à la fin. Dictée : Le carton est lourd, ne t’assieds pas dessus.",
      "dessous — deux s au milieu, et « sous » à la fin. Dictée : La lettre était glissée dessous.",
      "mieux — se termine par un x, pas par un s. Dictée : Il respire mieux depuis hier.",
      "quelquefois — un seul mot, avec « fois » à la fin. Dictée : Quelquefois, il oublie son écharpe.",
    ],
    undefined,
    "La question du jour : met-il une lettre finale au hasard, ou la bonne ? Un s posé sur « mieux » vaut mieux qu’un mot nu — ça veut dire qu’il sait qu’il en faut une, il reste à savoir laquelle. Note les mots où il hésite entre s et x : ce sont ceux qu’on reprendra, et il y en a rarement plus de deux.",
  ),
  f(
    "ec-invar-09",
    "Les mots invariables",
    "Liste 9 · les mots en -ment (deuxième série)",
    [
      "Apprendre, puis dicter. On reprend la règle du mois dernier : l’adjectif au féminin, puis -ment.",
      "Trois mots demandent un détour : sûrement garde son circonflexe, absolument et profondément transforment la fin de l’adjectif. On les traite à part, à la fin.",
      "Il peut écrire d’abord l’adjectif féminin en petit dans la marge, puis le mot complet. C’est une béquille, et on l’enlèvera quand elle ne servira plus.",
    ],
    [
      "également — de « égale ». Dictée : Il a également prévenu sa sœur.",
      "tellement — de « telle ». Dictée : Il a tellement ri qu’il en a pleuré.",
      "absolument — de « absolue », et le e tombe. Dictée : Je veux absolument voir la fin.",
      "certainement — de « certaine ». Dictée : Il viendra certainement demain.",
      "heureusement — de « heureuse ». Dictée : Heureusement, la pluie s’est arrêtée.",
      "longuement — de « longue ». Dictée : Ils ont parlé longuement dans le couloir.",
      "autrement — de « autre », sans e supplémentaire. Dictée : On ne pouvait pas faire autrement.",
      "tardivement — de « tardive ». Dictée : Le courrier est arrivé tardivement.",
      "sûrement — de « sûre », circonflexe compris. Dictée : Il a sûrement oublié l’heure.",
      "profondément — de « profonde », et le e devient é. Dictée : Il dort profondément.",
    ],
    undefined,
    "Est-ce que la règle du mois dernier est revenue toute seule, ou faut-il la redonner ? C’est ça, l’information du jour — pas le nombre de mots justes. Regarde ensuite le circonflexe de « sûrement » : il vient de l’adjectif, et si le lien est fait, il tiendra pour toujours.",
  ),
  f(
    "ec-invar-10",
    "Les mots invariables",
    "Liste 10 · les mots qui portent un accent",
    [
      "Apprendre, puis dicter. Dix mots, dix accents, et chacun est là pour une raison.",
      "Avant d’écrire, il dit à voix haute quel accent porte le mot : grave, aigu, circonflexe. Nommer l’accent aide à le poser.",
      "« çà et là » est une curiosité : la cédille sur un a, on ne la rencontre presque jamais ailleurs. On la regarde pour le plaisir, et on l’écrit.",
    ],
    [
      "déjà — un accent aigu, puis un accent grave. Dictée : Il a déjà fini son assiette.",
      "où — un accent grave sur le u : il indique un lieu. Dictée : Je ne sais pas où il a rangé la scie.",
      "dès — un accent grave : il veut dire « à partir de ». Dictée : Dès le matin, le vent s’est levé.",
      "auprès — un accent grave et un s final. Dictée : Il est resté auprès du feu.",
      "plutôt — un accent circonflexe sur le o. Dictée : Prends plutôt le petit panier.",
      "aussitôt — un circonflexe aussi, comme « bientôt ». Dictée : Aussitôt rentré, il a ôté ses bottes.",
      "à côté — un accent grave, puis deux accents aigus. Dictée : Assieds-toi à côté de moi.",
      "çà et là — une cédille sur le a, ce qui est rare. Dictée : Des outils traînaient çà et là dans l’atelier.",
      "guère — un accent grave, et un u muet après le g. Dictée : Il ne reste guère de bois sec.",
      "près — un accent grave et un s. Dictée : La ferme est tout près du pont.",
    ],
    undefined,
    "L’accent de « où » : est-ce qu’il le pose parce que le mot dit un lieu, ou parce qu’il l’a vu sur la fiche ? Demande-lui, sans piège. Regarde aussi le u muet de « guère » : c’est le même que dans « guitare » et « guerre », et une fois vu, il ne s’oublie plus.",
  ),
  f(
    "ec-invar-11",
    "Les mots invariables",
    "Liste 11 · les mots écrits en plusieurs morceaux",
    [
      "Apprendre, puis dicter. Aujourd’hui on compte : chaque expression vaut deux, trois, parfois quatre mots, et il les compte sur ses doigts avant d’écrire.",
      "Quatre d’entre elles portent un trait d’union — peut-être, c’est-à-dire, au-dessus, au-dessous — et les six autres n’en portent pas. C’est le tri du jour.",
      "Une astuce qui marche : on écrit d’abord les traits d’union et les espaces en l’air, du doigt, puis on pose le crayon.",
    ],
    [
      "peut-être — un trait d’union, et un t à « peut ». Dictée : Il viendra peut-être avec sa cousine.",
      "c’est-à-dire — deux traits d’union et une apostrophe. Dictée : Il rentre lundi, c’est-à-dire dans trois jours.",
      "au-dessus — un trait d’union, puis deux s au milieu. Dictée : La lampe est au-dessus de la table.",
      "au-dessous — un trait d’union aussi, et « sous » à la fin. Dictée : Le tiroir au-dessous est vide.",
      "tout à coup — trois mots séparés, sans trait d’union. Dictée : Tout à coup, le chien s’est mis à aboyer.",
      "à peu près — trois mots, deux accents. Dictée : Il reste à peu près un litre de lait.",
      "bien sûr — deux mots, et un circonflexe sur le u. Dictée : Bien sûr que tu peux venir.",
      "tout de suite — trois mots, et pas de « t » à « suite ». Dictée : Range ton bol tout de suite.",
      "par exemple — deux mots, et un seul m. Dictée : Prends un fruit, une pomme par exemple.",
      "en effet — deux mots, deux f. Dictée : Il pleuvait, en effet, depuis la veille.",
    ],
    undefined,
    "Traits d’union et espaces : c’est tout ce qui compte aujourd’hui. Fais la liste, pour toi, de ceux qu’il écrit collés — ce sont presque toujours les mêmes trois, et trois expressions, ça s’apprend en une semaine. Si les lettres sont justes et que seule la découpe cloche, dis-lui que le mot est écrit et qu’il reste à le couper : c’est vrai, et c’est très différent.",
  ),
  f(
    "ec-invar-12",
    "Les mots invariables",
    "Liste 12 · les petits mots venus de loin",
    [
      "Apprendre, puis dicter. Ces mots-là s’écrivent souvent dans les livres et se disent rarement à table : il faut les rencontrer pour les connaître.",
      "Pour chacun, donne un synonyme courant : malgré, c’est « même si » ; hormis, c’est « sauf » ; certes, c’est « c’est vrai ». Le sens d’abord, l’orthographe ensuite.",
      "On peut couper la liste en deux séances de cinq si dix d’un coup fait trop.",
    ],
    [
      "hélas — un accent aigu, et un s final. Dictée : Hélas, la fête a été annulée.",
      "malgré — un accent aigu sur le e final. Dictée : Il est sorti malgré la pluie.",
      "parmi — jamais de s à la fin, contrairement à « après ». Dictée : Une carte traînait parmi les papiers.",
      "selon — se termine par -on. Dictée : Selon la météo, il gèlera cette nuit.",
      "sauf — se termine par un f. Dictée : Tout le monde est là, sauf Lucien.",
      "hormis — un s final, et le mot « mis » caché dedans. Dictée : Rien n’a bougé, hormis la pendule.",
      "voici — un seul mot, de « vois » et « ici ». Dictée : Voici la liste des courses.",
      "voilà — un seul mot, avec un accent grave. Dictée : Voilà le chemin qu’il faut prendre.",
      "soudain — se termine par -ain, comme « demain ». Dictée : Soudain, la lumière s’est éteinte.",
      "certes — un s final, et un e avant. Dictée : Certes, il a raison sur ce point.",
    ],
    undefined,
    "L’absence de s à « parmi » est le seul vrai piège : après deux mois de listes où tout finit par un s, il va sûrement en poser un. C’est la preuve qu’il a retenu les listes précédentes. Regarde aussi s’il connaît le sens des dix mots à la fin de la séance — pour cette liste-là, comprendre vaut plus qu’écrire.",
  ),
  f(
    "ec-invar-13",
    "Les mots invariables",
    "Liste 13 · les mots savants de la liaison",
    [
      "Apprendre, puis dicter. Ce sont les mots de l’écrit soigné : ceux qu’on trouve dans un documentaire, une lettre, un article.",
      "Quatre d’entre eux veulent dire à peu près la même chose : cependant, pourtant, néanmoins, toutefois. Fais-les-lui classer du plus courant au plus rare, puis écrivez-les à la suite.",
      "Il peut en choisir deux à réutiliser dans son prochain texte. C’est la seule façon de les faire entrer pour de bon.",
    ],
    [
      "cependant — un seul mot, avec « pendant » dedans. Dictée : Il était fatigué ; cependant il a fini.",
      "pourtant — un seul mot, avec « tant » dedans. Dictée : Il avait pourtant promis de venir.",
      "néanmoins — un accent aigu, et un s final. Dictée : La route est longue, néanmoins nous partirons à pied.",
      "toutefois — un seul mot, avec « fois » à la fin. Dictée : Toutefois, rien n’est encore décidé.",
      "ainsi — pas de s final, contrairement à « après ». Dictée : Ainsi finit l’histoire du meunier.",
      "désormais — un accent aigu et un s final. Dictée : Désormais, la boulangerie ouvre le dimanche.",
      "auparavant — un seul mot, quatre syllabes. Dictée : Il avait vécu à Nantes auparavant.",
      "davantage — un seul mot, à ne pas couper. Dictée : Il faudrait davantage de lumière ici.",
      "notamment — deux m, et un a avant. Dictée : Les oiseaux, notamment les mésanges, reviennent.",
      "surtout — un seul mot, avec « tout » à la fin. Dictée : Surtout, n’oublie pas la clé.",
    ],
    undefined,
    "Ces mots-là entrent dans l’écriture avant d’entrer dans l’orthographe. Si tu en vois un apparaître dans une production d’écrit cette semaine, même mal écrit, c’est gagné et il faut le lui dire. Pour la graphie, regarde « notamment » et ses deux m, qui est le seul mot vraiment retors de la liste.",
  ),
  f(
    "ec-invar-14",
    "Les mots invariables",
    "Liste 14 · les mots qui ouvrent une circonstance",
    [
      "Apprendre, puis dicter. Ceux-ci annoncent toujours une suite : on ne dit jamais « lorsque » tout seul.",
      "Après chaque mot appris, demande-lui de finir la phrase à l’oral : « lorsque le train… ». Il entend alors à quoi sert le mot.",
      "Quatre sont en deux morceaux : tandis que, afin que, bien que, pendant que. La deuxième partie est toujours « que », et elle ne se colle pas.",
    ],
    [
      "lorsque — un seul mot, qui veut dire « quand ». Dictée : Lorsque la cloche sonne, tout le monde sort.",
      "puisque — un seul mot, un s au milieu. Dictée : Puisque tu es là, aide-moi à porter ça.",
      "quoique — un seul mot : il veut dire « bien que ». Dictée : Quoique fatigué, il a terminé son dessin.",
      "tandis que — deux mots, et un s muet à « tandis ». Dictée : Il lisait tandis que la soupe chauffait.",
      "afin que — deux mots, avec « fin » dedans. Dictée : Baisse la voix afin que le petit dorme.",
      "bien que — deux mots, jamais collés. Dictée : Bien que le ciel soit gris, on sortira.",
      "pendant que — deux mots, et -ant à la fin du premier. Dictée : Range ta chambre pendant que j’étends le linge.",
      "dès que — deux mots, avec un accent grave sur le premier. Dictée : Dès que la pluie cesse, on part.",
      "pour que — deux mots, comme « afin que ». Dictée : J’ai laissé la porte ouverte pour que le chat rentre.",
      "jusqu’à — une apostrophe et un accent grave. Dictée : Il a marché jusqu’à la grande route.",
    ],
    undefined,
    "L’apostrophe de « jusqu’à » est le point le plus fin de la liste : « jusqu’a » sans accent, ou « jusqua » d’un bloc, sont deux erreurs très différentes — la première dit qu’il connaît l’apostrophe, la deuxième qu’il ne l’a pas encore vue. Regarde aussi si le « que » reste détaché : c’est une découpe, pas une orthographe.",
  ),
  f(
    "ec-invar-15",
    "Les mots invariables",
    "Liste 15 · dire son doute, dire sa certitude",
    [
      "Apprendre, puis dicter. Ces dix mots servent tous à dire à quel point on est sûr de ce qu’on avance.",
      "Range-les avec lui sur une échelle, à l’oral, du moins sûr au plus sûr : probablement, sans doute, assurément. Il y aura des désaccords, tant mieux.",
      "Neuf d’entre eux finissent par -ment : la règle de l’adjectif féminin marche encore, sauf pour « sans doute ».",
    ],
    [
      "sans doute — deux mots, et pas de s à « doute ». Dictée : Il a sans doute laissé son écharpe au parc.",
      "probablement — de « probable ». Dictée : La route sera probablement fermée demain.",
      "assurément — de « assurée », et le e devient é. Dictée : C’est assurément le plus vieil arbre du village.",
      "effectivement — de « effective », deux f. Dictée : Le colis est effectivement arrivé ce matin.",
      "justement — de « juste ». Dictée : J’allais justement t’en parler.",
      "précisément — de « précise », et le e devient é. Dictée : Il est arrivé précisément à sept heures.",
      "forcément — de « forcée », même transformation. Dictée : Ce n’est pas forcément une bonne idée.",
      "éventuellement — de « éventuelle », deux l. Dictée : On passera éventuellement chez le voisin.",
      "apparemment — deux p, deux m, et un a au milieu. Dictée : Apparemment, le portail était ouvert.",
      "naturellement — de « naturelle », deux l. Dictée : Naturellement, il a voulu goûter le premier.",
    ],
    undefined,
    "La transformation du e en é — assurée donne assurément, précise donne précisément — est-elle vue comme une famille, ou comme trois mots sans lien ? La réponse se voit au troisième mot. Et « apparemment » n’obéit pas : il annonce la liste du prochain jour, on peut le lui dire, ça met de l’ordre dans ce qui vient.",
  ),
  f(
    "ec-invar-16",
    "Les mots invariables",
    "Liste 16 · les mots en -amment et en -emment",
    [
      "Apprendre, puis dicter. La liste la plus difficile de l’année, et elle a une clé : les deux fins se prononcent pareil, « -aman ».",
      "La clé : si l’adjectif finit par -ant, on écrit -amment (constant, constamment) ; s’il finit par -ent, on écrit -emment (prudent, prudemment). Cherchez l’adjectif ensemble avant chaque mot.",
      "On dicte cinq mots aujourd’hui si dix font trop. Cette liste peut se donner en deux fois sans rien perdre.",
    ],
    [
      "prudemment — de « prudent », donc -emment. Dictée : Il a traversé prudemment la grande rue.",
      "patiemment — de « patient », donc -emment. Dictée : Elle a attendu patiemment son tour.",
      "fréquemment — de « fréquent », donc -emment. Dictée : Le bus passe fréquemment le matin.",
      "récemment — de « récent », donc -emment. Dictée : Le pont a été repeint récemment.",
      "différemment — de « différent », donc -emment. Dictée : Chacun raconte l’histoire différemment.",
      "suffisamment — de « suffisant », donc -amment. Dictée : Il y a suffisamment de chaises.",
      "couramment — de « courant », donc -amment. Dictée : Sa tante parle couramment l’italien.",
      "brillamment — de « brillant », donc -amment. Dictée : Il s’est tiré d’affaire brillamment.",
      "constamment — de « constant », donc -amment. Dictée : La porte grince constamment.",
      "élégamment — de « élégant », donc -amment. Dictée : Elle s’est habillée élégamment pour le mariage.",
    ],
    undefined,
    "Est-ce qu’il cherche l’adjectif avant d’écrire, ou est-ce qu’il devine ? C’est la seule chose à observer aujourd’hui : la méthode, pas la graphie. Un mot juste trouvé par hasard vaut moins qu’un mot faux trouvé par la règle, parce que la règle, elle, resservira dix fois. Note aussi que les deux m sont toujours là, dans les deux cas : ça, c’est déjà acquis ou non, et ça se voit d’un coup d’œil.",
  ),
  f(
    "ec-invar-17",
    "Les mots invariables",
    "Liste 17 · ceux qui s’écrivent de deux façons",
    [
      "Aujourd’hui, on n’apprend pas dix mots : on apprend dix couples. Chaque phrase de dictée contient les deux formes, et il faut choisir laquelle va où.",
      "Pour chaque couple, donne le truc de remplacement : « quand » se remplace par « lorsque » ; « quant à » par « pour ce qui est de ». Si le remplacement marche, la forme est la bonne.",
      "On dicte lentement, phrase par phrase, et on corrige après chaque phrase — pas à la fin. Ici, chaque phrase est un problème à elle seule.",
    ],
    [
      "quand / quant à — « quand » se remplace par « lorsque ». Dictée : Quand il rentrera, on verra ; quant à moi, j’attends ici.",
      "près / prêt — « près » dit la distance, « prêt » veut dire préparé. Dictée : Il est tout près du but et il est prêt à partir.",
      "plutôt / plus tôt — « plutôt » veut dire « de préférence », « plus tôt » se remplace par « moins tard ». Dictée : Viens plutôt le matin, ou plus tôt que la dernière fois.",
      "peu / peux — « peu » dit une quantité, « peux » vient du verbe pouvoir. Dictée : Je peux t’en donner un peu.",
      "sans / s’en — « sans » veut dire « privé de », « s’en » se remplace par « il se… de cela ». Dictée : Il est parti sans rien dire et il s’en est voulu.",
      "davantage / d’avantage — « davantage » veut dire « plus » ; « d’avantage » contient le nom avantage. Dictée : Il en faudrait davantage, il n’y a pas d’avantage à attendre.",
      "quoique / quoi que — « quoique » se remplace par « bien que », « quoi que » par « quelle que soit la chose que ». Dictée : Quoique fatigué, il finira, quoi que tu en dises.",
      "aussitôt / aussi tôt — « aussitôt » veut dire « tout de suite » ; « aussi tôt » se compare à « aussi tard ». Dictée : Il est arrivé aussitôt, mais pas aussi tôt que prévu.",
      "parce que / par ce que — « parce que » donne la cause ; « par ce que » veut dire « par la chose que ». Dictée : Il est resté parce qu’il était ému par ce qu’il avait vu.",
      "bientôt / bien tôt — « bientôt » veut dire « dans peu de temps » ; « bien tôt » veut dire « très tôt ». Dictée : Il arrivera bientôt, et même bien tôt pour un dimanche.",
    ],
    undefined,
    "Le remplacement, encore : essaie-t-il vraiment de dire « lorsque » dans sa tête, ou tranche-t-il au son ? Demande-lui de justifier deux choix à voix haute, pas dix. Si un seul couple est bien tenu aujourd’hui, c’est un couple de plus qu’hier, et les neuf autres ont toute l’année prochaine devant eux.",
  ),
  f(
    "ec-invar-18",
    "Les mots invariables",
    "Liste 18 · les dix qui résistent",
    [
      "La dernière liste de l’année. Ce sont dix mots déjà vus, choisis parce qu’ils reviennent partout et qu’ils se défont facilement.",
      "On ne réapprend pas : on dicte directement, puis on ne reprend que ceux qui ont bougé. Le temps gagné va à autre chose.",
      "S’il veut, il écrit lui-même les dix mots sur une bande de papier à coller dans son cahier pour l’an prochain. C’est son aide-mémoire, pas le tien.",
    ],
    [
      "aujourd’hui — apostrophe au milieu, un seul mot. Dictée : Aujourd’hui, on range le grenier.",
      "beaucoup — un p muet à la fin. Dictée : Il a beaucoup plu cette semaine.",
      "peut-être — un trait d’union, un t à « peut ». Dictée : Il viendra peut-être en vélo.",
      "longtemps — un s final, « temps » caché dedans. Dictée : Ils ont marché longtemps sans parler.",
      "exprès — accent grave et s final. Dictée : Il a fait ce détour exprès.",
      "plutôt — circonflexe sur le o. Dictée : Prends plutôt la petite scie.",
      "davantage — un seul mot, sans apostrophe. Dictée : Il en faudrait davantage pour finir le mur.",
      "néanmoins — accent aigu, s final. Dictée : Le temps est couvert ; néanmoins nous partirons.",
      "quelquefois — un seul mot, « fois » à la fin. Dictée : Quelquefois, le renard traverse le pré.",
      "aussitôt — circonflexe sur le o, comme « plutôt ». Dictée : Aussitôt rentrés, ils ont allumé le feu.",
    ],
    undefined,
    "Compare, pour toi seul, avec la première liste, celle de décembre : ce qui a changé n’est pas le nombre de mots justes, c’est la façon dont il s’y prend — il cherche la famille, il pense à la lettre finale, il se relit. Note les deux ou trois mots qui résistent encore : ce sont ceux qu’on collera dans son cahier, et il n’y a aucune raison qu’ils ne cèdent pas un jour.",
  ),
];

/* ------------------------------------------------------------------ */
/* Transformer des phrases — quinze séries de cinq                     */
/* ------------------------------------------------------------------ */

const TRANSFORMER: Fiche[] = [
  f(
    "ec-transf-01",
    "Transformer des phrases",
    "Série 1 · au pluriel, un mot à la fois",
    [
      "Consigne du jour : mettre les cinq phrases au pluriel. Il les copie transformées sur son cahier, une par ligne.",
      "Avant d’écrire chaque phrase, il la dit au pluriel à voix haute. L’oreille attrape le verbe avant que la main s’y perde.",
      "On corrige phrase par phrase, pas à la fin. Une phrase juste, on passe ; une phrase qui coince, on la refait tout de suite.",
    ],
    [
      "Le chat dort sur le mur.",
      "La fleur pousse dans le pot.",
      "Le camion passe devant l’école.",
      "L’oiseau chante au matin.",
      "La porte grince un peu.",
    ],
    [
      "Les chats dorment sur le mur.",
      "Les fleurs poussent dans le pot.",
      "Les camions passent devant l’école.",
      "Les oiseaux chantent au matin.",
      "Les portes grincent un peu.",
    ],
    "Le nom prend son s tout seul ; c’est le verbe qui reste en arrière. Si « les chats dort » apparaît, ce n’est pas l’accord qui manque, c’est le lien entre le sujet et le verbe : on refait à voix haute la question « qui est-ce qui dort ? » avant d’écrire, et ça se remet en place. Regarde aussi le x d’« oiseaux », qui arrive sans prévenir.",
  ),
  f(
    "ec-transf-02",
    "Transformer des phrases",
    "Série 2 · au pluriel, le déterminant change aussi",
    [
      "Même consigne : les cinq phrases au pluriel, à l’écrit.",
      "Ici, le petit mot devant le nom change lui aussi : mon devient mes, ce devient ces, une devient des. On le lui dit avant, ce n’est pas une devinette.",
      "S’il bloque sur le verbe « être », rappelle-lui la paire : il est, ils sont. C’est la seule chose à savoir aujourd’hui.",
    ],
    [
      "Mon crayon est cassé.",
      "Ce livre me plaît.",
      "Ta chaussure est sale.",
      "Une branche touche la fenêtre.",
      "Son cahier reste ouvert.",
    ],
    [
      "Mes crayons sont cassés.",
      "Ces livres me plaisent.",
      "Tes chaussures sont sales.",
      "Des branches touchent la fenêtre.",
      "Ses cahiers restent ouverts.",
    ],
    "Trois choses bougent dans chaque phrase, et il en oublie souvent une — presque toujours la dernière. Demande-lui de relire en pointant du doigt : le petit mot, le nom, le verbe. Regarde si « cassés » et « ouverts » prennent leur s : ce sont des mots qui décrivent le sujet, et c’est la première fois de l’année qu’ils doivent suivre.",
  ),
  f(
    "ec-transf-03",
    "Transformer des phrases",
    "Série 3 · au pluriel, l’adjectif suit",
    [
      "Cinq phrases au pluriel. Aujourd’hui, chaque phrase contient un ou deux adjectifs collés au nom.",
      "La règle tient en une phrase : tout ce qui parle du nom prend la marque du nom. On peut le lui faire dire avec ses mots.",
      "Il souligne d’abord au crayon tous les mots qui vont devoir changer, puis il écrit. Ce repérage vaut la moitié du travail.",
    ],
    [
      "Le petit chien noir aboie.",
      "La grande table ronde est vide.",
      "Un mur gris entoure le pré.",
      "La rue étroite monte vers l’église.",
      "Le bol bleu est ébréché.",
    ],
    [
      "Les petits chiens noirs aboient.",
      "Les grandes tables rondes sont vides.",
      "Des murs gris entourent le pré.",
      "Les rues étroites montent vers l’église.",
      "Les bols bleus sont ébréchés.",
    ],
    "L’adjectif placé avant le nom (petit, grande) est plus souvent oublié que celui placé après (noir, ronde) — c’est très courant et ça n’a rien d’inquiétant. « Gris » ne bouge pas, parce qu’il a déjà son s : s’il en ajoute un deuxième, il applique bien la règle, il lui manque juste de regarder le mot avant. Dis-le-lui dans cet ordre-là.",
  ),
  f(
    "ec-transf-04",
    "Transformer des phrases",
    "Série 4 · au pluriel, les noms en -eau, -eu, -ou",
    [
      "Cinq phrases au pluriel. Le point du jour : certains noms prennent un x et non un s.",
      "-eau et -eu prennent un x ; -ou prend un s, sauf sept mots qu’on verra une autre fois. On le dit une fois, et on écrit.",
      "Fais-lui dire le pluriel à voix haute avant d’écrire : à l’oreille, x et s se ressemblent, donc c’est vraiment l’œil qui décide.",
    ],
    [
      "Le bateau rentre au port.",
      "Le cheveu est resté sur la brosse.",
      "Le hibou crie dans le noir.",
      "Le clou tient la planche.",
      "Le neveu arrive dimanche.",
    ],
    [
      "Les bateaux rentrent au port.",
      "Les cheveux sont restés sur la brosse.",
      "Les hiboux crient dans le noir.",
      "Les clous tiennent la planche.",
      "Les neveux arrivent dimanche.",
    ],
    "« Hibou » et « clou » se ressemblent et ne font pas le même pluriel : c’est la difficulté réelle de la séance, et se tromper là est normal. Ce qui compte, c’est de voir s’il se pose la question — s’il hésite une seconde devant « clou », il a compris qu’il y avait un choix à faire, et c’est le principal. Regarde aussi « sont restés », dont le s final vient du sujet.",
  ),
  f(
    "ec-transf-05",
    "Transformer des phrases",
    "Série 5 · au pluriel, les noms en -al et en -ail",
    [
      "Cinq phrases au pluriel. Aujourd’hui, la fin du mot change vraiment : journal donne journaux.",
      "Beaucoup de noms en -al donnent -aux, mais pas tous : bal, carnaval et festival gardent leur s. Ils sont dans la série exprès.",
      "Il peut écrire les cinq pluriels tout seuls dans la marge avant de recopier les phrases entières. Deux passages valent mieux qu’un seul trop chargé.",
    ],
    [
      "Le journal traîne sur le banc.",
      "Le cheval broute au fond du pré.",
      "Le vitrail éclaire la nef.",
      "Le bal finira tard.",
      "Le détail a son importance.",
    ],
    [
      "Les journaux traînent sur le banc.",
      "Les chevaux broutent au fond du pré.",
      "Les vitraux éclairent la nef.",
      "Les bals finiront tard.",
      "Les détails ont leur importance.",
    ],
    "« Les bals » est la phrase piège, et elle est là pour qu’il se trompe sans conséquence : s’il écrit « les baux », c’est qu’il applique la règle, et une règle appliquée trop loin est meilleur signe qu’une règle absente. La cinquième phrase demande deux changements à la fois — le verbe et le possessif — et c’est le vrai travail de la série.",
  ),
  f(
    "ec-transf-06",
    "Transformer des phrases",
    "Série 6 · au pluriel, les noms qui ne bougent pas",
    [
      "Cinq phrases au pluriel. Surprise du jour : certains noms s’écrivent déjà pareil au singulier et au pluriel.",
      "Un nom qui finit par s, x ou z ne change pas. Tout le reste de la phrase change quand même — c’est là que ça se joue.",
      "On corrige à voix haute en nommant ce qui a bougé dans chaque phrase. Parfois, c’est tout sauf le nom.",
    ],
    [
      "Le bras me fait mal.",
      "La noix est tombée.",
      "Le prix est affiché.",
      "Le tapis est roulé dans un coin.",
      "Le nez du chien est froid.",
    ],
    [
      "Les bras me font mal.",
      "Les noix sont tombées.",
      "Les prix sont affichés.",
      "Les tapis sont roulés dans un coin.",
      "Les nez des chiens sont froids.",
    ],
    "Le réflexe d’ajouter un s est tellement installé qu’un « brass » ou un « prixs » ne serait pas surprenant : c’est l’habitude qui parle, pas l’inattention. Ce qu’on regarde vraiment, c’est si le reste de la phrase suit malgré tout — le déterminant, le verbe, le mot qui décrit. La dernière phrase change deux noms : elle est la plus longue à traiter.",
  ),
  f(
    "ec-transf-07",
    "Transformer des phrases",
    "Série 7 · au pluriel, les verbes qui changent beaucoup",
    [
      "Cinq phrases au pluriel. Les verbes de cette série ne se contentent pas d’un -nt : ils changent de forme.",
      "Va, vont. Prend, prennent. Peut, peuvent. Fait, font. Dis-les-lui par paires avant de commencer, c’est plus rapide qu’une explication.",
      "Ces quatre verbes servent tous les jours : le temps passé ici est du temps gagné sur toute l’année.",
    ],
    [
      "Elle va au marché le jeudi.",
      "Il prend le train de sept heures.",
      "Le garçon peut venir dimanche.",
      "Ma sœur fait du vélo le samedi.",
      "Cet arbre perd ses feuilles.",
    ],
    [
      "Elles vont au marché le jeudi.",
      "Ils prennent le train de sept heures.",
      "Les garçons peuvent venir dimanche.",
      "Mes sœurs font du vélo le samedi.",
      "Ces arbres perdent leurs feuilles.",
    ],
    "Un « ils vas » ou un « ils prendent » n’est pas une faute d’inattention : c’est une règle bien apprise appliquée à un verbe qui n’y obéit pas, et c’est exactement ce qu’un enfant de cet âge doit faire avant de retenir les exceptions. Note lesquels des quatre verbes résistent : il y en a rarement plus d’un, et c’est celui-là qu’on remettra dans les séries suivantes.",
  ),
  f(
    "ec-transf-08",
    "Transformer des phrases",
    "Série 8 · au pluriel, quand « des » devient « de »",
    [
      "Cinq phrases au pluriel. Une finesse aujourd’hui, et une seule : quand un adjectif se place avant le nom, « des » devient « de ».",
      "Un gros caillou donne « de gros cailloux », pas « des gros cailloux ». À l’oral on dit souvent « des » ; à l’écrit soigné, on écrit « de ».",
      "Dis-lui d’emblée que les deux s’entendent dans la rue et que celle qu’on écrit ici est la forme soignée. Ce n’est pas une question de vrai ou de faux.",
    ],
    [
      "Il a ramassé un gros caillou.",
      "Une belle photo est accrochée au mur.",
      "Un long couloir mène à la cour.",
      "Le vent a cassé une jeune branche.",
      "Une petite lampe éclaire l’entrée.",
    ],
    [
      "Il a ramassé de gros cailloux.",
      "De belles photos sont accrochées au mur.",
      "De longs couloirs mènent à la cour.",
      "Le vent a cassé de jeunes branches.",
      "De petites lampes éclairent l’entrée.",
    ],
    "S’il écrit « des » partout, la phrase reste juste et comprise : c’est une nuance d’écrit soigné, et il faut le lui dire avant de corriger, sinon il croira avoir tout manqué. Ce qu’on regarde réellement, c’est la chaîne derrière : l’adjectif et le nom prennent-ils bien leur marque, et le verbe suit-il ? La deuxième phrase en demande quatre d’affilée.",
  ),
  f(
    "ec-transf-09",
    "Transformer des phrases",
    "Série 9 · au féminin, le nom et ce qui le suit",
    [
      "Aujourd’hui, ce n’est pas le pluriel : c’est le féminin. Même travail, autre chaîne. Dis-le en commençant, sinon il partira sur l’habitude.",
      "Cinq phrases à mettre au féminin, à l’écrit. Tout ce qui parle du nom change avec lui, y compris le petit mot devant.",
      "Les métiers changent de plusieurs façons : -er devient -ère, -eur devient -euse ou -rice. On les regarde ensemble avant, on ne les devine pas.",
    ],
    [
      "Le boulanger est content.",
      "Mon cousin est infirmier.",
      "Le chanteur est nerveux.",
      "Cet acteur est italien.",
      "Le directeur est nouveau ici.",
    ],
    [
      "La boulangère est contente.",
      "Ma cousine est infirmière.",
      "La chanteuse est nerveuse.",
      "Cette actrice est italienne.",
      "La directrice est nouvelle ici.",
    ],
    "Le nom change plus volontiers que le mot qui le décrit : « la boulangère est content » est la forme la plus fréquente, et elle montre qu’il a fait la moitié du chemin. Regarde les doublements — italien donne italienne avec deux n — et le cas de « nouveau », qui devient « nouvelle » et ne ressemble plus à rien. Celui-là s’apprend, il ne se déduit pas.",
  ),
  f(
    "ec-transf-10",
    "Transformer des phrases",
    "Série 10 · au féminin, quand le mot change tout à fait",
    [
      "Cinq phrases au féminin. Cette fois, certains mots changent complètement : frère devient sœur, roi devient reine.",
      "Fais deux colonnes au brouillon avant d’écrire : à gauche les mots masculins de la série, à droite leur féminin. Puis il recopie les phrases.",
      "Les accents comptent ici : discret donne discrète, avec un accent grave. C’est le genre de détail qu’on montre du doigt plutôt qu’on explique.",
    ],
    [
      "Mon frère est un bon cavalier.",
      "Le roi a nommé un ambassadeur.",
      "Ce garçon est un grand bavard.",
      "Le vieux monsieur est veuf.",
      "Mon oncle est un homme discret.",
    ],
    [
      "Ma sœur est une bonne cavalière.",
      "La reine a nommé une ambassadrice.",
      "Cette fille est une grande bavarde.",
      "La vieille dame est veuve.",
      "Ma tante est une femme discrète.",
    ],
    "Les mots qui changent entièrement ne s’inventent pas : s’il les cherche et ne les trouve pas, c’est un manque de vocabulaire, pas de grammaire, et on les lui donne sans détour. Ce qui se regarde vraiment, c’est ce qui suit derrière : « bon » devient « bonne » avec deux n, « veuf » devient « veuve » avec un v. Ces transformations-là, elles, s’apprennent par familles.",
  ),
  f(
    "ec-transf-11",
    "Transformer des phrases",
    "Série 11 · à la forme négative",
    [
      "Nouvelle transformation : les cinq phrases passent à la forme négative. Toujours à l’écrit, une phrase par ligne.",
      "La négation a deux morceaux : ne et pas, qui encadrent le verbe. Devant une voyelle, ne devient n’.",
      "Piège du jour, et il vaut le détour : après une négation, du, de la, des deviennent de. « Il mange de la soupe » donne « il ne mange pas de soupe ».",
    ],
    [
      "Il mange de la soupe.",
      "Elle a trouvé ses clés.",
      "Nous irons à la piscine samedi.",
      "Tu as encore du pain.",
      "Quelqu’un a frappé à la porte.",
    ],
    [
      "Il ne mange pas de soupe.",
      "Elle n’a pas trouvé ses clés.",
      "Nous n’irons pas à la piscine samedi.",
      "Tu n’as plus de pain.",
      "Personne n’a frappé à la porte.",
    ],
    "Le « ne » est le morceau qui disparaît, parce qu’on ne le dit presque jamais en parlant : « il mange pas de soupe » est du français oral correct, et c’est la version écrite qu’on installe ici. Dis-lui la différence plutôt que de barrer. Regarde ensuite si « de la » devient « de » : c’est la marque que la négation a agi sur toute la phrase et pas seulement sur le verbe.",
  ),
  f(
    "ec-transf-12",
    "Transformer des phrases",
    "Série 12 · à la forme négative, les cas retors",
    [
      "Cinq phrases à la forme négative. Chacune a sa propre négation : pas, rien, jamais, pas encore.",
      "Le contraire de « quelque chose » est « rien » ; celui de « toujours » est « jamais » ; celui de « déjà » est « pas encore ». On cherche le contraire avant d’écrire la phrase.",
      "La dernière phrase déplace les pronoms. Fais-la à l’oral d’abord, tous les deux, et écris-la seulement quand elle sonne juste.",
    ],
    [
      "Il voit quelque chose dans le noir.",
      "Elle va toujours au marché le jeudi.",
      "Prends ton manteau.",
      "Il a déjà rangé sa chambre.",
      "Donne-le-moi.",
    ],
    [
      "Il ne voit rien dans le noir.",
      "Elle ne va jamais au marché le jeudi.",
      "Ne prends pas ton manteau.",
      "Il n’a pas encore rangé sa chambre.",
      "Ne me le donne pas.",
    ],
    "La cinquième phrase est la plus difficile de toute la série de l’année : les pronoms passent devant le verbe et changent d’ordre. Si elle vient à l’oral et coince à l’écrit, elle est acquise — c’est la main qui suit, pas la tête. Regarde aussi les traits d’union qui disparaissent : « donne-le-moi » en a deux, « ne me le donne pas » n’en a aucun, et ça ne s’explique bien qu’en montrant les deux phrases côte à côte.",
  ),
  f(
    "ec-transf-13",
    "Transformer des phrases",
    "Série 13 · au pluriel, avec le passé composé",
    [
      "Cinq phrases au pluriel, toutes au passé composé avec l’auxiliaire être.",
      "Avec être, la fin du participe suit le sujet : il est tombé, ils sont tombés, elles sont tombées. On le dit une fois, on le montre sur la première phrase, et on écrit.",
      "La dernière phrase est pronominale et demande un accord en plus, sur « toutes seules ». Elle peut se faire ensemble si elle résiste.",
    ],
    [
      "Le rideau est tombé pendant la nuit.",
      "Ma cousine est partie très tôt.",
      "L’invité est arrivé avant l’heure.",
      "Le vase est resté sur la cheminée.",
      "La porte s’est refermée toute seule.",
    ],
    [
      "Les rideaux sont tombés pendant la nuit.",
      "Mes cousines sont parties très tôt.",
      "Les invités sont arrivés avant l’heure.",
      "Les vases sont restés sur la cheminée.",
      "Les portes se sont refermées toutes seules.",
    ],
    "Deux marques sont à poser dans chaque phrase : celle de l’auxiliaire, qui s’entend, et celle du participe, qui ne s’entend pas. Presque toujours, la première tient et la seconde manque — c’est logique, l’oreille ne peut pas aider. S’il pose les deux au moins une fois dans la série, la règle est en train de s’installer, et il faut le lui dire ce jour-là.",
  ),
  f(
    "ec-transf-14",
    "Transformer des phrases",
    "Série 14 · au pluriel, la chaîne entière",
    [
      "Cinq phrases au pluriel, les plus longues de l’année. Chacune contient plusieurs propositions, et la marque doit voyager jusqu’au bout.",
      "Avant d’écrire, il surligne tous les mots qui devront changer. Il y en a entre quatre et six par phrase. Ce repérage compte autant que l’écriture.",
      "La quatrième phrase cache une règle nouvelle : le participe s’accorde avec ce qui est placé avant lui. Donne-la, ne la fais pas deviner.",
    ],
    [
      "Mon voisin range son vélo, puis il ferme le garage.",
      "Cette fille a perdu son écharpe ; elle la cherche partout.",
      "Le chien qui aboie appartient au facteur.",
      "L’élève que j’ai vu hier est nouveau dans la classe.",
      "Quand il a fini son travail, mon frère sort jouer.",
    ],
    [
      "Mes voisins rangent leurs vélos, puis ils ferment le garage.",
      "Ces filles ont perdu leurs écharpes ; elles les cherchent partout.",
      "Les chiens qui aboient appartiennent au facteur.",
      "Les élèves que j’ai vus hier sont nouveaux dans la classe.",
      "Quand ils ont fini leur travail, mes frères sortent jouer.",
    ],
    "La marque tient-elle jusqu’à la fin de la phrase, ou s’essouffle-t-elle après la virgule ? C’est la seule question du jour, et la réponse se lit d’un coup d’œil sur le cahier. La troisième phrase demande d’accorder un verbe caché dans « qui aboie » : si celui-là passe, la notion de sujet est solide. Et pour la quatrième, s’il écrit « vus » après l’avoir entendue une fois, c’est du travail de CM2 qui arrive en avance.",
  ),
  f(
    "ec-transf-15",
    "Transformer des phrases",
    "Série 15 · deux transformations d’un coup",
    [
      "Dernière série de l’année : chaque phrase passe au féminin ET au pluriel. Deux chaînes en même temps.",
      "On procède en deux étapes, au brouillon : d’abord le féminin singulier, puis le pluriel. Faire les deux d’un coup est possible, mais rien n’oblige à l’essayer.",
      "Si deux phrases sur cinq sont menées jusqu’au bout, la séance a fait son travail. On s’arrête à l’heure, pas à la cinquième ligne.",
    ],
    [
      "Le nouveau maître est arrivé lundi.",
      "Ce garçon est un joueur régulier.",
      "Mon grand-père est vieux, mais il est très actif.",
      "Le lecteur attentif aura remarqué le détail.",
      "Un boulanger inquiet a fermé sa boutique.",
    ],
    [
      "Les nouvelles maîtresses sont arrivées lundi.",
      "Ces filles sont des joueuses régulières.",
      "Mes grands-mères sont vieilles, mais elles sont très actives.",
      "Les lectrices attentives auront remarqué le détail.",
      "Des boulangères inquiètes ont fermé leur boutique.",
    ],
    "Sors la première série, celle de décembre, et pose-la à côté, sans commentaire : « le chat dort sur le mur » d’un côté, ces phrases-ci de l’autre. C’est la même personne qui a fait les deux, à six mois d’écart, et ça se voit. Pour la suite, note seulement quelles chaînes s’arrêtent en route — le participe, l’adjectif, le possessif. Ce sont trois points de départ pour l’an prochain, et ils sont déjà à moitié faits.",
  ),
];

export const ecritureCopie: Fiche[] = [...COPIE, ...INVARIABLES, ...TRANSFORMER];
