/**
 * Pour chaque exercice, la partie du cours qui l'explique — celle que la
 * correction lui propose de rouvrir, qu'il ait juste ou faux, et que les
 * parents lisent sous ce qui n'est pas passé.
 *
 * La partie est désignée par son **titre**, et `""` désigne le début d'une
 * leçon, qui n'en a pas. Pas par son rang : une relecture qui insère ou
 * déplace une partie ne doit pas envoyer l'enfant relire le mauvais morceau
 * en silence. Un titre retouché, un exercice ajouté sans sa ligne ou une
 * ligne orpheline font échouer `programme.test.ts`.
 *
 * Rattachés le 23 septembre 2026 en lisant, pour chaque exercice, la
 * correction et le cours : la partie retenue est celle qu'un enfant qui s'est
 * trompé devrait relire — la méthode ou la règle que la correction applique.
 * Comme le reste du manuel, rien de tout ceci n'a été relu par un enseignant.
 */
export const PASSAGES: Record<string, string> = {
  /* m-p1-nombres — Les nombres jusqu’à 9 999 */
  "m-p1-nb-1": "Chaque place a un nom, et une valeur",
  "m-p1-nb-2": "Chaque place a un nom, et une valeur",
  "m-p1-nb-3": "« Chiffre des » et « nombre de » : deux choses différentes",
  "m-p1-nb-4": "« Chiffre des » et « nombre de » : deux choses différentes",
  "m-p1-nb-5": "Chaque place a un nom, et une valeur",
  "m-p1-nb-6": "Chaque place a un nom, et une valeur",
  "m-p1-nb-7": "Décomposer, c’est comprendre",
  "m-p1-nb-8": "Décomposer, c’est comprendre",
  "m-p1-nb-r2": "Chaque place a un nom, et une valeur",
  "m-p1-nb-r1": "Chaque place a un nom, et une valeur",
  "m-p1-nb-r3": "« Chiffre des » et « nombre de » : deux choses différentes",
  "m-p1-nb-r4": "« Chiffre des » et « nombre de » : deux choses différentes",
  "m-p1-nb-r5": "Chaque place a un nom, et une valeur",
  "m-p1-nb-r6": "Chaque place a un nom, et une valeur",
  "m-p1-nb-r7": "Décomposer, c’est comprendre",
  "m-p1-nb-r8": "Décomposer, c’est comprendre",
  /* m-p1-comparer — Comparer, ranger et encadrer */
  "m-p1-cmp-1": "La méthode",
  "m-p1-cmp-2": "La méthode",
  "m-p1-cmp-3": "Ranger",
  "m-p1-cmp-4": "Ranger",
  "m-p1-cmp-5": "La méthode",
  "m-p1-cmp-6": "Encadrer, et la demi-droite graduée",
  "m-p1-cmp-7": "Encadrer, et la demi-droite graduée",
  "m-p1-cmp-8": "Encadrer, et la demi-droite graduée",
  "m-p1-cmp-r1": "La méthode",
  "m-p1-cmp-r2": "La méthode",
  "m-p1-cmp-r3": "Ranger",
  "m-p1-cmp-r4": "Ranger",
  "m-p1-cmp-r5": "La méthode",
  "m-p1-cmp-r6": "Encadrer, et la demi-droite graduée",
  "m-p1-cmp-r7": "Encadrer, et la demi-droite graduée",
  "m-p1-cmp-r8": "Encadrer, et la demi-droite graduée",
  /* m-p1-fractions — Les fractions : partager en parts égales */
  "m-p1-fr-1": "Les deux nombres, et ce qu’ils disent",
  "m-p1-fr-2": "Plus petit ou plus grand que 1 ?",
  "m-p1-fr-3": "Plus petit ou plus grand que 1 ?",
  "m-p1-fr-4": "Comparer deux fractions",
  "m-p1-fr-5": "Comparer deux fractions",
  "m-p1-fr-6": "Les deux nombres, et ce qu’ils disent",
  "m-p1-fr-7": "Les deux nombres, et ce qu’ils disent",
  "m-p1-fr-8": "Les deux nombres, et ce qu’ils disent",
  "m-p1-fr-r1": "Les deux nombres, et ce qu’ils disent",
  "m-p1-fr-r2": "Plus petit ou plus grand que 1 ?",
  "m-p1-fr-r3": "Plus petit ou plus grand que 1 ?",
  "m-p1-fr-r4": "Comparer deux fractions",
  "m-p1-fr-r5": "Comparer deux fractions",
  "m-p1-fr-r6": "Les deux nombres, et ce qu’ils disent",
  "m-p1-fr-r7": "Les deux nombres, et ce qu’ils disent",
  "m-p1-fr-r8": "Les deux nombres, et ce qu’ils disent",
  /* m-p1-fraction-quantite — La fraction d’une quantité */
  "m-p1-fq-1": "Une part : on divise",
  "m-p1-fq-2": "Une part : on divise",
  "m-p1-fq-3": "Une part : on divise",
  "m-p1-fq-4": "Plusieurs parts : on divise, puis on multiplie",
  "m-p1-fq-5": "Plusieurs parts : on divise, puis on multiplie",
  "m-p1-fq-6": "Une part : on divise",
  "m-p1-fq-7": "Une part : on divise",
  "m-p1-fq-8": "Plusieurs parts : on divise, puis on multiplie",
  "m-p1-fq-r1": "Une part : on divise",
  "m-p1-fq-r2": "Une part : on divise",
  "m-p1-fq-r3": "Une part : on divise",
  "m-p1-fq-r4": "Plusieurs parts : on divise, puis on multiplie",
  "m-p1-fq-r5": "Plusieurs parts : on divise, puis on multiplie",
  "m-p1-fq-r6": "Une part : on divise",
  "m-p1-fq-r7": "Une part : on divise",
  "m-p1-fq-r8": "Plusieurs parts : on divise, puis on multiplie",
  /* m-p1-addition-soustraction — Additionner et soustraire en colonnes */
  "m-p1-as-1": "Estimer avant, vérifier après",
  "m-p1-as-2": "Estimer avant, vérifier après",
  "m-p1-as-3": "Aligner les rangs, pas les bords",
  "m-p1-as-4": "La retenue dans la soustraction",
  "m-p1-as-5": "La retenue dans la soustraction",
  "m-p1-as-6": "La retenue dans la soustraction",
  "m-p1-as-7": "Et parfois, ne pas poser du tout",
  "m-p1-as-8": "Et parfois, ne pas poser du tout",
  "m-p1-as-r1": "Estimer avant, vérifier après",
  "m-p1-as-r2": "Estimer avant, vérifier après",
  "m-p1-as-r3": "Aligner les rangs, pas les bords",
  "m-p1-as-r4": "La retenue dans la soustraction",
  "m-p1-as-r5": "La retenue dans la soustraction",
  "m-p1-as-r6": "La retenue dans la soustraction",
  "m-p1-as-r7": "Et parfois, ne pas poser du tout",
  "m-p1-as-r8": "Et parfois, ne pas poser du tout",
  /* m-p1-problemes — Les problèmes : comprendre avant de calculer */
  "m-p1-pb-1": "2. Modéliser",
  "m-p1-pb-2": "2. Modéliser",
  "m-p1-pb-3": "2. Modéliser",
  "m-p1-pb-4": "1. Comprendre",
  "m-p1-pb-5": "1. Comprendre",
  "m-p1-pb-6": "2. Modéliser",
  "m-p1-pb-7": "2. Modéliser",
  "m-p1-pb-8": "4. Répondre — et se relire",
  "m-p1-pb-r1": "2. Modéliser",
  "m-p1-pb-r2": "2. Modéliser",
  "m-p1-pb-r3": "2. Modéliser",
  "m-p1-pb-r4": "1. Comprendre",
  "m-p1-pb-r5": "1. Comprendre",
  "m-p1-pb-r6": "2. Modéliser",
  "m-p1-pb-r7": "2. Modéliser",
  "m-p1-pb-r8": "4. Répondre — et se relire",
  /* m-p2-fractions-sup — Les fractions plus grandes que 1 */
  "m-p2-fs-1": "Écrire une fraction comme un entier plus un reste",
  "m-p2-fs-2": "Écrire une fraction comme un entier plus un reste",
  "m-p2-fs-3": "Écrire une fraction comme un entier plus un reste",
  "m-p2-fs-4": "Et dans l’autre sens",
  "m-p2-fs-5": "Encadrer et placer",
  "m-p2-fs-6": "Écrire une fraction comme un entier plus un reste",
  "m-p2-fs-7": "Écrire une fraction comme un entier plus un reste",
  "m-p2-fs-8": "Encadrer et placer",
  /* m-p2-fractions-calcul — Additionner et soustraire des fractions */
  "m-p2-fc-1": "Même dénominateur : on additionne les parts",
  "m-p2-fc-2": "Même dénominateur : on additionne les parts",
  "m-p2-fc-3": "Même dénominateur : on additionne les parts",
  "m-p2-fc-4": "Même dénominateur : on additionne les parts",
  "m-p2-fc-5": "Quelques égalités à connaître par cœur",
  "m-p2-fc-6": "Même dénominateur : on additionne les parts",
  "m-p2-fc-7": "Même dénominateur : on additionne les parts",
  "m-p2-fc-8": "Même dénominateur : on additionne les parts",
  /* m-p2-fractions-decimales — Les dixièmes et les centièmes */
  "m-p2-fd-1": "Couper l’unité en dix, puis en cent",
  "m-p2-fd-2": "Couper l’unité en dix, puis en cent",
  "m-p2-fd-3": "Couper l’unité en dix, puis en cent",
  "m-p2-fd-4": "Passer des dixièmes aux centièmes",
  "m-p2-fd-5": "Passer des dixièmes aux centièmes",
  "m-p2-fd-6": "Lire et écrire",
  "m-p2-fd-7": "Couper l’unité en dix, puis en cent",
  "m-p2-fd-8": "Lire et écrire",
  /* m-p2-multiplication — Poser une multiplication */
  "m-p2-mu-1": "Pourquoi ça marche",
  "m-p2-mu-2": "Pourquoi ça marche",
  "m-p2-mu-3": "Le zéro au milieu",
  "m-p2-mu-4": "Les raccourcis, qui ne sont pas de la triche",
  "m-p2-mu-5": "Les raccourcis, qui ne sont pas de la triche",
  "m-p2-mu-6": "Les raccourcis, qui ne sont pas de la triche",
  "m-p2-mu-7": "Pourquoi ça marche",
  "m-p2-mu-8": "Pourquoi ça marche",
  /* m-p2-multiples — Les multiples et les diviseurs */
  "m-p2-ml-1": "Trois reconnaissances immédiates",
  "m-p2-ml-2": "Trois reconnaissances immédiates",
  "m-p2-ml-3": "Trois reconnaissances immédiates",
  "m-p2-ml-4": "Pour les autres, on divise",
  "m-p2-ml-5": "Pour les autres, on divise",
  "m-p2-ml-6": "Pour les autres, on divise",
  "m-p2-ml-7": "",
  "m-p2-ml-8": "Trois reconnaissances immédiates",
  /* m-p2-longueurs — Les longueurs, du millimètre au kilomètre */
  "m-p2-lg-1": "Les unités, et la seule chose à retenir",
  "m-p2-lg-2": "Les unités, et la seule chose à retenir",
  "m-p2-lg-3": "Convertir en raisonnant",
  "m-p2-lg-4": "Les unités, et la seule chose à retenir",
  "m-p2-lg-5": "Convertir en raisonnant",
  "m-p2-lg-6": "Choisir l’unité, et estimer",
  "m-p2-lg-7": "Les unités, et la seule chose à retenir",
  "m-p2-lg-8": "Convertir en raisonnant",
  /* m-p3-grands-nombres — Les grands nombres jusqu’à 999 999 */
  "m-p3-gn-1": "Les zéros ne sont pas facultatifs",
  "m-p3-gn-2": "Les zéros ne sont pas facultatifs",
  "m-p3-gn-3": "Par paquets de trois",
  "m-p3-gn-4": "Le nombre de milliers",
  "m-p3-gn-5": "Le nombre de milliers",
  "m-p3-gn-6": "Les zéros ne sont pas facultatifs",
  "m-p3-gn-7": "Par paquets de trois",
  "m-p3-gn-8": "Par paquets de trois",
  /* m-p3-virgule — L’écriture à virgule */
  "m-p3-vg-1": "La virgule est un raccourci",
  "m-p3-vg-2": "La virgule est un raccourci",
  "m-p3-vg-3": "La virgule est un raccourci",
  "m-p3-vg-4": "L’erreur à ne pas faire",
  "m-p3-vg-5": "Partie entière et arrondi",
  "m-p3-vg-6": "Partie entière et arrondi",
  "m-p3-vg-7": "La virgule est un raccourci",
  "m-p3-vg-8": "La virgule est un raccourci",
  /* m-p3-comparer-decimaux — Comparer et ranger les nombres décimaux */
  "m-p3-cd-1": "La confusion la plus fréquente",
  "m-p3-cd-2": "La méthode sûre",
  "m-p3-cd-3": "La méthode sûre",
  "m-p3-cd-4": "Intercaler",
  "m-p3-cd-5": "Intercaler",
  "m-p3-cd-6": "Intercaler",
  "m-p3-cd-7": "La méthode sûre",
  "m-p3-cd-8": "La confusion la plus fréquente",
  /* m-p3-division — La division posée */
  "m-p3-dv-1": "Poser, chiffre par chiffre",
  "m-p3-dv-2": "Poser, chiffre par chiffre",
  "m-p3-dv-3": "Poser, chiffre par chiffre",
  "m-p3-dv-4": "Poser, chiffre par chiffre",
  "m-p3-dv-5": "Poser, chiffre par chiffre",
  "m-p3-dv-6": "Partager, ou grouper",
  "m-p3-dv-7": "Partager, ou grouper",
  "m-p3-dv-8": "Partager, ou grouper",
  /* m-p3-masses-contenances — Les masses et les contenances */
  "m-p3-mc-1": "Les masses",
  "m-p3-mc-2": "Les masses",
  "m-p3-mc-3": "Les masses",
  "m-p3-mc-4": "Les contenances",
  "m-p3-mc-5": "Les contenances",
  "m-p3-mc-6": "Estimer, pour se relire",
  "m-p3-mc-7": "Les contenances",
  "m-p3-mc-8": "Les masses",
  /* m-p3-perimetre — Le périmètre */
  "m-p3-pe-1": "Les règles qu’on peut trouver soi-même",
  "m-p3-pe-2": "On additionne les côtés",
  "m-p3-pe-3": "On additionne les côtés",
  "m-p3-pe-4": "Dans l’autre sens",
  "m-p3-pe-5": "On additionne les côtés",
  "m-p3-pe-6": "Les règles qu’on peut trouver soi-même",
  "m-p3-pe-7": "On additionne les côtés",
  "m-p3-pe-8": "Dans l’autre sens",
  /* m-p4-aires — Les aires */
  "m-p4-ai-1": "La règle qu’on peut découvrir",
  "m-p4-ai-2": "La règle qu’on peut découvrir",
  "m-p4-ai-3": "Compter des carreaux",
  "m-p4-ai-4": "Deux figures, deux mesures",
  "m-p4-ai-5": "Deux figures, deux mesures",
  "m-p4-ai-6": "La règle qu’on peut découvrir",
  "m-p4-ai-7": "Deux figures, deux mesures",
  "m-p4-ai-8": "La règle qu’on peut découvrir",
  /* m-p4-angles — Les angles */
  "m-p4-an-1": "L’angle droit, et les autres",
  "m-p4-an-2": "Dans les figures",
  "m-p4-an-3": "L’angle droit, et les autres",
  "m-p4-an-4": "L’angle droit, et les autres",
  "m-p4-an-5": "Dans les figures",
  "m-p4-an-6": "L’angle droit, et les autres",
  "m-p4-an-7": "",
  "m-p4-an-8": "Comparer sans mesurer",
  /* m-p4-durees — L’heure et les durées */
  "m-p4-du-1": "Ce qu’il faut savoir sans réfléchir",
  "m-p4-du-2": "Ce qu’il faut savoir sans réfléchir",
  "m-p4-du-3": "La méthode du chemin",
  "m-p4-du-4": "La méthode du chemin",
  "m-p4-du-5": "Convertir",
  "m-p4-du-6": "Convertir",
  "m-p4-du-7": "La méthode du chemin",
  "m-p4-du-8": "Convertir",
  /* m-p4-proportionnalite — La proportionnalité */
  "m-p4-pr-1": "La phrase qui résout presque tout",
  "m-p4-pr-2": "La phrase qui résout presque tout",
  "m-p4-pr-3": "La phrase qui résout presque tout",
  "m-p4-pr-4": "La phrase qui résout presque tout",
  "m-p4-pr-5": "Et quand le lien n’est pas rond",
  "m-p4-pr-6": "La phrase qui résout presque tout",
  "m-p4-pr-7": "Attention : tout n’est pas proportionnel",
  "m-p4-pr-8": "Et quand le lien n’est pas rond",
  /* m-p4-calcul-mental — Le calcul mental : les chemins courts */
  "m-p4-cm-1": "Ajouter 9, 19, 29",
  "m-p4-cm-2": "Ajouter 9, 19, 29",
  "m-p4-cm-3": "Multiplier par 4, par 8, par 5",
  "m-p4-cm-4": "Multiplier par 4, par 8, par 5",
  "m-p4-cm-5": "Multiplier par 4, par 8, par 5",
  "m-p4-cm-6": "Découper un facteur",
  "m-p4-cm-7": "Découper un facteur",
  "m-p4-cm-8": "Multiplier par 4, par 8, par 5",
  /* m-p4-donnees — Les tableaux et les graphiques */
  "m-p4-do-1": "Lire un diagramme en barres",
  "m-p4-do-2": "Lire un diagramme en barres",
  "m-p4-do-3": "Lire un diagramme en barres",
  "m-p4-do-4": "Lire un tableau à double entrée",
  "m-p4-do-5": "Lire un diagramme en barres",
  "m-p4-do-6": "Lire un diagramme en barres",
  "m-p4-do-7": "Lire une courbe",
  "m-p4-do-8": "Lire un diagramme en barres",
  /* m-p5-figures — Les figures et leurs propriétés */
  "m-p5-fi-1": "Les triangles",
  "m-p5-fi-2": "Les triangles",
  "m-p5-fi-3": "Les quadrilatères",
  "m-p5-fi-4": "Les quadrilatères",
  "m-p5-fi-5": "Les quadrilatères",
  "m-p5-fi-6": "Le cercle et le disque",
  "m-p5-fi-7": "Le cercle et le disque",
  "m-p5-fi-8": "Les quadrilatères",
  /* m-p5-perpendiculaires — Perpendiculaires et parallèles */
  "m-p5-pp-1": "Perpendiculaires",
  "m-p5-pp-2": "Parallèles",
  "m-p5-pp-3": "Perpendiculaires",
  "m-p5-pp-4": "Parallèles",
  "m-p5-pp-5": "Une remarque utile",
  "m-p5-pp-6": "Les outils, et à quoi ils servent",
  "m-p5-pp-7": "Parallèles",
  "m-p5-pp-8": "Les outils, et à quoi ils servent",
  /* m-p5-symetrie — La symétrie axiale */
  "m-p5-sy-1": "Combien d’axes ?",
  "m-p5-sy-2": "Combien d’axes ?",
  "m-p5-sy-3": "Combien d’axes ?",
  "m-p5-sy-4": "Autour de nous",
  "m-p5-sy-5": "Combien d’axes ?",
  "m-p5-sy-6": "Construire le symétrique sur du quadrillage",
  "m-p5-sy-7": "Construire le symétrique sur du quadrillage",
  "m-p5-sy-8": "Autour de nous",
  /* m-p5-solides — Les solides */
  "m-p5-so-1": "Trois mots pour décrire",
  "m-p5-so-2": "Trois mots pour décrire",
  "m-p5-so-3": "Trois mots pour décrire",
  "m-p5-so-4": "Les solides à connaître",
  "m-p5-so-5": "Les solides à connaître",
  "m-p5-so-6": "Les solides à connaître",
  "m-p5-so-7": "Le patron",
  "m-p5-so-8": "Les solides à connaître",
  /* m-p5-nombre-cache — Le nombre caché */
  "m-p5-nc-1": "Trouver un nombre caché",
  "m-p5-nc-2": "Trouver un nombre caché",
  "m-p5-nc-3": "Le signe = veut dire « autant que »",
  "m-p5-nc-4": "Le signe = veut dire « autant que »",
  "m-p5-nc-5": "Un programme de calcul",
  "m-p5-nc-6": "Continuer une suite",
  "m-p5-nc-7": "Continuer une suite",
  "m-p5-nc-8": "Un programme de calcul",
  /* m-p5-hasard — Le hasard : certain, possible, impossible */
  "m-p5-ha-1": "Trois mots à ne pas confondre",
  "m-p5-ha-2": "Trois mots à ne pas confondre",
  "m-p5-ha-3": "Lister toutes les issues",
  "m-p5-ha-4": "Lister toutes les issues",
  "m-p5-ha-5": "Lister toutes les issues",
  "m-p5-ha-6": "Attention aux deux issues",
  "m-p5-ha-7": "Trois mots à ne pas confondre",
  "m-p5-ha-8": "Attention aux deux issues",
  /* f-p1-verbe-sujet — Trouver le verbe et le sujet */
  "f-p1-vs-1": "Le verbe d’abord, et un test qui ne trompe pas",
  "f-p1-vs-2": "Puis le sujet",
  "f-p1-vs-3": "Trois sortes de sujets",
  "f-p1-vs-4": "Le verbe d’abord, et un test qui ne trompe pas",
  "f-p1-vs-5": "Le verbe d’abord, et un test qui ne trompe pas",
  "f-p1-vs-6": "Puis le sujet",
  "f-p1-vs-7": "Trois sortes de sujets",
  "f-p1-vs-8": "Puis le sujet",
  "f-p1-vs-r1": "Le verbe d’abord, et un test qui ne trompe pas",
  "f-p1-vs-r2": "Puis le sujet",
  "f-p1-vs-r3": "Trois sortes de sujets",
  "f-p1-vs-r4": "Le verbe d’abord, et un test qui ne trompe pas",
  "f-p1-vs-r5": "Le verbe d’abord, et un test qui ne trompe pas",
  "f-p1-vs-r6": "Puis le sujet",
  "f-p1-vs-r7": "Trois sortes de sujets",
  "f-p1-vs-r8": "Puis le sujet",
  /* f-p1-natures — La nature des mots */
  "f-p1-na-1": "Les familles à connaître",
  "f-p1-na-2": "Les familles à connaître",
  "f-p1-na-3": "Deux détails qui servent",
  "f-p1-na-4": "Les familles à connaître",
  "f-p1-na-5": "Comment trancher en cas de doute",
  "f-p1-na-6": "Les familles à connaître",
  "f-p1-na-7": "",
  "f-p1-na-8": "Deux détails qui servent",
  "f-p1-na-r1": "Les familles à connaître",
  "f-p1-na-r2": "Les familles à connaître",
  "f-p1-na-r3": "Les familles à connaître",
  "f-p1-na-r4": "Deux détails qui servent",
  "f-p1-na-r5": "Comment trancher en cas de doute",
  "f-p1-na-r6": "Les familles à connaître",
  "f-p1-na-r7": "",
  "f-p1-na-r8": "Deux détails qui servent",
  /* f-p1-types-phrases — Les types et les formes de phrases */
  "f-p1-tp-1": "Les trois types",
  "f-p1-tp-2": "Les trois types",
  "f-p1-tp-3": "Les formes : négative et exclamative",
  "f-p1-tp-4": "Les formes : négative et exclamative",
  "f-p1-tp-5": "Poser une question : trois façons",
  "f-p1-tp-6": "Les formes : négative et exclamative",
  "f-p1-tp-7": "Poser une question : trois façons",
  "f-p1-tp-8": "Les formes : négative et exclamative",
  "f-p1-tp-r1": "Les trois types",
  "f-p1-tp-r2": "Les trois types",
  "f-p1-tp-r3": "Les formes : négative et exclamative",
  "f-p1-tp-r4": "Les formes : négative et exclamative",
  "f-p1-tp-r5": "Poser une question : trois façons",
  "f-p1-tp-r6": "Les formes : négative et exclamative",
  "f-p1-tp-r7": "Poser une question : trois façons",
  "f-p1-tp-r8": "Les formes : négative et exclamative",
  /* f-p1-groupe-nominal — Le groupe du nom et ses accords */
  "f-p1-gn-1": "Les marques",
  "f-p1-gn-2": "Les marques",
  "f-p1-gn-3": "Les marques",
  "f-p1-gn-4": "Le noyau commande",
  "f-p1-gn-5": "Quand un nom en complète un autre",
  "f-p1-gn-6": "Les marques",
  "f-p1-gn-7": "Le noyau commande",
  "f-p1-gn-8": "Les marques",
  "f-p1-gn-r1": "Les marques",
  "f-p1-gn-r2": "Les marques",
  "f-p1-gn-r3": "Les marques",
  "f-p1-gn-r4": "Le noyau commande",
  "f-p1-gn-r5": "Quand un nom en complète un autre",
  "f-p1-gn-r6": "Les marques",
  "f-p1-gn-r7": "Le noyau commande",
  "f-p1-gn-r8": "Les marques",
  /* f-p1-present — Le présent de l’indicatif */
  "f-p1-pr-1": "Ce qui demande le plus d’attention",
  "f-p1-pr-2": "Ce qui demande le plus d’attention",
  "f-p1-pr-3": "Les huit irréguliers, au présent",
  "f-p1-pr-4": "Les huit irréguliers, au présent",
  "f-p1-pr-5": "Ce qui demande le plus d’attention",
  "f-p1-pr-6": "Les huit irréguliers, au présent",
  "f-p1-pr-7": "Les trois groupes",
  "f-p1-pr-8": "Les trois groupes",
  "f-p1-pr-r1": "Ce qui demande le plus d’attention",
  "f-p1-pr-r2": "Ce qui demande le plus d’attention",
  "f-p1-pr-r3": "Les huit irréguliers, au présent",
  "f-p1-pr-r4": "Les huit irréguliers, au présent",
  "f-p1-pr-r5": "Ce qui demande le plus d’attention",
  "f-p1-pr-r6": "Les huit irréguliers, au présent",
  "f-p1-pr-r7": "Les trois groupes",
  "f-p1-pr-r8": "Les trois groupes",
  /* f-p1-familles — Les familles de mots */
  "f-p1-fa-1": "La forme du mot : le radical",
  "f-p1-fa-2": "Les préfixes, devant",
  "f-p1-fa-3": "Les préfixes, devant",
  "f-p1-fa-4": "Les suffixes, derrière",
  "f-p1-fa-5": "La forme du mot : le radical",
  "f-p1-fa-6": "Les préfixes, devant",
  "f-p1-fa-7": "La forme du mot : le radical",
  "f-p1-fa-8": "Les suffixes, derrière",
  "f-p1-fa-r1": "La forme du mot : le radical",
  "f-p1-fa-r2": "Les préfixes, devant",
  "f-p1-fa-r3": "Les préfixes, devant",
  "f-p1-fa-r4": "Les suffixes, derrière",
  "f-p1-fa-r5": "La forme du mot : le radical",
  "f-p1-fa-r6": "Les préfixes, devant",
  "f-p1-fa-r7": "La forme du mot : le radical",
  "f-p1-fa-r8": "Les suffixes, derrière",
  /* f-p2-imparfait — L’imparfait */
  "f-p2-im-1": "Trois détails d’orthographe",
  "f-p2-im-2": "Une bonne nouvelle",
  "f-p2-im-3": "Une bonne nouvelle",
  "f-p2-im-4": "La seule vraie exception",
  "f-p2-im-5": "Une bonne nouvelle",
  "f-p2-im-6": "Une bonne nouvelle",
  "f-p2-im-7": "Une bonne nouvelle",
  "f-p2-im-8": "Une bonne nouvelle",
  /* f-p2-futur — Le futur */
  "f-p2-fu-1": "Le -r- est la marque du futur",
  "f-p2-fu-2": "Les irréguliers, qui gardent quand même leur r",
  "f-p2-fu-3": "Les irréguliers, qui gardent quand même leur r",
  "f-p2-fu-4": "Les irréguliers, qui gardent quand même leur r",
  "f-p2-fu-5": "Les irréguliers, qui gardent quand même leur r",
  "f-p2-fu-6": "Le -r- est la marque du futur",
  "f-p2-fu-7": "Ne pas confondre avec le conditionnel",
  "f-p2-fu-8": "Le -r- est la marque du futur",
  /* f-p2-passe-compose — Le passé composé */
  "f-p2-pc-1": "Composé, parce qu’il a deux morceaux",
  "f-p2-pc-2": "Le participe passé",
  "f-p2-pc-3": "Le participe passé",
  "f-p2-pc-4": "Le participe passé",
  "f-p2-pc-5": "L’accord avec être",
  "f-p2-pc-6": "L’accord avec être",
  "f-p2-pc-7": "La négation",
  "f-p2-pc-8": "Le participe passé",
  /* f-p2-complements — Les compléments : objet ou circonstanciel */
  "f-p2-co-1": "Le test du déplacement et de la suppression",
  "f-p2-co-2": "Direct ou indirect",
  "f-p2-co-3": "Direct ou indirect",
  "f-p2-co-4": "Le test du déplacement et de la suppression",
  "f-p2-co-5": "Direct ou indirect",
  "f-p2-co-6": "Direct ou indirect",
  "f-p2-co-7": "Direct ou indirect",
  "f-p2-co-8": "Le test du déplacement et de la suppression",
  /* f-p2-homophones — Les mots qui se prononcent pareil */
  "f-p2-ho-1": "a ou à",
  "f-p2-ho-2": "a ou à",
  "f-p2-ho-3": "son ou sont",
  "f-p2-ho-4": "son ou sont",
  "f-p2-ho-5": "est ou et",
  "f-p2-ho-6": "est ou et",
  "f-p2-ho-7": "ont ou on",
  "f-p2-ho-8": "ont ou on",
  /* f-p2-comprendre — Comprendre un texte : l’explicite et l’implicite */
  "f-p2-cp-1": "L’explicite : c’est écrit",
  "f-p2-cp-2": "Une déduction se justifie",
  "f-p2-cp-3": "L’implicite : ce n’est pas écrit, mais ça se déduit",
  "f-p2-cp-4": "L’implicite : ce n’est pas écrit, mais ça se déduit",
  "f-p2-cp-5": "L’implicite : ce n’est pas écrit, mais ça se déduit",
  "f-p2-cp-6": "L’explicite : c’est écrit",
  "f-p2-cp-7": "L’implicite : ce n’est pas écrit, mais ça se déduit",
  "f-p2-cp-8": "Une déduction se justifie",
  /* f-p2-ecrire — Écrire un texte qui se tient */
  "f-p2-ec-1": "Le brouillon n’est pas une punition",
  "f-p2-ec-2": "Ce qui fait qu’un texte se tient",
  "f-p2-ec-3": "Ce qui fait qu’un texte se tient",
  "f-p2-ec-4": "Les reprises, pour ne pas répéter",
  "f-p2-ec-5": "Se relire, en trois passages",
  "f-p2-ec-6": "Se relire, en trois passages",
  "f-p2-ec-7": "Le brouillon n’est pas une punition",
  "f-p2-ec-8": "Ce qui fait qu’un texte se tient",
  /* f-p3-pronoms — Les pronoms personnels */
  "f-p3-pn-1": "Les pronoms sujets",
  "f-p3-pn-2": "Les pronoms compléments",
  "f-p3-pn-3": "Direct ou indirect, là aussi",
  "f-p3-pn-4": "Direct ou indirect, là aussi",
  "f-p3-pn-5": "Direct ou indirect, là aussi",
  "f-p3-pn-6": "Les pronoms compléments",
  "f-p3-pn-7": "Les pronoms sujets",
  "f-p3-pn-8": "Direct ou indirect, là aussi",
  /* f-p3-epithete — L’adjectif épithète */
  "f-p3-ep-1": "Comment le repérer",
  "f-p3-ep-2": "Comment le repérer",
  "f-p3-ep-3": "Comment le repérer",
  "f-p3-ep-4": "Comment le repérer",
  "f-p3-ep-5": "Enlever pour vérifier",
  "f-p3-ep-6": "Épithète : dans le groupe du nom",
  "f-p3-ep-7": "Comment le repérer",
  "f-p3-ep-8": "Épithète : dans le groupe du nom",
  /* f-p3-accord-sujet-verbe — L’accord du sujet et du verbe */
  "f-p3-av-1": "Le noyau commande, pas le mot le plus proche",
  "f-p3-av-2": "Le noyau commande, pas le mot le plus proche",
  "f-p3-av-3": "Quand le sujet n’est pas devant",
  "f-p3-av-4": "Plusieurs sujets",
  "f-p3-av-5": "Plusieurs sujets",
  "f-p3-av-6": "Plusieurs sujets",
  "f-p3-av-7": "Nom ou verbe : les mêmes lettres, pas la même règle",
  "f-p3-av-8": "Nom ou verbe : les mêmes lettres, pas la même règle",
  /* f-p3-synonymes — Synonymes et contraires */
  "f-p3-sy-1": "Les contraires",
  "f-p3-sy-2": "Les contraires",
  "f-p3-sy-3": "Les synonymes",
  "f-p3-sy-4": "Les contraires",
  "f-p3-sy-5": "Les synonymes",
  "f-p3-sy-6": "Les synonymes",
  "f-p3-sy-7": "Les contraires",
  "f-p3-sy-8": "Les contraires",
  /* f-p3-dialogue — Le dialogue dans un récit */
  "f-p3-di-1": "Les signes",
  "f-p3-di-2": "Les signes",
  "f-p3-di-3": "Les signes",
  "f-p3-di-4": "Les verbes de parole",
  "f-p3-di-5": "Les verbes de parole",
  "f-p3-di-6": "Les verbes de parole",
  "f-p3-di-7": "Les verbes de parole",
  "f-p3-di-8": "Ce que le dialogue apporte au récit",
  /* f-p3-genres — Reconnaître un poème, une pièce, un récit */
  "f-p3-ge-1": "Le poème",
  "f-p3-ge-2": "Le théâtre",
  "f-p3-ge-3": "Le poème",
  "f-p3-ge-4": "Le poème",
  "f-p3-ge-5": "Le théâtre",
  "f-p3-ge-6": "Le poème",
  "f-p3-ge-7": "Le récit",
  "f-p3-ge-8": "Le théâtre",
  /* f-p4-radical — Les verbes qui changent de radical */
  "f-p4-rd-1": "Les verbes en -cer et -ger : garder le son",
  "f-p4-rd-2": "Les verbes en -cer et -ger : garder le son",
  "f-p4-rd-3": "Les verbes en -cer et -ger : garder le son",
  "f-p4-rd-4": "Les verbes en -yer",
  "f-p4-rd-5": "Les verbes en -eler et -eter",
  "f-p4-rd-6": "Les verbes en -eler et -eter",
  "f-p4-rd-7": "Les verbes en -eler et -eter",
  "f-p4-rd-8": "Le e muet et le é",
  /* f-p4-chaine — Transformer une phrase sans casser les accords */
  "f-p4-ch-1": "Une transformation entraîne les autres",
  "f-p4-ch-2": "Au pluriel, le verbe suit aussi",
  "f-p4-ch-3": "Une transformation entraîne les autres",
  "f-p4-ch-4": "Au pluriel, le verbe suit aussi",
  "f-p4-ch-5": "Au pluriel, le verbe suit aussi",
  "f-p4-ch-6": "Au pluriel, le verbe suit aussi",
  "f-p4-ch-7": "Au pluriel, le verbe suit aussi",
  "f-p4-ch-8": "La méthode : souligner d’abord",
  /* f-p4-polysemie — Les mots à plusieurs sens */
  "f-p4-po-1": "",
  "f-p4-po-2": "Le même mot, des sens différents",
  "f-p4-po-3": "Le mot spécialisé",
  "f-p4-po-4": "Le sens propre et le sens figuré",
  "f-p4-po-5": "Le sens propre et le sens figuré",
  "f-p4-po-6": "Le sens propre et le sens figuré",
  "f-p4-po-7": "Le même mot, des sens différents",
  "f-p4-po-8": "Le mot spécialisé",
  /* f-p4-heros — Qu’est-ce qu’un héros ? */
  "f-p4-he-1": "Ce qui fait un héros",
  "f-p4-he-2": "Ce qui fait un héros",
  "f-p4-he-3": "Les héros ont des faiblesses",
  "f-p4-he-4": "Les héros ont des faiblesses",
  "f-p4-he-5": "Des héroïnes",
  "f-p4-he-6": "Les héros ordinaires",
  "f-p4-he-7": "Les héros ont des faiblesses",
  "f-p4-he-8": "Ce qui fait un héros",
  /* f-p4-poesie — Le goût des mots : la poésie */
  "f-p4-pe-1": "Les sons",
  "f-p4-pe-2": "Les images",
  "f-p4-pe-3": "Les images",
  "f-p4-pe-4": "Jouer",
  "f-p4-pe-5": "Jouer",
  "f-p4-pe-6": "Les sons",
  "f-p4-pe-7": "Les sons",
  "f-p4-pe-8": "Les sons",
  /* f-p4-documents — Lire un document pour apprendre */
  "f-p4-dc-1": "Nature et source : les deux questions d’abord",
  "f-p4-dc-2": "Nature et source : les deux questions d’abord",
  "f-p4-dc-3": "Nature et source : les deux questions d’abord",
  "f-p4-dc-4": "Le document composite",
  "f-p4-dc-5": "Le document composite",
  "f-p4-dc-6": "Chercher, plutôt que tout lire",
  "f-p4-dc-7": "Le document composite",
  "f-p4-dc-8": "Chercher, plutôt que tout lire",
  /* f-p5-merveilleux — Le merveilleux et l’étrange */
  "f-p5-me-1": "Le merveilleux : personne ne s’étonne",
  "f-p5-me-2": "Le merveilleux : personne ne s’étonne",
  "f-p5-me-3": "L’étrange : quelque chose ne va pas",
  "f-p5-me-4": "L’étrange : quelque chose ne va pas",
  "f-p5-me-5": "Pourquoi ces récits existent",
  "f-p5-me-6": "Pourquoi ces récits existent",
  "f-p5-me-7": "Le merveilleux : personne ne s’étonne",
  "f-p5-me-8": "L’étrange : quelque chose ne va pas",
  /* f-p5-morale — La morale d’une histoire */
  "f-p5-mo-1": "Comment marche une fable",
  "f-p5-mo-2": "Comment marche une fable",
  "f-p5-mo-3": "Une morale peut se discuter",
  "f-p5-mo-4": "Une morale peut se discuter",
  "f-p5-mo-5": "Une morale peut se discuter",
  "f-p5-mo-6": "Une morale peut se discuter",
  "f-p5-mo-7": "Comment marche une fable",
  "f-p5-mo-8": "Justice, liberté, tolérance",
  /* f-p5-orthographe — L’orthographe des mots */
  "f-p5-or-1": "La famille renseigne",
  "f-p5-or-2": "La famille renseigne",
  "f-p5-or-3": "La famille renseigne",
  "f-p5-or-4": "Les mots invariables",
  "f-p5-or-5": "Les mots invariables",
  "f-p5-or-6": "Les mots invariables",
  "f-p5-or-7": "Les doubles consonnes",
  "f-p5-or-8": "La famille renseigne",
  /* f-p5-conjugaison-bilan — Les quatre temps : reconnaître et choisir */
  "f-p5-cb-1": "Reconnaître, par la terminaison",
  "f-p5-cb-2": "Reconnaître, par la terminaison",
  "f-p5-cb-3": "Reconnaître, par la terminaison",
  "f-p5-cb-4": "Choisir, selon ce qu’on raconte",
  "f-p5-cb-5": "Choisir, selon ce qu’on raconte",
  "f-p5-cb-6": "Reconnaître, par la terminaison",
  "f-p5-cb-7": "Reconnaître, par la terminaison",
  "f-p5-cb-8": "Reconnaître, par la terminaison",
  /* f-p5-expliquer — Expliquer et donner son avis */
  "f-p5-ex-1": "Trois morceaux",
  "f-p5-ex-2": "Les mots qui articulent",
  "f-p5-ex-3": "Les mots qui articulent",
  "f-p5-ex-4": "Les mots qui articulent",
  "f-p5-ex-5": "Trois morceaux",
  "f-p5-ex-6": "Les mots qui articulent",
  "f-p5-ex-7": "Expliquer une leçon avec ses mots",
  "f-p5-ex-8": "Trois morceaux",
  /* f-p5-ponctuation — La ponctuation et la lecture à voix haute */
  "f-p5-pt-1": "Chaque signe donne une instruction",
  "f-p5-pt-2": "Chaque signe donne une instruction",
  "f-p5-pt-3": "Une virgule change le sens",
  "f-p5-pt-4": "Chaque signe donne une instruction",
  "f-p5-pt-5": "Lire par groupes de sens",
  "f-p5-pt-6": "Lire par groupes de sens",
  "f-p5-pt-7": "Chaque signe donne une instruction",
  "f-p5-pt-8": "Une virgule change le sens",
  /* s-p1-masse — Mesurer une masse */
  "s-p1-ma-1": "Comparer, sans chiffres",
  "s-p1-ma-2": "Comparer, sans chiffres",
  "s-p1-ma-3": "La tare : peser ce qui coule",
  "s-p1-ma-4": "La tare : peser ce qui coule",
  "s-p1-ma-5": "Comparer, sans chiffres",
  "s-p1-ma-6": "La tare : peser ce qui coule",
  "s-p1-ma-7": "",
  "s-p1-ma-8": "Mesurer, avec une unité",
  "s-p1-ma-r1": "Comparer, sans chiffres",
  "s-p1-ma-r2": "Comparer, sans chiffres",
  "s-p1-ma-r3": "La tare : peser ce qui coule",
  "s-p1-ma-r4": "La tare : peser ce qui coule",
  "s-p1-ma-r5": "Comparer, sans chiffres",
  "s-p1-ma-r6": "La tare : peser ce qui coule",
  "s-p1-ma-r7": "",
  "s-p1-ma-r8": "Mesurer, avec une unité",
  /* s-p1-melanges — Les mélanges, et comment les séparer */
  "s-p1-me-1": "Homogène ou hétérogène",
  "s-p1-me-2": "Homogène ou hétérogène",
  "s-p1-me-3": "Trois façons de séparer",
  "s-p1-me-4": "Trois façons de séparer",
  "s-p1-me-5": "Trois façons de séparer",
  "s-p1-me-6": "Homogène ou hétérogène",
  "s-p1-me-7": "Trois façons de séparer",
  "s-p1-me-8": "Homogène ou hétérogène",
  "s-p1-me-r1": "Homogène ou hétérogène",
  "s-p1-me-r2": "Homogène ou hétérogène",
  "s-p1-me-r3": "Trois façons de séparer",
  "s-p1-me-r4": "Trois façons de séparer",
  "s-p1-me-r5": "Trois façons de séparer",
  "s-p1-me-r6": "Homogène ou hétérogène",
  "s-p1-me-r7": "Trois façons de séparer",
  "s-p1-me-r8": "Homogène ou hétérogène",
  /* s-p2-dissolution — Dissoudre, et la limite */
  "s-p2-di-1": "Dissoudre n’est pas disparaître",
  "s-p2-di-2": "Dissoudre n’est pas disparaître",
  "s-p2-di-3": "Le test du filtre",
  "s-p2-di-4": "Dissoudre n’est pas disparaître",
  "s-p2-di-5": "La saturation : il y a une limite",
  "s-p2-di-6": "La saturation : il y a une limite",
  "s-p2-di-7": "Le test du filtre",
  "s-p2-di-8": "La saturation : il y a une limite",
  /* s-p2-mouvement — Mesurer un déplacement */
  "s-p2-mv-1": "Mesurer une durée",
  "s-p2-mv-2": "Comparer deux déplacements",
  "s-p2-mv-3": "Refaire la mesure",
  "s-p2-mv-4": "Refaire la mesure",
  "s-p2-mv-5": "Comparer deux déplacements",
  "s-p2-mv-6": "Refaire la mesure",
  "s-p2-mv-7": "Mesurer une durée",
  "s-p2-mv-8": "Mesurer une distance",
  /* s-p2-objets — Comment marche un objet technique */
  "s-p2-ot-1": "Une fonction, plusieurs solutions",
  "s-p2-ot-2": "Le besoin, puis la fonction",
  "s-p2-ot-3": "Une fonction, plusieurs solutions",
  "s-p2-ot-4": "Le besoin, puis la fonction",
  "s-p2-ot-5": "Le croquis",
  "s-p2-ot-6": "Une fonction, plusieurs solutions",
  "s-p2-ot-7": "Des pièces qui travaillent ensemble",
  "s-p2-ot-8": "Le besoin, puis la fonction",
  /* s-p3-ombres — La lumière et les ombres */
  "s-p3-om-1": "",
  "s-p3-om-2": "Trois sortes de matériaux",
  "s-p3-om-3": "Trois sortes de matériaux",
  "s-p3-om-4": "Trois éléments, et rien d’autre",
  "s-p3-om-5": "La taille change, et on peut le prévoir",
  "s-p3-om-6": "La taille change, et on peut le prévoir",
  "s-p3-om-7": "Trois éléments, et rien d’autre",
  "s-p3-om-8": "Trois sortes de matériaux",
  /* s-p3-lune — Les phases de la Lune */
  "s-p3-lu-1": "La Lune ne brille pas",
  "s-p3-lu-2": "La Lune ne brille pas",
  "s-p3-lu-3": "Les quatre phases",
  "s-p3-lu-4": "Les quatre phases",
  "s-p3-lu-5": "Les quatre phases",
  "s-p3-lu-6": "Un mois",
  "s-p3-lu-7": "Les quatre phases",
  "s-p3-lu-8": "La Lune ne brille pas",
  /* s-p4-espece — Qu’est-ce qu’une espèce ? */
  "s-p4-es-1": "Une espèce, c’est une question de descendance",
  "s-p4-es-2": "Une espèce, c’est une question de descendance",
  "s-p4-es-3": "Classer par ce qu’on possède",
  "s-p4-es-4": "Classer par ce qu’on possède",
  "s-p4-es-5": "La clé de détermination",
  "s-p4-es-6": "Classer par ce qu’on possède",
  "s-p4-es-7": "Une espèce, c’est une question de descendance",
  "s-p4-es-8": "Classer par ce qu’on possède",
  /* s-p4-developpement — Comment grandissent les animaux */
  "s-p4-dv-1": "Deux façons de grandir",
  "s-p4-dv-2": "Deux façons de grandir",
  "s-p4-dv-3": "Deux façons de grandir",
  "s-p4-dv-4": "Où les œufs sont fécondés",
  "s-p4-dv-5": "Où les œufs sont fécondés",
  "s-p4-dv-6": "Beaucoup d’œufs, ou peu de petits",
  "s-p4-dv-7": "Sortir d’un œuf, ou du ventre de sa mère",
  "s-p4-dv-8": "Deux façons de grandir",
  /* s-p4-ecosystemes — Les écosystèmes et les chaînes alimentaires */
  "s-p4-ec-1": "",
  "s-p4-ec-2": "Qui mange qui",
  "s-p4-ec-3": "Qui mange qui",
  "s-p4-ec-4": "Un réseau, pas une ligne",
  "s-p4-ec-5": "Toucher à un maillon touche tout",
  "s-p4-ec-6": "Un réseau, pas une ligne",
  "s-p4-ec-7": "Qui mange qui",
  "s-p4-ec-8": "Qui mange qui",
  /* s-p5-meteo — La météo et les saisons */
  "s-p5-mt-1": "",
  "s-p5-mt-2": "Ce qu’on mesure, et avec quoi",
  "s-p5-mt-3": "Ce qu’on mesure, et avec quoi",
  "s-p5-mt-4": "Ce qu’on mesure, et avec quoi",
  "s-p5-mt-5": "Les saisons ne viennent pas de la distance",
  "s-p5-mt-6": "Les saisons ne viennent pas de la distance",
  "s-p5-mt-7": "Ce qu’on mesure, et avec quoi",
  "s-p5-mt-8": "Mesurer toujours pareil",
  /* s-p5-cerveau — Le cerveau et l’attention */
  "s-p5-ce-1": "",
  "s-p5-ce-2": "Le cerveau interprète, il ne photographie pas",
  "s-p5-ce-3": "Le cerveau interprète, il ne photographie pas",
  "s-p5-ce-4": "L’attention est limitée, et ça ne se décide pas",
  "s-p5-ce-5": "Ce qui aide vraiment",
  "s-p5-ce-6": "Ce qui aide vraiment",
  "s-p5-ce-7": "",
  "s-p5-ce-8": "Ce qui aide vraiment",
  /* s-p5-puberte — Grandir : les changements du corps */
  "s-p5-pu-1": "",
  "s-p5-pu-2": "Pas au même âge, et ce n’est pas une course",
  "s-p5-pu-3": "Ce qui change",
  "s-p5-pu-4": "Ce qui change",
  "s-p5-pu-5": "Pas au même âge, et ce n’est pas une course",
  "s-p5-pu-6": "Des questions, c’est normal",
  "s-p5-pu-7": "Pas au même âge, et ce n’est pas une course",
  "s-p5-pu-8": "Ce qui change",
  /* s-p5-programmation — Donner des instructions à une machine */
  "s-p5-pg-1": "Un algorithme est une suite d’étapes",
  "s-p5-pg-2": "Un algorithme est une suite d’étapes",
  "s-p5-pg-3": "Répéter, plutôt que recopier",
  "s-p5-pg-4": "La machine ne devine pas",
  "s-p5-pg-5": "Un algorithme est une suite d’étapes",
  "s-p5-pg-6": "Répéter, plutôt que recopier",
  "s-p5-pg-7": "Répéter, plutôt que recopier",
  "s-p5-pg-8": "Un algorithme est une suite d’étapes",
  /* h-p1-seigneurie — Le seigneur, le château et la seigneurie */
  "h-p1-se-1": "",
  "h-p1-se-2": "",
  "h-p1-se-3": "La seigneurie : un territoire et ses habitants",
  "h-p1-se-4": "La seigneurie : un territoire et ses habitants",
  "h-p1-se-5": "Le château : trois fonctions à la fois",
  "h-p1-se-6": "Le château : trois fonctions à la fois",
  "h-p1-se-r1": "",
  "h-p1-se-r2": "",
  "h-p1-se-r3": "La seigneurie : un territoire et ses habitants",
  "h-p1-se-r4": "La seigneurie : un territoire et ses habitants",
  "h-p1-se-r5": "Le château : trois fonctions à la fois",
  "h-p1-se-r6": "Le château : trois fonctions à la fois",
  /* h-p1-paysans — La vie des paysannes et des paysans */
  "h-p1-pa-1": "",
  "h-p1-pa-2": "Une année réglée par les saisons",
  "h-p1-pa-3": "Ce qu’ils doivent, et à qui",
  "h-p1-pa-4": "Ce qu’ils doivent, et à qui",
  "h-p1-pa-5": "Une année réglée par les saisons",
  "h-p1-pa-6": "Et dans les villes",
  "h-p1-pa-r1": "",
  "h-p1-pa-r2": "Une année réglée par les saisons",
  "h-p1-pa-r4": "Ce qu’ils doivent, et à qui",
  "h-p1-pa-r5": "Une année réglée par les saisons",
  "h-p1-pa-r3": "Ce qu’ils doivent, et à qui",
  "h-p1-pa-r6": "Et dans les villes",
  /* h-p2-eglise — L’Église, l’art roman et l’art gothique */
  "h-p2-eg-1": "Ce que l’Église fait, en plus du culte",
  "h-p2-eg-2": "Ce que l’Église fait, en plus du culte",
  "h-p2-eg-3": "L’art roman : lourd, sombre, solide",
  "h-p2-eg-4": "L’art gothique : haut, clair, élancé",
  "h-p2-eg-5": "L’art gothique : haut, clair, élancé",
  "h-p2-eg-6": "L’art roman : lourd, sombre, solide",
  /* h-p2-renaissance — François Ier et la Renaissance */
  "h-p2-re-1": "",
  "h-p2-re-2": "Un roi mécène",
  "h-p2-re-3": "Un roi mécène",
  "h-p2-re-4": "Ce qui change",
  "h-p2-re-5": "Ce qui change",
  "h-p2-re-6": "Un roi mécène",
  /* h-p3-henri-iv — Henri IV et les guerres de religion */
  "h-p3-hi-1": "Henri IV : changer de camp pour faire la paix",
  "h-p3-hi-2": "Deux façons d’être chrétien",
  "h-p3-hi-3": "Presque quarante ans de guerre",
  "h-p3-hi-4": "Henri IV : changer de camp pour faire la paix",
  "h-p3-hi-5": "Henri IV : changer de camp pour faire la paix",
  "h-p3-hi-6": "Presque quarante ans de guerre",
  /* h-p3-louis-xiv — Louis XIV, Versailles et la société d’ordres */
  "h-p3-lo-1": "",
  "h-p3-lo-2": "",
  "h-p3-lo-3": "Versailles, un outil de pouvoir",
  "h-p3-lo-4": "Trois ordres, et une réalité",
  "h-p3-lo-5": "Trois ordres, et une réalité",
  "h-p3-lo-6": "Les femmes à la Cour",
  /* h-p4-explorations — Les grandes explorations */
  "h-p4-ex-1": "Deux voyages qui changent la carte",
  "h-p4-ex-2": "Ce qui a rendu la traversée possible",
  "h-p4-ex-3": "Ce qui a rendu la traversée possible",
  "h-p4-ex-4": "Deux voyages qui changent la carte",
  "h-p4-ex-5": "Pourquoi partir",
  "h-p4-ex-6": "Deux voyages qui changent la carte",
  /* h-p4-colonisation — Les empires coloniaux et l’esclavage */
  "h-p4-co-1": "Des empires coloniaux",
  "h-p4-co-2": "Ce que les conquêtes font aux Amérindiens",
  "h-p4-co-3": "La traite et les plantations",
  "h-p4-co-4": "La traite et les plantations",
  "h-p4-co-5": "Ce que l’Europe en a tiré",
  "h-p4-co-6": "La traite et les plantations",
  /* h-p5-royaume-1789 — Le royaume en 1789 et les Lumières */
  "h-p5-ro-1": "L’État est ruiné",
  "h-p5-ro-2": "Les idées des Lumières",
  "h-p5-ro-3": "Les idées des Lumières",
  "h-p5-ro-4": "Les idées des Lumières",
  "h-p5-ro-5": "Les cahiers de doléances",
  "h-p5-ro-6": "Le peuple a faim",
  /* h-p5-revolution — 1789, l’année révolutionnaire */
  "h-p5-rv-1": "Le 14 juillet : la prise de la Bastille",
  "h-p5-rv-2": "La nuit du 4 août : la fin des privilèges",
  "h-p5-rv-3": "Le 26 août : la Déclaration des Droits de l’Homme et du Citoyen",
  "h-p5-rv-4": "Le 26 août : la Déclaration des Droits de l’Homme et du Citoyen",
  "h-p5-rv-5": "Les 5 et 6 octobre : la marche des femmes",
  "h-p5-rv-6": "Le 26 août : la Déclaration des Droits de l’Homme et du Citoyen",
  /* g-p1-se-nourrir — Comment se nourrit-on dans le monde ? */
  "g-p1-sn-1": "L’aliment de base change selon les régions",
  "g-p1-sn-2": "L’aliment de base change selon les régions",
  "g-p1-sn-3": "L’aliment de base change selon les régions",
  "g-p1-sn-4": "Ce qui se mesure : la ration alimentaire",
  "g-p1-sn-5": "Deux mots à ne pas confondre",
  "g-p1-sn-6": "Deux mots à ne pas confondre",
  "g-p1-sn-r1": "L’aliment de base change selon les régions",
  "g-p1-sn-r2": "L’aliment de base change selon les régions",
  "g-p1-sn-r3": "L’aliment de base change selon les régions",
  "g-p1-sn-r4": "Ce qui se mesure : la ration alimentaire",
  "g-p1-sn-r5": "Deux mots à ne pas confondre",
  "g-p1-sn-r6": "Deux mots à ne pas confondre",
  /* g-p1-produits — D’où vient ce qu’on mange ? */
  "g-p1-pr-1": "Agricole ou transformé",
  "g-p1-pr-2": "Agricole ou transformé",
  "g-p1-pr-3": "Lire une étiquette",
  "g-p1-pr-4": "Pourquoi ça vient de loin",
  "g-p1-pr-5": "Pourquoi ça vient de loin",
  "g-p1-pr-6": "Agricole ou transformé",
  "g-p1-pr-r2": "Agricole ou transformé",
  "g-p1-pr-r1": "Agricole ou transformé",
  "g-p1-pr-r3": "Lire une étiquette",
  "g-p1-pr-r4": "Pourquoi ça vient de loin",
  "g-p1-pr-r5": "Pourquoi ça vient de loin",
  "g-p1-pr-r6": "Agricole ou transformé",
  /* g-p2-chaine — La chaîne de production d’un aliment */
  "g-p2-ch-1": "Les cinq étapes",
  "g-p2-ch-2": "Suivre un yaourt",
  "g-p2-ch-3": "Les cinq étapes",
  "g-p2-ch-4": "Ce que la chaîne dit du monde",
  "g-p2-ch-5": "Ce que la chaîne dit du monde",
  "g-p2-ch-6": "Les cinq étapes",
  /* g-p2-inegalites — Les inégalités de niveau de vie */
  "g-p2-in-1": "Ce qu’on mesure",
  "g-p2-in-2": "Ce qu’on mesure",
  "g-p2-in-3": "Où ça se voit",
  "g-p2-in-4": "Ce qu’on mesure",
  "g-p2-in-5": "Inégalités entre pays, et à l’intérieur",
  "g-p2-in-6": "Ce qu’on mesure",
  /* g-p3-aires — Se repérer sur un planisphère */
  "g-p3-ai-1": "Les continents et les océans",
  "g-p3-ai-2": "Les continents et les océans",
  "g-p3-ai-3": "Les aires régionales",
  "g-p3-ai-4": "Comment tenir ces repères",
  "g-p3-ai-5": "Les continents et les océans",
  "g-p3-ai-6": "Pourquoi ce découpage",
  /* g-p3-acces — L’inégal accès à l’eau, à la santé, à l’école */
  "g-p3-ac-1": "L’eau",
  "g-p3-ac-2": "L’eau",
  "g-p3-ac-3": "L’eau",
  "g-p3-ac-4": "La santé",
  "g-p3-ac-5": "L’école",
  "g-p3-ac-6": "L’eau",
  /* g-p4-se-deplacer — Comment se déplace-t-on dans le monde ? */
  "g-p4-sd-1": "Chaque transport, son infrastructure",
  "g-p4-sd-2": "Chaque transport, son infrastructure",
  "g-p4-sd-3": "Chaque transport, son infrastructure",
  "g-p4-sd-4": "À chaque distance son transport",
  "g-p4-sd-5": "Chaque transport, son infrastructure",
  "g-p4-sd-6": "Qui peut se déplacer",
  /* g-p4-distances — Deux façons de mesurer une distance */
  "g-p4-di-1": "Les kilomètres, et le temps",
  "g-p4-di-2": "Les kilomètres, et le temps",
  "g-p4-di-3": "Le monde s’est rétréci",
  "g-p4-di-4": "Le monde s’est rétréci",
  "g-p4-di-5": "Les kilomètres, et le temps",
  "g-p4-di-6": "Le monde s’est rétréci",
  /* g-p5-internet — Comment marche Internet */
  "g-p5-in-1": "Des câbles, surtout",
  "g-p5-in-2": "Des câbles, surtout",
  "g-p5-in-3": "Des câbles, surtout",
  "g-p5-in-4": "Et les centres de données",
  "g-p5-in-5": "Et les centres de données",
  "g-p5-in-6": "Et les centres de données",
  /* g-p5-fracture — Tout le monde n’a pas Internet */
  "g-p5-fr-1": "",
  "g-p5-fr-2": "À l’échelle de la France",
  "g-p5-fr-3": "À l’échelle de la France",
  "g-p5-fr-4": "À l’échelle du monde",
  "g-p5-fr-5": "Pourquoi ça compte de plus en plus",
  "g-p5-fr-6": "Pourquoi ça compte de plus en plus",
  /* a-p1-saluer — Saluer et se présenter */
  "a-p1-sa-1": "Bonjour, au revoir",
  "a-p1-sa-2": "Bonjour, au revoir",
  "a-p1-sa-3": "Bonjour, au revoir",
  "a-p1-sa-4": "Dire son nom",
  "a-p1-sa-5": "Comment ça va",
  "a-p1-sa-6": "Bonjour, au revoir",
  "a-p1-sa-7": "Bonjour, au revoir",
  "a-p1-sa-8": "Bonjour, au revoir",
  "a-p1-sa-r1": "Bonjour, au revoir",
  "a-p1-sa-r3": "Bonjour, au revoir",
  "a-p1-sa-r2": "Bonjour, au revoir",
  "a-p1-sa-r4": "Dire son nom",
  "a-p1-sa-r5": "Comment ça va",
  "a-p1-sa-r6": "Bonjour, au revoir",
  "a-p1-sa-r7": "Bonjour, au revoir",
  "a-p1-sa-r8": "Bonjour, au revoir",
  /* a-p1-nombres — Les nombres et l’âge */
  "a-p1-no-1": "De un à vingt",
  "a-p1-no-2": "De un à vingt",
  "a-p1-no-3": "Les dizaines, et le trait d’union",
  "a-p1-no-4": "L’âge : avoir ou être ?",
  "a-p1-no-5": "L’âge : avoir ou être ?",
  "a-p1-no-6": "Les dizaines, et le trait d’union",
  "a-p1-no-7": "De un à vingt",
  "a-p1-no-8": "Les dizaines, et le trait d’union",
  /* a-p2-couleurs — Les couleurs et les objets de la classe */
  "a-p2-co-1": "Les couleurs",
  "a-p2-co-2": "Les objets de la classe",
  "a-p2-co-3": "Décrire : l’adjectif passe devant",
  "a-p2-co-4": "Décrire : l’adjectif passe devant",
  "a-p2-co-5": "Les objets de la classe",
  "a-p2-co-6": "Les objets de la classe",
  "a-p2-co-7": "Les couleurs",
  "a-p2-co-8": "Décrire : l’adjectif passe devant",
  /* a-p2-famille — La famille */
  "a-p2-fa-1": "Le vocabulaire",
  "a-p2-fa-2": "Le vocabulaire",
  "a-p2-fa-3": "À qui c’est : les possessifs",
  "a-p2-fa-4": "Le ’s de possession",
  "a-p2-fa-5": "Le vocabulaire",
  "a-p2-fa-6": "À qui c’est : les possessifs",
  "a-p2-fa-7": "Le ’s de possession",
  "a-p2-fa-8": "Le vocabulaire",
  /* a-p3-heure — L’heure et la journée */
  "a-p3-he-1": "Demander et répondre",
  "a-p3-he-2": "Demander et répondre",
  "a-p3-he-3": "Demander et répondre",
  "a-p3-he-4": "Demander et répondre",
  "a-p3-he-5": "Le matin et l’après-midi",
  "a-p3-he-6": "Raconter sa journée",
  "a-p3-he-7": "Raconter sa journée",
  "a-p3-he-8": "Demander et répondre",
  /* a-p4-nourriture — La nourriture, et ce qu’on aime */
  "a-p4-nu-1": "Le vocabulaire",
  "a-p4-nu-2": "I like, I don’t like",
  "a-p4-nu-3": "I like, I don’t like",
  "a-p4-nu-4": "Le vocabulaire",
  "a-p4-nu-5": "Le pluriel des goûts",
  "a-p4-nu-6": "Le vocabulaire",
  "a-p4-nu-7": "I like, I don’t like",
  "a-p4-nu-8": "Le vocabulaire",
  /* a-p4-meteo — Le temps qu’il fait et les saisons */
  "a-p4-mo-1": "Le temps qu’il fait",
  "a-p4-mo-2": "Les saisons et les mois",
  "a-p4-mo-3": "Le temps qu’il fait",
  "a-p4-mo-4": "Les saisons et les mois",
  "a-p4-mo-5": "Les jours",
  "a-p4-mo-6": "Le temps qu’il fait",
  "a-p4-mo-7": "Le temps qu’il fait",
  "a-p4-mo-8": "Les jours",
  /* a-p5-lieux — Les lieux et le chemin */
  "a-p5-li-1": "Les lieux",
  "a-p5-li-2": "Demander et indiquer le chemin",
  "a-p5-li-3": "Demander et indiquer le chemin",
  "a-p5-li-4": "Où c’est",
  "a-p5-li-5": "Où c’est",
  "a-p5-li-6": "Demander et indiquer le chemin",
  "a-p5-li-7": "Où c’est",
  "a-p5-li-8": "Les lieux",
  /* e-p1-regles — Pourquoi il y a des règles */
  "e-p1-re-1": "À quoi servent les règles",
  "e-p1-re-2": "Habitude, règle, loi",
  "e-p1-re-3": "Habitude, règle, loi",
  "e-p1-re-4": "Habitude, règle, loi",
  "e-p1-re-5": "Une règle peut être injuste",
  "e-p1-re-6": "Une règle peut être injuste",
  /* e-p2-republique — La République et ses symboles */
  "e-p2-rp-1": "Les symboles",
  "e-p2-rp-2": "Les symboles",
  "e-p2-rp-3": "Les symboles",
  "e-p2-rp-4": "Ce que veut dire la devise",
  "e-p2-rp-5": "La laïcité",
  "e-p2-rp-6": "Ce que veut dire la devise",
  /* e-p3-differences — Le respect et les différences */
  "e-p3-df-1": "Respecter, ce n’est pas être d’accord",
  "e-p3-df-2": "La discrimination",
  "e-p3-df-3": "Le harcèlement",
  "e-p3-df-4": "Le harcèlement",
  "e-p3-df-5": "Le harcèlement",
  "e-p3-df-6": "Le harcèlement",
  "e-p3-df-7": "Le harcèlement",
  /* e-p3-emotions — Nommer ce qu’on ressent, régler un conflit */
  "e-p3-em-1": "",
  "e-p3-em-2": "Un vocabulaire plus précis",
  "e-p3-em-3": "Ce qui se cache derrière la colère",
  "e-p3-em-4": "Régler un conflit",
  "e-p3-em-5": "Régler un conflit",
  "e-p3-em-6": "Régler un conflit",
  /* e-p4-egalite — L’égalité entre les filles et les garçons */
  "e-p4-eg-1": "Ce que dit le droit, et depuis quand",
  "e-p4-eg-2": "Les stéréotypes",
  "e-p4-eg-3": "Les stéréotypes",
  "e-p4-eg-4": "Les stéréotypes",
  "e-p4-eg-5": "Et dans les faits, aujourd’hui",
  "e-p4-eg-6": "Ce que dit le droit, et depuis quand",
  /* e-p5-decider — Décider ensemble : le vote */
  "e-p5-dc-1": "Voter, et ce que ça suppose",
  "e-p5-dc-2": "Voter, et ce que ça suppose",
  "e-p5-dc-3": "Voter, et ce que ça suppose",
  "e-p5-dc-4": "Les limites du vote",
  "e-p5-dc-5": "Les limites du vote",
  "e-p5-dc-6": "Autres façons de décider",
  "e-p5-dc-7": "Les limites du vote",
  /* ar-p2-couleurs — Les couleurs */
  "ar-p2-cl-1": "Primaires et secondaires",
  "ar-p2-cl-2": "Primaires et secondaires",
  "ar-p2-cl-3": "Primaires et secondaires",
  "ar-p2-cl-4": "Chaudes et froides",
  "ar-p2-cl-5": "Les complémentaires",
  "ar-p2-cl-6": "Les complémentaires",
  "ar-p2-cl-7": "Primaires et secondaires",
  "ar-p2-cl-8": "La peinture et la lumière ne se mélangent pas pareil",
  /* ar-p3-image — Regarder une image */
  "ar-p3-im-1": "Décrire avant d’interpréter",
  "ar-p3-im-2": "La composition dirige le regard",
  "ar-p3-im-3": "La composition dirige le regard",
  "ar-p3-im-4": "La composition dirige le regard",
  "ar-p3-im-5": "Ce qui attire l’œil",
  "ar-p3-im-6": "Décrire avant d’interpréter",
  "ar-p3-im-7": "La composition dirige le regard",
  "ar-p3-im-8": "La composition dirige le regard",
  /* ar-p4-musique — Écouter une musique */
  "ar-p4-mu-1": "Quatre choses à repérer",
  "ar-p4-mu-2": "Quatre choses à repérer",
  "ar-p4-mu-3": "Les familles d’instruments",
  "ar-p4-mu-4": "Les familles d’instruments",
  "ar-p4-mu-5": "La forme : ce qui revient",
  "ar-p4-mu-6": "La forme : ce qui revient",
  "ar-p4-mu-7": "Quatre choses à repérer",
  "ar-p4-mu-8": "Les familles d’instruments",
  /* ar-p5-rythme — Le rythme et la pulsation */
  "ar-p5-ry-1": "La pulsation : le battement régulier",
  "ar-p5-ry-2": "La pulsation : le battement régulier",
  "ar-p5-ry-3": "Le rythme : ce qui se passe par-dessus",
  "ar-p5-ry-4": "La mesure et le silence",
  "ar-p5-ry-5": "La mesure et le silence",
  "ar-p5-ry-6": "La mesure et le silence",
  "ar-p5-ry-7": "La mesure et le silence",
  "ar-p5-ry-8": "La pulsation : le battement régulier",
};
